# -*- coding: utf-8 -*-
"""每个 FEAT_XXX 的中文翻译与功能域归类（由 title 人工翻译）。

GROUP_ORDER 定义功能域分章顺序；META[name] = (中文翻译, 功能域)。
"""

# 功能域常量（同时作为 Markdown 章节标题）
MEM    = "内存管理与地址转换"
MODEL  = "内存模型与原子操作"
FPSIMD = "浮点 / SIMD / 数据类型"
SVE    = "SVE 可伸缩向量扩展"
SME    = "SME 可伸缩矩阵扩展"
SEC    = "安全与内存标记"
VIRT   = "虚拟化"
DEBUG  = "调试与追踪"
PERF   = "性能监控与剖析"
RAS    = "RAS 可靠性、可用性与可维护性"
SYS    = "系统控制、异常与执行状态"

GROUP_ORDER = [MEM, MODEL, FPSIMD, SVE, SME, SEC, VIRT, DEBUG, PERF, RAS, SYS]

META = {
    "FEAT_AA32":               ("PE 支持 AArch32", SYS),
    "FEAT_AA32BF16":           ("AArch32 BFloat16 指令", FPSIMD),
    "FEAT_AA32EL0":            ("EL0 支持 AArch32", SYS),
    "FEAT_AA32EL1":            ("EL1 支持 AArch32", SYS),
    "FEAT_AA32EL2":            ("EL2 支持 AArch32", SYS),
    "FEAT_AA32EL3":            ("EL3 支持 AArch32", SYS),
    "FEAT_AA32HPD":            ("AArch32 分级权限禁用", MEM),
    "FEAT_AA32I8MM":           ("AArch32 Int8 矩阵乘加", FPSIMD),
    "FEAT_AA64":               ("上次复位后 PE 使用 AArch64", SYS),
    "FEAT_AA64EL0":            ("EL0 支持 AArch64", SYS),
    "FEAT_AA64EL1":            ("EL1 支持 AArch64", SYS),
    "FEAT_AA64EL2":            ("EL2 支持 AArch64", SYS),
    "FEAT_AA64EL3":            ("EL3 支持 AArch64", SYS),
    "FEAT_ABLE":               ("地址断点链接扩展", DEBUG),
    "FEAT_ADERR":              ("异步设备错误异常", RAS),
    "FEAT_AES":                ("Advanced SIMD AES 指令", SEC),
    "FEAT_AFP":                ("可选浮点行为（Alternate FP）", FPSIMD),
    "FEAT_AIE":                ("内存属性索引增强", MEM),
    "FEAT_AMU_EXT":            ("外部活动监视器", PERF),
    "FEAT_AMU_EXT32":          ("32 位外部活动监视器", PERF),
    "FEAT_AMU_EXT64":          ("64 位外部活动监视器扩展", PERF),
    "FEAT_AMU_EXTACR":         ("活动监视器外部控制寄存器", PERF),
    "FEAT_AMUv1":              ("活动监视器扩展 v1", PERF),
    "FEAT_AMUv1p1":            ("活动监视器扩展 v1.1", PERF),
    "FEAT_ANERR":              ("异步普通错误异常", RAS),
    "FEAT_ASID16":             ("16 位 ASID", MEM),
    "FEAT_ASID2":              ("支持并发使用两个 ASID", MEM),
    "FEAT_ASMv8p2":            ("A64 ISA 的 Armv8.2 变更", SYS),
    "FEAT_ATS1A":              ("忽略阶段 1 权限的地址转换操作", MEM),
    "FEAT_AdvSIMD":            ("Advanced SIMD 扩展", FPSIMD),
    "FEAT_Armv9_Crypto":       ("Armv9 加密扩展", SEC),
    "FEAT_BBML1":              ("转换表 break-before-make 级别 1", MEM),
    "FEAT_BBML2":              ("转换表 break-before-make 级别 2", MEM),
    "FEAT_BF16":               ("AArch64 BFloat16 指令", FPSIMD),
    "FEAT_BRBE":               ("分支记录缓冲扩展", DEBUG),
    "FEAT_BRBEv1p1":           ("分支记录缓冲扩展 v1.1", DEBUG),
    "FEAT_BTI":                ("分支目标识别", SEC),
    "FEAT_BWE":                ("断点与监视点增强", DEBUG),
    "FEAT_BWE2":               ("断点与监视点增强 2", DEBUG),
    "FEAT_BigEnd":             ("EL1 及以上支持大端", SYS),
    "FEAT_BigEndEL0":          ("EL0 支持大端", SYS),
    "FEAT_CCIDX":              ("扩展的缓存索引", MEM),
    "FEAT_CHK":                ("检查特性状态（CHK）", SYS),
    "FEAT_CLRBHB":             ("支持清除分支历史指令", SEC),
    "FEAT_CMOW":               ("缓存维护权限控制", MEM),
    "FEAT_CMPBR":              ("比较并分支指令", SYS),
    "FEAT_CNTSC":              ("通用计数器缩放", SYS),
    "FEAT_CONSTPACFIELD":      ("PAC 算法增强", SEC),
    "FEAT_CP15SDISABLE2":      ("CP15SDISABLE2", SYS),
    "FEAT_CPA":                ("仅指令的受检指针算术", SEC),
    "FEAT_CPA2":               ("受检指针算术", SEC),
    "FEAT_CRC32":              ("CRC32 指令", SYS),
    "FEAT_CSSC":               ("通用短序列压缩指令", SYS),
    "FEAT_CSV2":               ("缓存推测变体 2（CSV2）", SEC),
    "FEAT_CSV2_1p1":           ("缓存推测变体 2", SEC),
    "FEAT_CSV2_1p2":           ("缓存推测变体 2 v1.2", SEC),
    "FEAT_CSV2_2":             ("缓存推测变体 2 version 2", SEC),
    "FEAT_CSV2_3":             ("缓存推测变体 2 version 3", SEC),
    "FEAT_CSV3":               ("缓存推测变体 3（CSV3）", SEC),
    "FEAT_Crypto":             ("加密扩展", SEC),
    "FEAT_D128":               ("128 位转换表，56 位 PA", MEM),
    "FEAT_DGH":                ("数据聚合提示（Data Gathering Hint）", MODEL),
    "FEAT_DIT":                ("数据无关定时指令", SEC),
    "FEAT_DPB":                ("DC CVAP 指令", MEM),
    "FEAT_DPB2":               ("DC CVADP 指令", MEM),
    "FEAT_Debugv8p1":          ("Debug v8.1", DEBUG),
    "FEAT_Debugv8p2":          ("Debug v8.2", DEBUG),
    "FEAT_Debugv8p4":          ("Debug v8.4", DEBUG),
    "FEAT_Debugv8p8":          ("Debug v8.8", DEBUG),
    "FEAT_Debugv8p9":          ("Debug v8.9", DEBUG),
    "FEAT_DoPD":               ("掉电后调试（Debug over Powerdown）", DEBUG),
    "FEAT_DotProd":            ("Advanced SIMD 点积指令", FPSIMD),
    "FEAT_DoubleFault":        ("双重故障扩展", RAS),
    "FEAT_DoubleFault2":       ("双重故障扩展 v2", RAS),
    "FEAT_DoubleLock":         ("双重锁（Double Lock）", DEBUG),
    "FEAT_E0PD":               ("阻止 EL0 访问地址映射的一半", SEC),
    "FEAT_E2H0":               ("HCR_EL2.E2H 的编程控制", VIRT),
    "FEAT_E3DSE":              ("委派 SError 异常注入", RAS),
    "FEAT_EBEP":               ("基于异常的事件剖析", PERF),
    "FEAT_EBF16":              ("AArch64 扩展 BFloat16 行为", FPSIMD),
    "FEAT_ECBHB":              ("基于分支历史信息的可利用控制（ECBHB）", SEC),
    "FEAT_ECV":                ("增强的计数器虚拟化", VIRT),
    "FEAT_ECV_POFF":           ("增强计数器虚拟化物理偏移", VIRT),
    "FEAT_EDHSR":              ("支持 EDHSR", DEBUG),
    "FEAT_EL0":                ("支持在 EL0 执行", SYS),
    "FEAT_EL1":                ("支持在 EL1 执行", SYS),
    "FEAT_EL2":                ("支持在 EL2 执行", SYS),
    "FEAT_EL3":                ("支持 EL3", SYS),
    "FEAT_EPAC":               ("增强的指针认证", SEC),
    "FEAT_ETE":                ("嵌入式追踪扩展（ETE）", DEBUG),
    "FEAT_ETEv1p1":            ("嵌入式追踪扩展 v1.1", DEBUG),
    "FEAT_ETEv1p2":            ("嵌入式追踪扩展 v1.2", DEBUG),
    "FEAT_ETEv1p3":            ("嵌入式追踪扩展 v1.3", DEBUG),
    "FEAT_ETMv4":              ("嵌入式追踪宏单元 v4（ETM）", DEBUG),
    "FEAT_ETS2":               ("增强的转换同步", MEM),
    "FEAT_ETS3":               ("增强的转换同步", MEM),
    "FEAT_EVT":                ("增强的虚拟化陷阱", VIRT),
    "FEAT_EVT2":               ("增强的虚拟化陷阱 2", VIRT),
    "FEAT_ExS":                ("上下文同步与异常处理控制", SYS),
    "FEAT_F32MM":              ("单精度浮点矩阵乘加", SVE),
    "FEAT_F64MM":              ("双精度浮点矩阵乘加", SVE),
    "FEAT_F8F16MM":            ("8 位浮点矩阵乘加至半精度", FPSIMD),
    "FEAT_F8F32MM":            ("8 位浮点矩阵乘加至单精度", FPSIMD),
    "FEAT_FAMINMAX":           ("浮点最大/最小绝对值指令", FPSIMD),
    "FEAT_FCMA":               ("浮点复数指令", FPSIMD),
    "FEAT_FGT":                ("细粒度陷阱", VIRT),
    "FEAT_FGT2":               ("细粒度陷阱 2", VIRT),
    "FEAT_FGWTE3":             ("EL3 细粒度写陷阱", VIRT),
    "FEAT_FHM":                ("浮点半精度到单精度乘加指令", FPSIMD),
    "FEAT_FP":                 ("浮点扩展", FPSIMD),
    "FEAT_FP16":               ("半精度浮点数据处理", FPSIMD),
    "FEAT_FP8":                ("FP8 转换指令", FPSIMD),
    "FEAT_FP8DOT2":            ("FP8 2 路点积至半精度指令", FPSIMD),
    "FEAT_FP8DOT4":            ("FP8 4 路点积至单精度指令", FPSIMD),
    "FEAT_FP8FMA":             ("FP8 乘加至半精度和单精度指令", FPSIMD),
    "FEAT_FPAC":               ("AUT* 指令认证失败时触发故障", SEC),
    "FEAT_FPACCOMBINE":        ("组合指针认证指令的故障", SEC),
    "FEAT_FPACC_SPEC":         ("指针认证指令的推测行为", SEC),
    "FEAT_FPMR":               ("浮点模式寄存器", FPSIMD),
    "FEAT_FPRCVT":             ("标量 FP 寄存器中的浮点/整数互转", FPSIMD),
    "FEAT_FRINTTS":            ("浮点转整数指令", FPSIMD),
    "FEAT_FlagM":              ("条件标志操作指令", SYS),
    "FEAT_FlagM2":             ("标志操作指令增强", SYS),
    "FEAT_GCS":                ("受保护控制栈扩展（GCS）", SEC),
    "FEAT_GTG":                ("客户机转换粒度大小", MEM),
    "FEAT_HACDBS":             ("清理脏状态的硬件加速器", MEM),
    "FEAT_HAF":                ("访问标志的硬件管理", MEM),
    "FEAT_HAFDBS":             ("脏状态的硬件管理", MEM),
    "FEAT_HAFT":               ("表描述符访问标志的硬件管理", MEM),
    "FEAT_HBC":                ("带提示的条件分支", SYS),
    "FEAT_HCX":                ("支持 HCRX_EL2 寄存器", VIRT),
    "FEAT_HDBSS":              ("硬件脏状态跟踪结构", MEM),
    "FEAT_HPDS":               ("转换表中的分级权限禁用", MEM),
    "FEAT_HPDS2":              ("分级权限禁用", MEM),
    "FEAT_HPMN0":              ("MDCR_EL2.HPMN 可设为零", PERF),
    "FEAT_I8MM":               ("AArch64 Int8 矩阵乘加", FPSIMD),
    "FEAT_IDST":               ("ID 空间陷阱处理", VIRT),
    "FEAT_IDTE3":              ("将 ID 寄存器访问陷阱到 EL3", VIRT),
    "FEAT_IESB":               ("隐式错误同步事件", RAS),
    "FEAT_ITE":                ("插桩追踪扩展", DEBUG),
    "FEAT_IVIPT":              ("IVIPT 扩展", MEM),
    "FEAT_JSCVT":              ("JavaScript 转换指令", FPSIMD),
    "FEAT_LOR":                ("受限排序区域", MODEL),
    "FEAT_LPA":                ("大 PA 与 IPA 支持", MEM),
    "FEAT_LPA2":               ("4KB 和 16KB 粒度的更大物理地址", MEM),
    "FEAT_LRCPC":              ("Load-Acquire RCpc 指令", MODEL),
    "FEAT_LRCPC2":             ("Load-Acquire RCpc 指令 v2", MODEL),
    "FEAT_LRCPC3":             ("Load-Acquire RCpc 指令 v3", MODEL),
    "FEAT_LS64":               ("无状态的 64 字节加载/存储", MODEL),
    "FEAT_LS64WB":             ("面向回写可缓存内存的 LS64", MODEL),
    "FEAT_LS64_ACCDATA":       ("带状态的 64 字节 EL0 存储", MODEL),
    "FEAT_LS64_V":             ("带状态的 64 字节存储", MODEL),
    "FEAT_LSE":                ("大型系统扩展（LSE，原子指令）", MODEL),
    "FEAT_LSE128":             ("128 位原子操作", MODEL),
    "FEAT_LSE2":               ("大型系统扩展 v2", MODEL),
    "FEAT_LSFE":               ("大型系统浮点扩展（浮点原子）", MODEL),
    "FEAT_LSMAOC":             ("AArch32 多寄存器加载/存储原子性与排序控制", MODEL),
    "FEAT_LSUI":               ("非特权加载存储", MODEL),
    "FEAT_LUT":                ("2 位和 4 位索引查表指令", FPSIMD),
    "FEAT_LVA":                ("大 VA 支持", MEM),
    "FEAT_LVA3":               ("56 位 VA", MEM),
    "FEAT_LittleEnd":          ("EL1 及以上支持小端", SYS),
    "FEAT_LittleEndEL0":       ("EL0 支持小端", SYS),
    "FEAT_MEC":                ("内存加密上下文", SEC),
    "FEAT_MOPS":               ("内存操作指令标准化", MODEL),
    "FEAT_MPAM":               ("内存系统资源分区与监控扩展（MPAM）", PERF),
    "FEAT_MPAM_PE_BW_CTRL":    ("MPAM PE 侧带宽控制", PERF),
    "FEAT_MPAMv0p1":           ("MPAM 扩展 v0.1", PERF),
    "FEAT_MPAMv1p0":           ("MPAM 扩展 v1.0", PERF),
    "FEAT_MPAMv1p1":           ("MPAM 扩展 v1.1", PERF),
    "FEAT_MTE":                ("内存标记扩展（MTE）", SEC),
    "FEAT_MTE2":               ("内存标记扩展 2", SEC),
    "FEAT_MTE3":               ("MTE 非对称故障处理", SEC),
    "FEAT_MTE4":               ("增强的内存标记扩展", SEC),
    "FEAT_MTE_ASYM_FAULT":     ("内存标记非对称故障", SEC),
    "FEAT_MTE_ASYNC":          ("标记检查故障的异步报告", SEC),
    "FEAT_MTE_CANONICAL_TAGS": ("对未标记内存的规范标记检查", SEC),
    "FEAT_MTE_NO_ADDRESS_TAGS":("禁用地址标记的内存标记", SEC),
    "FEAT_MTE_PERM":           ("分配标记访问权限", SEC),
    "FEAT_MTE_STORE_ONLY":     ("仅存储标记检查", SEC),
    "FEAT_MTE_TAGGED_FAR":     ("标记检查故障时的 FAR_ELx", SEC),
    "FEAT_MTPMU":              ("多线程 PMU 扩展", PERF),
    "FEAT_MixedEnd":           ("混合端序支持", SYS),
    "FEAT_MixedEndEL0":        ("EL0 混合端序支持", SYS),
    "FEAT_NMI":                ("不可屏蔽中断", SYS),
    "FEAT_NV":                 ("嵌套虚拟化", VIRT),
    "FEAT_NV2":                ("增强的嵌套虚拟化支持", VIRT),
    "FEAT_NV2p1":              ("增强的嵌套虚拟化支持", VIRT),
    "FEAT_OCCMO":              ("外部可缓存缓存维护操作", MEM),
    "FEAT_PACIMP":             ("指针认证 — IMPLEMENTATION DEFINED 算法", SEC),
    "FEAT_PACQARMA3":          ("指针认证 — QARMA3 算法", SEC),
    "FEAT_PACQARMA5":          ("指针认证 — QARMA5 算法", SEC),
    "FEAT_PAN":                ("特权访问禁止（PAN）", SEC),
    "FEAT_PAN2":               ("受 PSTATE.PAN 影响的 AT S1E1R/W 指令变体", SEC),
    "FEAT_PAN3":               ("支持 SCTLR_ELx.EPAN", SEC),
    "FEAT_PAuth":              ("指针认证（PAuth）", SEC),
    "FEAT_PAuth2":             ("指针认证增强", SEC),
    "FEAT_PAuth_LR":           ("以 SP 和 PC 为多样化因子对 LR 签名的指针认证指令", SEC),
    "FEAT_PCDPHINT":           ("生产者-消费者数据放置提示", MODEL),
    "FEAT_PCSRv8":             ("基于 PC 采样的剖析扩展", PERF),
    "FEAT_PCSRv8p2":           ("基于 PC 采样的剖析扩展", PERF),
    "FEAT_PCSRv8p9":           ("Armv8.9 基于 PC 采样的剖析扩展", PERF),
    "FEAT_PFAR":               ("物理故障地址寄存器扩展", RAS),
    "FEAT_PMULL":              ("Advanced SIMD PMULL 指令", SEC),
    "FEAT_PMUv3":              ("PMU 扩展 v3", PERF),
    "FEAT_PMUv3_EDGE":         ("PMU 事件边沿检测", PERF),
    "FEAT_PMUv3_EXT":          ("性能监视器外部接口", PERF),
    "FEAT_PMUv3_EXT32":        ("性能监视器 32 位外部接口", PERF),
    "FEAT_PMUv3_EXT64":        ("性能监视器 64 位外部接口", PERF),
    "FEAT_PMUv3_EXTPMN":       ("为外部代理保留 PMU 事件计数器", PERF),
    "FEAT_PMUv3_ICNTR":        ("固定功能指令计数器", PERF),
    "FEAT_PMUv3_SME":          ("面向 SME 的性能监视器扩展", PERF),
    "FEAT_PMUv3_SS":           ("PMU 快照扩展", PERF),
    "FEAT_PMUv3_TH":           ("事件计数阈值", PERF),
    "FEAT_PMUv3_TH2":          ("性能监视器事件计数器链接扩展", PERF),
    "FEAT_PMUv3p1":            ("Armv8.1 PMU 扩展", PERF),
    "FEAT_PMUv3p4":            ("Armv8.4 PMU 扩展", PERF),
    "FEAT_PMUv3p5":            ("Armv8.5 PMU 扩展", PERF),
    "FEAT_PMUv3p7":            ("Armv8.7 PMU 扩展", PERF),
    "FEAT_PMUv3p8":            ("Armv8.8 PMU 扩展", PERF),
    "FEAT_PMUv3p9":            ("Armv8.9 PMU 扩展", PERF),
    "FEAT_PRFMSLC":            ("PRFM/PRFUM 指令的 SLC 目标支持", MODEL),
    "FEAT_PoPS":               ("物理存储点（Point of Physical Storage）", MEM),
    "FEAT_RAS":                ("可靠性、可用性与可维护性（RAS）扩展", RAS),
    "FEAT_RASv1p1":            ("RAS 扩展 v1.1", RAS),
    "FEAT_RASv2":              ("RAS 扩展 v2", RAS),
    "FEAT_RDM":                ("Advanced SIMD 舍入双倍乘加指令", FPSIMD),
    "FEAT_RME":                ("领域管理扩展（RME）", SEC),
    "FEAT_RME_GDI":            ("RME 颗粒数据隔离扩展", SEC),
    "FEAT_RME_GPC2":           ("RME 颗粒保护检查 2 扩展", SEC),
    "FEAT_RME_GPC3":           ("RME 颗粒保护检查 3 扩展", SEC),
    "FEAT_RNG":                ("随机数生成器", SEC),
    "FEAT_RNG_TRAP":           ("RNDR/RNDRRS 的陷阱支持", SEC),
    "FEAT_RPRES":              ("提高 FRECPE 和 FRSQRTE 精度", FPSIMD),
    "FEAT_RPRFM":              ("支持范围预取内存指令", MODEL),
    "FEAT_S1PIE":              ("阶段 1 权限间接", MEM),
    "FEAT_S1POE":              ("阶段 1 权限叠加", MEM),
    "FEAT_S2FWB":              ("阶段 2 强制回写", MEM),
    "FEAT_S2PIE":              ("阶段 2 权限间接", MEM),
    "FEAT_S2POE":              ("阶段 2 权限叠加", MEM),
    "FEAT_S2TGran16K":         ("阶段 2 支持 16KB 内存转换粒度", MEM),
    "FEAT_S2TGran4K":          ("阶段 2 支持 4KB 内存转换粒度", MEM),
    "FEAT_S2TGran64K":         ("阶段 2 支持 64KB 内存转换粒度", MEM),
    "FEAT_SB":                 ("推测屏障", SEC),
    "FEAT_SCTLR2":             ("SCTLR_ELx 扩展", SYS),
    "FEAT_SEL2":               ("安全 EL2", VIRT),
    "FEAT_SHA1":               ("Advanced SIMD SHA1 指令", SEC),
    "FEAT_SHA256":             ("Advanced SIMD SHA256 指令", SEC),
    "FEAT_SHA3":               ("Advanced SIMD SHA3 指令", SEC),
    "FEAT_SHA512":             ("Advanced SIMD SHA512 指令", SEC),
    "FEAT_SM3":                ("Advanced SIMD SM3 指令", SEC),
    "FEAT_SM4":                ("Advanced SIMD SM4 指令", SEC),
    "FEAT_SME":                ("可伸缩矩阵扩展（SME）", SME),
    "FEAT_SME2":               ("可伸缩矩阵扩展 v2", SME),
    "FEAT_SME2p1":             ("可伸缩矩阵扩展 v2.1", SME),
    "FEAT_SME2p2":             ("可伸缩矩阵扩展 v2.2", SME),
    "FEAT_SME_B16B16":         ("SME ZA 目标的非加宽 BFloat16→BFloat16 算术", SME),
    "FEAT_SME_F16F16":         ("SME2 的非加宽半精度 FP16→FP16 算术", SME),
    "FEAT_SME_F64F64":         ("双精度浮点指令（SME）", SME),
    "FEAT_SME_F8F16":          ("SME2 ZA 目标 FP8 乘加/点积/外积至半精度指令", SME),
    "FEAT_SME_F8F32":          ("SME2 ZA 目标 FP8 乘加/点积/外积至单精度指令", SME),
    "FEAT_SME_FA64":           ("流式 SVE 模式下完整 A64 指令集支持", SME),
    "FEAT_SME_I16I64":         ("16 位到 64 位整数加宽指令", SME),
    "FEAT_SME_LUTv2":          ("4 位索引、8 位元素查表指令", SME),
    "FEAT_SME_MOP4":           ("四分之一片外积指令", SME),
    "FEAT_SME_TMOP":           ("结构化稀疏外积指令", SME),
    "FEAT_SPE":                ("统计剖析扩展（SPE）", PERF),
    "FEAT_SPECRES":            ("推测限制指令", SEC),
    "FEAT_SPECRES2":           ("增强的推测限制指令", SEC),
    "FEAT_SPE_ALTCLK":         ("统计剖析备用时钟域扩展", PERF),
    "FEAT_SPE_ArchInst":       ("统计剖析架构指令采样", PERF),
    "FEAT_SPE_CRR":            ("统计剖析调用返回分支记录", PERF),
    "FEAT_SPE_DPFZS":          ("SPE 冻结时禁用周期计数器", PERF),
    "FEAT_SPE_EFT":            ("统计剖析按类型扩展过滤", PERF),
    "FEAT_SPE_ERnd":           ("统计剖析周期末随机采样", PERF),
    "FEAT_SPE_EXC":            ("SPE 剖析异常扩展", PERF),
    "FEAT_SPE_FDS":            ("统计剖析数据源过滤", PERF),
    "FEAT_SPE_FPF":            ("统计剖析浮点与 SIMD 标志扩展", PERF),
    "FEAT_SPE_FnE":            ("统计剖析反向事件过滤", PERF),
    "FEAT_SPE_LDS":            ("统计剖析数据源数据包生成", PERF),
    "FEAT_SPE_PBT":            ("统计剖析前一分支目标", PERF),
    "FEAT_SPE_SME":            ("面向 SME 的统计剖析扩展", PERF),
    "FEAT_SPE_nVM":            ("统计剖析物理寻址模式扩展", PERF),
    "FEAT_SPEv1p1":            ("统计剖析扩展 v1.1", PERF),
    "FEAT_SPEv1p2":            ("统计剖析扩展 v1.2", PERF),
    "FEAT_SPEv1p3":            ("统计剖析扩展 v1.3", PERF),
    "FEAT_SPEv1p4":            ("统计剖析扩展 v1.4", PERF),
    "FEAT_SPEv1p5":            ("统计剖析扩展 v1.5", PERF),
    "FEAT_SPMU":               ("系统性能监视器扩展", PERF),
    "FEAT_SPMU2":              ("系统性能监视器扩展 v2", PERF),
    "FEAT_SRMASK":             ("按位系统寄存器写掩码", SYS),
    "FEAT_SSBS":               ("推测存储旁路安全（SSBS）", SEC),
    "FEAT_SSBS2":              ("SSBS 的 MRS/MSR 指令 v2", SEC),
    "FEAT_SSVE_AES":           ("流式 SVE 模式 AES 与 128 位多项式长乘指令", SME),
    "FEAT_SSVE_BitPerm":       ("流式可伸缩向量位置换指令", SME),
    "FEAT_SSVE_FEXPA":         ("流式 FEXPA 指令", SME),
    "FEAT_SSVE_FP8DOT2":       ("流式 SVE 模式 FP8 2 路点积至半精度指令", SME),
    "FEAT_SSVE_FP8DOT4":       ("流式 SVE 模式 SVE2 FP8 4 路点积至单精度指令", SME),
    "FEAT_SSVE_FP8FMA":        ("流式 SVE 模式 SVE2 FP8 乘加至半/单精度指令", SME),
    "FEAT_STEP2":              ("增强的软件单步扩展", DEBUG),
    "FEAT_SVE":                ("可伸缩向量扩展（SVE）", SVE),
    "FEAT_SVE2":               ("可伸缩向量扩展 v2", SVE),
    "FEAT_SVE2p1":             ("可伸缩向量扩展 v2.1", SVE),
    "FEAT_SVE2p2":             ("可伸缩向量扩展 v2.2", SVE),
    "FEAT_SVE_AES":            ("可伸缩向量 AES 指令", SVE),
    "FEAT_SVE_AES2":           ("SVE 多向量 AES 与 128 位多项式长乘指令", SVE),
    "FEAT_SVE_B16B16":         ("面向 SVE2 和 SME2 的非加宽 BFloat16→BFloat16 算术", SVE),
    "FEAT_SVE_BFSCALE":        ("BFloat16 浮点指数调整", SVE),
    "FEAT_SVE_BitPerm":        ("可伸缩向量位置换指令", SVE),
    "FEAT_SVE_F16F32MM":       ("SVE 半精度浮点矩阵乘加至单精度", SVE),
    "FEAT_SVE_PMULL128":       ("SVE 单向量 AES 与 128 位多项式长乘指令", SVE),
    "FEAT_SVE_SHA3":           ("可伸缩向量 SHA3 指令", SVE),
    "FEAT_SVE_SM4":            ("可伸缩向量 SM4 指令", SVE),
    "FEAT_SYSINSTR128":        ("128 位系统指令", SYS),
    "FEAT_SYSREG128":          ("128 位系统寄存器", SYS),
    "FEAT_Secure":             ("支持安全状态", SEC),
    "FEAT_SpecSEI":            ("来自推测性内存读取的 SError 中断异常", RAS),
    "FEAT_TCR2":               ("支持 TCR2_ELx", MEM),
    "FEAT_TGran16K":           ("阶段 1 支持 16KB 内存转换粒度", MEM),
    "FEAT_TGran4K":            ("阶段 1 支持 4KB 内存转换粒度", MEM),
    "FEAT_TGran64K":           ("阶段 1 支持 64KB 内存转换粒度", MEM),
    "FEAT_THE":                ("转换加固扩展", MEM),
    "FEAT_TIDCP1":             ("EL0 使用 IMPLEMENTATION DEFINED 功能", SYS),
    "FEAT_TLBIOS":             ("外部可共享域的 TLB 失效指令", MEM),
    "FEAT_TLBIRANGE":          ("TLB 范围失效指令", MEM),
    "FEAT_TLBIW":              ("面向脏状态的 TLBI VMALL", MEM),
    "FEAT_TRBE":               ("追踪缓冲扩展（TRBE）", DEBUG),
    "FEAT_TRBE_EXC":           ("追踪缓冲剖析异常扩展", DEBUG),
    "FEAT_TRBE_EXT":           ("追踪缓冲外部模式", DEBUG),
    "FEAT_TRBE_MPAM":          ("追踪缓冲 MPAM 扩展", DEBUG),
    "FEAT_TRBEv1p1":           ("追踪缓冲扩展 v1.1", DEBUG),
    "FEAT_TRC_EXT":            ("追踪外部寄存器", DEBUG),
    "FEAT_TRC_SR":             ("追踪系统寄存器", DEBUG),
    "FEAT_TRF":                ("自托管追踪扩展", DEBUG),
    "FEAT_TTCNP":              ("转换表公共非私有转换", MEM),
    "FEAT_TTL":                ("转换表级别（TTL）", MEM),
    "FEAT_TTST":               ("小型转换表", MEM),
    "FEAT_TWED":               ("延迟陷阱 WFE", VIRT),
    "FEAT_UAO":                ("非特权访问覆盖控制", SEC),
    "FEAT_UINJ":               ("未定义指令异常注入", SYS),
    "FEAT_VHE":                ("虚拟化主机扩展（VHE）", VIRT),
    "FEAT_VMID16":             ("16 位 VMID", VIRT),
    "FEAT_WFxT":               ("带超时的 WFE 和 WFI 指令", SYS),
    "FEAT_XNX":                ("转换表阶段 2 非特权永不执行", MEM),
    "FEAT_XS":                 ("XS 属性", MODEL),
    "FEAT_nTLBPA":             ("转换表遍历的中间缓存", MEM),
}
