# -*- coding: utf-8 -*-
"""A64 指令的中文一行简介，键为 iform id（由翻译 Workflow 生成，merge_translate.py 汇总）。"""

INSTR_DESC = {
    'ABS': '求绝对值',
    'ADC': '带进位加法',
    'ADCS': '带进位加法并设置标志位',
    'ADD_addsub_ext': '扩展并缩放寄存器后相加',
    'ADD_addsub_imm': '加立即数',
    'ADD_addsub_shift': '加可选移位寄存器',
    'ADDG': '带内存标签的加法',
    'ADDPT': '带检查的指针加法',
    'ADDS_addsub_ext': '扩展并缩放寄存器后相加并设置标志位',
    'ADDS_addsub_imm': '加立即数并设置标志位',
    'ADDS_addsub_shift': '加可选移位寄存器并设置标志位',
    'ADR': '计算PC相对地址',
    'ADRP': '计算PC相对4KB页地址',
    'AND_log_imm': '按位与（立即数）',
    'AND_log_shift': '按位与（移位寄存器）',
    'ANDS_log_imm': '按位与（立即数）并设置标志位',
    'ANDS_log_shift': '按位与（移位寄存器）并设置标志位',
    'APAS_SYS': '关联物理地址空间（SYS 的别名）',
    'ASR_SBFM': '算术右移（立即数）（SBFM 的别名）',
    'ASR_ASRV': '算术右移（寄存器）（ASRV 的别名）',
    'ASRV': '算术右移可变位数',
    'AT_SYS': '地址转换（SYS 的别名）',
    'AUTDA': '使用密钥A验证数据地址',
    'AUTDB': '使用密钥B验证数据地址',
    'AUTIA': '使用密钥A验证指令地址',
    'AUTIA171615': '使用密钥A验证指令地址',
    'AUTIASPPC_imm': '使用密钥A通过立即数偏移验证返回地址',
    'AUTIASPPCR': '使用密钥A通过寄存器验证返回地址',
    'AUTIB': '使用密钥B验证指令地址',
    'AUTIB171615': '使用密钥B验证指令地址',
    'AUTIBSPPC_imm': '使用密钥B通过立即数偏移验证返回地址',
    'AUTIBSPPCR': '使用密钥B通过寄存器验证返回地址',
    'AXFLAG': '将浮点条件标志从ARM格式转换为外部格式',
    'B_uncond': '无条件跳转',
    'B_cond': '条件跳转',
    'BC_cond': '一致性条件跳转',
    'BFC_BFM': '位域清零（BFM 的别名）',
    'BFI_BFM': '位域插入（BFM 的别名）',
    'BFM': '位域移动',
    'BFXIL_BFM': '位域提取并插入低端（BFM 的别名）',
    'BIC_log_shift': '按位清零（移位寄存器）',
    'BICS': '按位清零（移位寄存器）并设置标志位',
    'BL': '带链接跳转',
    'BLR': '跳转到寄存器地址并保存返回地址',
    'BLRA': '带指针认证跳转到寄存器并保存返回地址',
    'BR': '跳转到寄存器地址',
    'BRA': '带指针认证跳转到寄存器',
    'BRB_SYS': '分支记录缓冲区操作（SYS 的别名）',
    'BRK': '断点指令',
    'BTI': '分支目标标识',
    'CAS': '内存中字或双字的比较并交换',
    'CASB': '内存中字节的比较并交换',
    'CASH': '内存中半字的比较并交换',
    'CASP': '内存中字或双字对的比较并交换',
    'CASPT': '非特权字或双字对的比较并交换',
    'CAST': '非特权字或双字的比较并交换',
    'CBcc_imm': '寄存器与立即数比较并按条件跳转',
    'CBcc_regs': '寄存器间比较并按条件跳转',
    'CBBcc_regs': '字节比较并按条件跳转',
    'CBBLE_regs': '字节有符号小于等于比较并跳转（CBB<cc> 的别名）',
    'CBBLO_regs': '字节无符号低于比较并跳转（CBB<cc> 的别名）',
    'CBBLS_regs': '字节无符号低于等于比较并跳转（CBB<cc> 的别名）',
    'CBBLT_regs': '字节有符号小于比较并跳转（CBB<cc> 的别名）',
    'CBGE_imm': '有符号大于等于立即数比较并跳转（CB<cc> 立即数的别名）',
    'CBHcc_regs': '半字比较并按条件跳转',
    'CBHLE_regs': '半字有符号小于等于比较并跳转（CBH<cc> 的别名）',
    'CBHLO_regs': '半字无符号低于比较并跳转（CBH<cc> 的别名）',
    'CBHLS_regs': '半字无符号低于等于比较并跳转（CBH<cc> 的别名）',
    'CBHLT_regs': '半字有符号小于比较并跳转（CBH<cc> 的别名）',
    'CBHS_imm': '无符号高于等于立即数比较并跳转（CB<cc> 立即数的别名）',
    'CBLE_imm': '有符号小于等于立即数比较并跳转（CB<cc> 立即数的别名）',
    'CBLE_regs': '有符号小于等于寄存器比较并跳转（CB<cc> 寄存器的别名）',
    'CBLO_regs': '无符号低于寄存器比较并跳转（CB<cc> 寄存器的别名）',
    'CBLS_imm': '无符号低于等于立即数比较并跳转（CB<cc> 立即数的别名）',
    'CBLS_regs': '无符号低于等于寄存器比较并跳转（CB<cc> 寄存器的别名）',
    'CBLT_regs': '有符号小于寄存器比较并跳转（CB<cc> 寄存器的别名）',
    'CBNZ': '非零比较并跳转',
    'CBZ': '零比较并跳转',
    'CCMN_imm': '条件比较负值（立即数）',
    'CCMN_reg': '条件比较负值（寄存器）',
    'CCMP_imm': '条件比较（立即数）',
    'CCMP_reg': '条件比较（寄存器）',
    'CFINV': '反转进位标志',
    'CFP_SYS': '按上下文限制控制流预测（SYS 的别名）',
    'CHKFEAT': '检查特性状态',
    'CINC_CSINC': '条件递增（CSINC 的别名）',
    'CINV_CSINV': '条件取反（CSINV 的别名）',
    'CLRBHB': '清除分支历史',
    'CLREX': '清除独占访问标记',
    'CLS_int': '计算前导符号位数',
    'CLZ_int': '计算前导零位数',
    'CMN_ADDS_addsub_ext': '比较负值（扩展寄存器）（ADDS 扩展寄存器的别名）',
    'CMN_ADDS_addsub_imm': '比较负值（立即数）（ADDS 立即数的别名）',
    'CMN_ADDS_addsub_shift': '比较负值（移位寄存器）（ADDS 移位寄存器的别名）',
    'CMP_SUBS_addsub_ext': '比较（扩展寄存器）（SUBS 扩展寄存器的别名）',
    'CMP_SUBS_addsub_imm': '比较（立即数）（SUBS 立即数的别名）',
    'CMP_SUBS_addsub_shift': '比较（移位寄存器）（SUBS 移位寄存器的别名）',
    'CMPP_SUBPS': '带标签比较（SUBPS 的别名）',
    'CNEG_CSNEG': '条件取负（CSNEG 的别名）',
    'CNT': '统计置位位数',
    'COSP_SYS': '按上下文清除其他推测预测限制（SYS 的别名）',
    'CPP_SYS': '按上下文限制缓存预取预测（SYS 的别名）',
    'CPYFP': '仅向前内存拷贝',
    'CPYFPN': '仅向前内存拷贝，读写均非时序',
    'CPYFPRN': '仅向前内存拷贝，读非时序',
    'CPYFPRT': '仅向前内存拷贝，非特权读',
    'CPYFPRTN': '仅向前内存拷贝，非特权读且读写非时序',
    'CPYFPRTRN': '仅向前内存拷贝，非特权且非时序读',
    'CPYFPRTWN': '仅向前内存拷贝，非特权读、写非时序',
    'CPYFPT': '仅向前内存拷贝，读写均非特权',
    'CPYFPTN': '仅向前内存拷贝，读写均非特权且非时序',
    'CPYFPTRN': '仅向前内存拷贝，读写非特权、读非时序',
    'CPYFPTWN': '仅向前内存拷贝，读写非特权、写非时序',
    'CPYFPWN': '仅向前内存拷贝，写非时序',
    'CPYFPWT': '仅向前内存拷贝，非特权写',
    'CPYFPWTN': '仅向前内存拷贝，非特权写且读写非时序',
    'CPYFPWTRN': '仅向前内存拷贝，非特权写、读非时序',
    'CPYFPWTWN': '仅向前内存拷贝，非特权且非时序写',
    'CPYP': '内存拷贝',
    'CPYPN': '内存拷贝，读写均非时序',
    'CPYPRN': '内存复制，读取使用非临时访问语义',
    'CPYPRT': '内存复制，读取使用非特权访问语义',
    'CPYPRTN': '内存复制，读取非特权，读写均非临时访问',
    'CPYPRTRN': '内存复制，读取非特权且非临时访问',
    'CPYPRTWN': '内存复制，读取非特权，写入非临时访问',
    'CPYPT': '内存复制，读写均使用非特权访问语义',
    'CPYPTN': '内存复制，读写均非特权且非临时访问',
    'CPYPTRN': '内存复制，读写非特权，读取非临时访问',
    'CPYPTWN': '内存复制，读写非特权，写入非临时访问',
    'CPYPWN': '内存复制，写入使用非临时访问语义',
    'CPYPWT': '内存复制，写入使用非特权访问语义',
    'CPYPWTN': '内存复制，写入非特权，读写均非临时访问',
    'CPYPWTRN': '内存复制，写入非特权，读取非临时访问',
    'CPYPWTWN': '内存复制，写入非特权且非临时访问',
    'CRC32': '计算 CRC32 校验和',
    'CRC32C': '计算 CRC32C 校验和',
    'CSDB': '消费推测数据屏障',
    'CSEL': '条件选择寄存器值',
    'CSET_CSINC': '条件置位（CSINC 的别名）',
    'CSETM_CSINV': '条件置位掩码（CSINV 的别名）',
    'CSINC': '条件选择并加一',
    'CSINV': '条件选择并按位取反',
    'CSNEG': '条件选择并取负',
    'CTZ': '统计尾部零位个数',
    'DC_SYS': '数据缓存操作（SYS 的别名）',
    'DCPS1': '调试模式：将 PE 状态切换到 EL1',
    'DCPS2': '调试模式：将 PE 状态切换到 EL2',
    'DCPS3': '调试模式：将 PE 状态切换到 EL3',
    'DGH': '数据聚集提示',
    'DMB': '数据内存屏障',
    'DRPS': '调试模式：恢复 PE 状态',
    'DSB': '数据同步屏障',
    'DVP_SYS': '按上下文限制数据值预测（SYS 的别名）',
    'EON': '按位异或非（移位寄存器）',
    'EOR_log_imm': '按位异或（立即数）',
    'EOR_log_shift': '按位异或（移位寄存器）',
    'ERET': '从异常返回',
    'ERETA': '带指针认证的异常返回',
    'ESB': '错误同步屏障',
    'EXTR': '从寄存器对中提取位域',
    'GCSB': '受保护控制栈屏障',
    'GCSPOPCX_SYS': '受保护控制栈弹出并比较异常返回记录（SYS 的别名）',
    'GCSPOPM_SYSL': '受保护控制栈弹出（SYSL 的别名）',
    'GCSPOPX_SYS': '受保护控制栈弹出异常返回记录（SYS 的别名）',
    'GCSPUSHM_SYS': '受保护控制栈压栈（SYS 的别名）',
    'GCSPUSHX_SYS': '受保护控制栈压入异常返回记录（SYS 的别名）',
    'GCSSS1_SYS': '受保护控制栈切换栈第一步（SYS 的别名）',
    'GCSSS2_SYSL': '受保护控制栈切换栈第二步（SYSL 的别名）',
    'GCSSTR': '向受保护控制栈存储寄存器',
    'GCSSTTR': '向受保护控制栈存储寄存器（非特权）',
    'GMI': '插入标签掩码',
    'HINT': '提示指令',
    'HLT': '暂停指令',
    'HVC': '调用虚拟机监控程序',
    'IC_SYS': '指令缓存操作（SYS 的别名）',
    'IRG': '插入随机内存标签',
    'ISB': '指令同步屏障',
    'LD64B': '单拷贝原子 64 字节加载',
    'LDADD': '原子加法（字或双字）',
    'LDADDB': '原子加法（字节）',
    'LDADDH': '原子加法（半字）',
    'LDAPR': '加载-获取 RCpc 寄存器',
    'LDAPRB': '加载-获取 RCpc 寄存器字节',
    'LDAPRH': '加载-获取 RCpc 寄存器半字',
    'LDAPUR_gen': '加载-获取 RCpc 寄存器（非比例偏移）',
    'LDAPURB': '加载-获取 RCpc 寄存器字节（非比例偏移）',
    'LDAPURH': '加载-获取 RCpc 寄存器半字（非比例偏移）',
    'LDAPURSB': '加载-获取 RCpc 寄存器有符号字节（非比例偏移）',
    'LDAPURSH': '加载-获取 RCpc 寄存器有符号半字（非比例偏移）',
    'LDAPURSW': '加载-获取 RCpc 寄存器有符号字（非比例偏移）',
    'LDAR': '加载-获取寄存器',
    'LDARB': '加载-获取寄存器字节',
    'LDARH': '加载-获取寄存器半字',
    'LDATXR': '加载-获取非特权独占寄存器',
    'LDAXP': '加载-获取独占寄存器对',
    'LDAXR': '加载-获取独占寄存器',
    'LDAXRB': '加载-获取独占寄存器字节',
    'LDAXRH': '加载-获取独占寄存器半字',
    'LDCLR': '原子位清零（字或双字）',
    'LDCLRB': '原子位清零（字节）',
    'LDCLRH': '原子位清零（半字）',
    'LDCLRP': '原子位清零（四字）',
    'LDEOR': '原子按位异或（字或双字）',
    'LDEORB': '原子按位异或（字节）',
    'LDEORH': '原子按位异或（半字）',
    'LDG': '加载内存分配标签',
    'LDGM': '批量加载内存标签',
    'LDIAPP': '加载-获取 RCpc 有序寄存器对',
    'LDLAR': 'LOAcquire 加载寄存器',
    'LDLARB': 'LOAcquire 加载寄存器字节',
    'LDLARH': 'LOAcquire 加载寄存器半字',
    'LDNP_gen': '加载寄存器对（非临时提示）',
    'LDP_gen': '加载寄存器对',
    'LDPSW': '加载有符号字寄存器对',
    'LDR_imm_gen': '加载寄存器（立即数偏移）',
    'LDR_lit_gen': '加载寄存器（PC 相对字面量）',
    'LDR_reg_gen': '加载寄存器（寄存器偏移）',
    'LDRA': '带指针认证的加载寄存器',
    'LDRB_imm': '加载字节寄存器（立即数偏移）',
    'LDRB_reg': '加载字节寄存器（寄存器偏移）',
    'LDRH_imm': '加载半字寄存器（立即数偏移）',
    'LDRH_reg': '加载半字寄存器（寄存器偏移）',
    'LDRSB_imm': '加载有符号字节寄存器（立即数偏移）',
    'LDRSB_reg': '加载有符号字节寄存器（寄存器偏移）',
    'LDRSH_imm': '加载有符号半字寄存器（立即数偏移）',
    'LDRSH_reg': '加载有符号半字寄存器（寄存器偏移）',
    'LDRSW_imm': '加载有符号字寄存器（立即数偏移）',
    'LDRSW_lit': '加载有符号字寄存器（PC 相对字面量）',
    'LDRSW_reg': '加载有符号字寄存器（寄存器偏移）',
    'LDSET': '原子位置位（字或双字）',
    'LDSETB': '原子位置位（字节）',
    'LDSETH': '原子位置位（半字）',
    'LDSETP': '原子位置位（四字）',
    'LDSMAX': '原子有符号最大值（字或双字）',
    'LDSMAXB': '原子有符号最大值（字节）',
    'LDSMAXH': '原子有符号最大值（半字）',
    'LDSMIN': '原子有符号最小值（字或双字）',
    'LDSMINB': '原子有符号最小值（字节）',
    'LDSMINH': '原子有符号最小值（半字）',
    'LDTADD': '原子非特权加法',
    'LDTCLR': '原子位清零（非特权模式）',
    'LDTNP_gen': '加载非特权寄存器对（非临时提示）',
    'LDTP_gen': '加载非特权寄存器对',
    'LDTR': '加载寄存器（非特权模式）',
    'LDTRB': '加载字节寄存器（非特权模式）',
    'LDTRH': '加载半字寄存器（非特权模式）',
    'LDTRSB': '加载有符号字节寄存器（非特权模式）',
    'LDTRSH': '加载有符号半字寄存器（非特权模式）',
    'LDTRSW': '加载有符号字寄存器（非特权模式）',
    'LDTSET': '原子位置位（非特权模式）',
    'LDTXR': '加载非特权独占寄存器',
    'LDUMAX': '原子无符号最大值操作（字或双字）',
    'LDUMAXB': '原子无符号最大值操作（字节）',
    'LDUMAXH': '原子无符号最大值操作（半字）',
    'LDUMIN': '原子无符号最小值操作（字或双字）',
    'LDUMINB': '原子无符号最小值操作（字节）',
    'LDUMINH': '原子无符号最小值操作（半字）',
    'LDUR_gen': '加载寄存器（非对齐偏移）',
    'LDURB': '加载字节寄存器（非对齐偏移）',
    'LDURH': '加载半字寄存器（非对齐偏移）',
    'LDURSB': '加载有符号字节寄存器（非对齐偏移）',
    'LDURSH': '加载有符号半字寄存器（非对齐偏移）',
    'LDURSW': '加载有符号字寄存器（非对齐偏移）',
    'LDXP': '加载独占寄存器对',
    'LDXR': '加载独占寄存器',
    'LDXRB': '加载独占字节寄存器',
    'LDXRH': '加载独占半字寄存器',
    'LSL_UBFM': '立即数逻辑左移（UBFM 的别名）',
    'LSL_LSLV': '寄存器逻辑左移（LSLV 的别名）',
    'LSLV': '可变逻辑左移',
    'LSR_UBFM': '立即数逻辑右移（UBFM 的别名）',
    'LSR_LSRV': '寄存器逻辑右移（LSRV 的别名）',
    'LSRV': '可变逻辑右移',
    'MADD': '乘加运算',
    'MADDPT': '带检查指针的乘加运算',
    'MNEG_MSUB': '乘法取反（MSUB 的别名）',
    'MOV_ORR_log_imm': '移动位掩码立即数（ORR 立即数的别名）',
    'MOV_MOVN': '移动反转宽立即数（MOVN 的别名）',
    'MOV_ORR_log_shift': '移动寄存器值（ORR 移位寄存器的别名）',
    'MOV_ADD_addsub_imm': '寄存器与 SP 之间移动值（ADD 立即数的别名）',
    'MOV_MOVZ': '移动宽立即数（MOVZ 的别名）',
    'MOVK': '带保留的宽立即数移动',
    'MOVN': '带取反的宽立即数移动',
    'MOVZ': '带零扩展的宽立即数移动',
    'MRRS': '将系统寄存器移动到两个相邻通用寄存器',
    'MRS': '将系统寄存器移动到通用寄存器',
    'MSR_imm': '将立即数移动到特殊寄存器',
    'MSR_reg': '将通用寄存器移动到系统寄存器',
    'MSRR': '将两个相邻通用寄存器移动到系统寄存器',
    'MSUB': '乘减运算',
    'MSUBPT': '带检查指针的乘减运算',
    'MUL_MADD': '乘法（MADD 的别名）',
    'MVN_ORN_log_shift': '按位取反（ORN 移位寄存器的别名）',
    'NEG_SUB_addsub_shift': '取反（移位寄存器）（SUB 移位寄存器的别名）',
    'NEGS_SUBS_addsub_shift': '取反并设置标志位（SUBS 移位寄存器的别名）',
    'NGC_SBC': '带进位取反（SBC 的别名）',
    'NGCS_SBCS': '带进位取反并设置标志位（SBCS 的别名）',
    'NOP': '空操作',
    'ORN_log_shift': '按位 OR NOT（移位寄存器）',
    'ORR_log_imm': '按位 OR（立即数）',
    'ORR_log_shift': '按位 OR（移位寄存器）',
    'PACDA': '为数据地址生成指针认证码（密钥 A）',
    'PACDB': '为数据地址生成指针认证码（密钥 B）',
    'PACGA': '使用通用密钥生成指针认证码',
    'PACIA': '为指令地址生成指针认证码（密钥 A）',
    'PACIA171615': '为指令地址生成指针认证码（密钥 A）',
    'PACIASPPC': '为返回地址生成指针认证码（密钥 A）',
    'PACIB': '为指令地址生成指针认证码（密钥 B）',
    'PACIB171615': '为指令地址生成指针认证码（密钥 B）',
    'PACIBSPPC': '为返回地址生成指针认证码（密钥 B）',
    'PACM': '指针认证修饰符',
    'PACNBIASPPC': '为返回地址生成指针认证码（密钥 A，非分支目标）',
    'PACNBIBSPPC': '为返回地址生成指针认证码（密钥 B，非分支目标）',
    'PRFM_imm': '预取内存（立即数偏移）',
    'PRFM_lit': '预取内存（字面量）',
    'PRFM_reg': '预取内存（寄存器偏移）',
    'PRFUM': '预取内存（非对齐偏移）',
    'PSB': '性能分析同步屏障',
    'PSSBB_DSB': '物理推测性存储绕过屏障（DSB 的别名）',
    'RBIT_int': '按位翻转',
    'RCWCAS': '读检写比较并交换双字（内存）',
    'RCWCASP': '读检写比较并交换四字（内存）',
    'RCWCLR': '读检写原子位清零（双字，内存）',
    'RCWCLRP': '读检写原子位清零（四字，内存）',
    'RCWSCAS': '读检写软件比较并交换双字（内存）',
    'RCWSCASP': '读检写软件比较并交换四字（内存）',
    'RCWSCLR': '读检写软件原子位清零（双字，内存）',
    'RCWSCLRP': '读检写软件原子位清零（四字，内存）',
    'RCWSET': '读检写原子位置位（双字，内存）',
    'RCWSETP': '读检写原子位置位（四字，内存）',
    'RCWSSET': '读检写软件原子位置位（双字，内存）',
    'RCWSSETP': '读检写软件原子位置位（四字，内存）',
    'RCWSSWP': '读检写软件交换双字（内存）',
    'RCWSSWPP': '读检写软件交换四字（内存）',
    'RCWSWP': '读检写交换双字（内存）',
    'RCWSWPP': '读检写交换四字（内存）',
    'RET': '从子程序返回',
    'RETA': '从子程序返回（带指针认证）',
    'RETASPPC_imm': '从子程序返回（增强指针认证，立即数偏移）',
    'RETASPPCR_reg': '从子程序返回（增强指针认证，寄存器偏移）',
    'REV': '字节序翻转',
    'REV16_int': '在 16 位半字内翻转字节序',
    'REV32_int': '在 32 位字内翻转字节序',
    'REV64_REV': '64 位字节序翻转（REV 的别名）',
    'RMIF': '循环移位并掩码插入标志位',
    'ROR_EXTR': '立即数循环右移（EXTR 的别名）',
    'ROR_RORV': '寄存器循环右移（RORV 的别名）',
    'RORV': '可变循环右移',
    'RPRFM_reg': '范围预取内存',
    'SB': '推测屏障',
    'SBC': '带进位减法',
    'SBCS': '带进位减法并设置标志位',
    'SBFIZ_SBFM': '有符号位域插零（SBFM 的别名）',
    'SBFM': '有符号位域移动',
    'SBFX_SBFM': '有符号位域提取（SBFM 的别名）',
    'SDIV': '有符号除法（取商）',
    'SETF': '评估 8 位或 16 位标志值',
    'SETGP': '带标签设置的内存清零',
    'SETGPN': '带标签设置的内存清零（非临时）',
    'SETGPT': '带标签设置的内存清零（非特权模式）',
    'SETGPTN': '带标签设置的内存填充（非特权、非临时）',
    'SETP': '内存填充',
    'SETPN': '内存填充（非临时）',
    'SETPT': '内存填充（非特权）',
    'SETPTN': '内存填充（非特权、非临时）',
    'SEV': '发送事件至所有 PE',
    'SEVL': '发送本地事件',
    'SMADDL': '有符号乘加长（32×32+64→64）',
    'SMAX_imm': '有符号最大值（立即数）',
    'SMAX_reg': '有符号最大值（寄存器）',
    'SMC': '安全监控调用',
    'SMIN_imm': '有符号最小值（立即数）',
    'SMIN_reg': '有符号最小值（寄存器）',
    'SMNEGL_SMSUBL': '有符号乘负长（SMSUBL 的别名）',
    'SMSTART_MSR_imm': '启用 Streaming SVE 模式及 SME 架构状态（MSR immediate 的别名）',
    'SMSTOP_MSR_imm': '禁用 Streaming SVE 模式及 SME 架构状态（MSR immediate 的别名）',
    'SMSUBL': '有符号乘减长（32×32 后减 64→64）',
    'SMULH': '有符号乘高位（64×64→高 64 位）',
    'SMULL_SMADDL': '有符号乘长（SMADDL 的别名）',
    'SSBB_DSB': '推测存储绕过屏障（DSB 的别名）',
    'ST2G': '存储两个分配标签',
    'ST64B': '单拷贝原子 64 字节存储（无状态结果）',
    'ST64BV': '单拷贝原子 64 字节存储（有状态结果）',
    'ST64BV0': '单拷贝原子 64 字节 EL0 存储（有状态结果）',
    'STADD_LDADD': '原子加字或双字（无返回，LDADD 系列的别名）',
    'STADDB_LDADDB': '原子加字节（无返回，LDADDB 系列的别名）',
    'STADDH_LDADDH': '原子加半字（无返回，LDADDH 系列的别名）',
    'STCLR_LDCLR': '原子位清除字或双字（无返回，LDCLR 系列的别名）',
    'STCLRB_LDCLRB': '原子位清除字节（无返回，LDCLRB 系列的别名）',
    'STCLRH_LDCLRH': '原子位清除半字（无返回，LDCLRH 系列的别名）',
    'STEOR_LDEOR': '原子异或字或双字（无返回，LDEOR 系列的别名）',
    'STEORB_LDEORB': '原子异或字节（无返回，LDEORB 系列的别名）',
    'STEORH_LDEORH': '原子异或半字（无返回，LDEORH 系列的别名）',
    'STG': '存储单个分配标签',
    'STGM': '存储多个分配标签',
    'STGP': '存储分配标签及一对寄存器',
    'STILP': '有序存储释放一对寄存器',
    'STLLR': 'LORelease 存储寄存器',
    'STLLRB': 'LORelease 存储寄存器字节',
    'STLLRH': 'LORelease 存储寄存器半字',
    'STLR': '存储释放寄存器',
    'STLRB': '存储释放寄存器字节',
    'STLRH': '存储释放寄存器半字',
    'STLTXR': '存储释放非特权独占寄存器',
    'STLUR_gen': '存储释放寄存器（非对齐偏移）',
    'STLURB': '存储释放寄存器字节（非对齐偏移）',
    'STLURH': '存储释放寄存器半字（非对齐偏移）',
    'STLXP': '存储释放独占一对寄存器',
    'STLXR': '存储释放独占寄存器',
    'STLXRB': '存储释放独占寄存器字节',
    'STLXRH': '存储释放独占寄存器半字',
    'STNP_gen': '存储一对寄存器（非临时提示）',
    'STP_gen': '存储一对寄存器',
    'STR_imm_gen': '存储寄存器（立即数偏移）',
    'STR_reg_gen': '存储寄存器（寄存器偏移）',
    'STRB_imm': '存储寄存器字节（立即数偏移）',
    'STRB_reg': '存储寄存器字节（寄存器偏移）',
    'STRH_imm': '存储寄存器半字（立即数偏移）',
    'STRH_reg': '存储寄存器半字（寄存器偏移）',
    'STSET_LDSET': '原子位置位字或双字（无返回，LDSET 系列的别名）',
    'STSETB_LDSETB': '原子位置位字节（无返回，LDSETB 系列的别名）',
    'STSETH_LDSETH': '原子位置位半字（无返回，LDSETH 系列的别名）',
    'STSHH': '存储共享提示',
    'STSMAX_LDSMAX': '原子有符号最大值字或双字（无返回，LDSMAX 系列的别名）',
    'STSMAXB_LDSMAXB': '原子有符号最大值字节（无返回，LDSMAXB 系列的别名）',
    'STSMAXH_LDSMAXH': '原子有符号最大值半字（无返回，LDSMAXH 系列的别名）',
    'STSMIN_LDSMIN': '原子有符号最小值字或双字（无返回，LDSMIN 系列的别名）',
    'STSMINB_LDSMINB': '原子有符号最小值字节（无返回，LDSMINB 系列的别名）',
    'STSMINH_LDSMINH': '原子有符号最小值半字（无返回，LDSMINH 系列的别名）',
    'STTADD_LDTADD': '非特权原子加（无返回，LDTADD 系列的别名）',
    'STTCLR_LDTCLR': '非特权原子位清除（无返回，LDTCLR 系列的别名）',
    'STTNP_gen': '存储非特权一对寄存器（非临时提示）',
    'STTP_gen': '存储非特权一对寄存器',
    'STTR': '存储寄存器（非特权）',
    'STTRB': '存储寄存器字节（非特权）',
    'STTRH': '存储寄存器半字（非特权）',
    'STTSET_LDTSET': '非特权原子位置位（无返回，LDTSET 系列的别名）',
    'STTXR': '存储非特权独占寄存器',
    'STUMAX_LDUMAX': '原子无符号最大值字或双字（无返回，LDUMAX 系列的别名）',
    'STUMAXB_LDUMAXB': '原子无符号最大值字节（无返回，LDUMAXB 系列的别名）',
    'STUMAXH_LDUMAXH': '原子无符号最大值半字（无返回，LDUMAXH 系列的别名）',
    'STUMIN_LDUMIN': '原子无符号最小值字或双字（无返回，LDUMIN 系列的别名）',
    'STUMINB_LDUMINB': '原子无符号最小值字节（无返回，LDUMINB 系列的别名）',
    'STUMINH_LDUMINH': '原子无符号最小值半字（无返回，LDUMINH 系列的别名）',
    'STUR_gen': '存储寄存器（非对齐偏移）',
    'STURB': '存储寄存器字节（非对齐偏移）',
    'STURH': '存储寄存器半字（非对齐偏移）',
    'STXP': '存储独占一对寄存器',
    'STXR': '存储独占寄存器',
    'STXRB': '存储独占寄存器字节',
    'STXRH': '存储独占寄存器半字',
    'STZ2G': '存储两个分配标签并清零内存',
    'STZG': '存储单个分配标签并清零内存',
    'STZGM': '存储多个分配标签并清零内存',
    'SUB_addsub_ext': '减法（扩展并缩放寄存器）',
    'SUB_addsub_imm': '减法（立即数）',
    'SUB_addsub_shift': '减法（可选移位寄存器）',
    'SUBG': '带标签的减法',
    'SUBP': '指针相减',
    'SUBPS': '指针相减并设置标志位',
    'SUBPT': '带检查的指针相减',
    'SUBS_addsub_ext': '减法并设置标志位（扩展并缩放寄存器）',
    'SUBS_addsub_imm': '减法并设置标志位（立即数）',
    'SUBS_addsub_shift': '减法并设置标志位（可选移位寄存器）',
    'SVC': '管理员调用（系统调用）',
    'SWP': '原子交换字或双字',
    'SWPB': '原子交换字节',
    'SWPH': '原子交换半字',
    'SWPP': '原子交换四字（128 位）',
    'SWPT': '非特权原子交换',
    'SXTB_SBFM': '有符号字节扩展（SBFM 的别名）',
    'SXTH_SBFM': '有符号半字扩展（SBFM 的别名）',
    'SXTW_SBFM': '有符号字扩展（SBFM 的别名）',
    'SYS': '系统指令',
    'SYSL': '带返回值的系统指令',
    'SYSP': '128 位系统指令',
    'TBNZ': '测试位非零则跳转',
    'TBZ': '测试位为零则跳转',
    'TLBI_SYS': 'TLB 无效化操作（SYS 的别名）',
    'TLBIP_SYSP': 'TLB 无效化配对操作（SYSP 的别名）',
    'TRCIT_SYS': '跟踪插桩（SYS 的别名）',
    'TSB': '跟踪同步屏障',
    'TST_ANDS_log_imm': '按位测试（立即数）（ANDS 立即数的别名）',
    'TST_ANDS_log_shift': '按位测试（移位寄存器）（ANDS 移位寄存器的别名）',
    'UBFIZ_UBFM': '无符号位域插入零（UBFM 的别名）',
    'UBFM': '无符号位域移动',
    'UBFX_UBFM': '无符号位域提取（UBFM 的别名）',
    'UDF_perm_undef': '永久未定义指令',
    'UDIV': '无符号除法（取商）',
    'UMADDL': '无符号乘加长（32位×32位+64位→64位）',
    'UMAX_imm': '无符号最大值（立即数）',
    'UMAX_reg': '无符号最大值（寄存器）',
    'UMIN_imm': '无符号最小值（立即数）',
    'UMIN_reg': '无符号最小值（寄存器）',
    'UMNEGL_UMSUBL': '无符号乘法取负长（UMSUBL 的别名）',
    'UMSUBL': '无符号乘减长（32位×32位，64位减）',
    'UMULH': '无符号乘法高位结果',
    'UMULL_UMADDL': '无符号乘法长（UMADDL 的别名）',
    'UXTB_UBFM': '无符号字节零扩展（UBFM 的别名）',
    'UXTH_UBFM': '无符号半字零扩展（UBFM 的别名）',
    'WFE': '等待事件',
    'WFET': '带超时的等待事件',
    'WFI': '等待中断',
    'WFIT': '带超时的等待中断',
    'XAFLAG': '将浮点条件标志从外部格式转换为 Arm 格式',
    'XPAC': '去除指针认证码（PAC）',
    'YIELD': '让出处理器提示',
    'ABS_advsimd': '向量绝对值',
    'ADD_advsimd': '向量加法',
    'ADDHN_advsimd': '加法并取高位窄结果（ADDHN/ADDHN2）',
    'ADDP_advsimd_pair': '成对元素相加（标量）',
    'ADDP_advsimd_vec': '成对相加（向量）',
    'ADDV_advsimd': '向量跨通道累加',
    'AESD_advsimd': 'AES 单轮解密',
    'AESE_advsimd': 'AES 单轮加密',
    'AESIMC_advsimd': 'AES 逆混列变换',
    'AESMC_advsimd': 'AES 混列变换',
    'AND_advsimd': '向量按位与',
    'BCAX_advsimd': '位清除后异或',
    'BF12CVTL_advsimd': '8位浮点转换为 BFloat16（向量）',
    'BFCVT_float': '单精度转换为 BFloat16（标量）',
    'BFCVTN_advsimd': '单精度转换为 BFloat16（向量，BFCVTN/BFCVTN2）',
    'BFDOT_advsimd_elt': 'BFloat16 点积到单精度（向量，按元素）',
    'BFDOT_advsimd_vec': 'BFloat16 点积到单精度（向量）',
    'BFMLAL_advsimd_elt': 'BFloat16 乘加到单精度（按元素）',
    'BFMLAL_advsimd_vec': 'BFloat16 乘加到单精度（向量）',
    'BFMMLA_advsimd': 'BFloat16 矩阵乘累加到单精度',
    'BIC_advsimd_imm': '向量按位清除（立即数）',
    'BIC_advsimd_reg': '向量按位清除（寄存器）',
    'BIF_advsimd': '条件为假时按位插入',
    'BIT_advsimd': '条件为真时按位插入',
    'BSL_advsimd': '按位选择',
    'CLS_advsimd': '统计前导符号位数（向量）',
    'CLZ_advsimd': '统计前导零位数（向量）',
    'CMEQ_advsimd_reg': '按位比较相等（向量，寄存器）',
    'CMEQ_advsimd_zero': '按位比较是否等于零（向量）',
    'CMGE_advsimd_reg': '有符号比较大于等于（向量，寄存器）',
    'CMGE_advsimd_zero': '有符号比较大于等于零（向量）',
    'CMGT_advsimd_reg': '有符号比较大于（向量，寄存器）',
    'CMGT_advsimd_zero': '有符号比较大于零（向量）',
    'CMHI_advsimd': '无符号比较更高（向量，寄存器）',
    'CMHS_advsimd': '无符号比较大于等于（向量，寄存器）',
    'CMLE_advsimd': '有符号比较小于等于零（向量）',
    'CMLT_advsimd': '有符号比较小于零（向量）',
    'CMTST_advsimd': '按位测试非零比较（向量）',
    'CNT_advsimd': '按字节统计置位位数',
    'DUP_advsimd_elt': '将向量元素复制到向量或标量',
    'DUP_advsimd_gen': '将通用寄存器值复制到向量',
    'EOR_advsimd': '向量按位异或',
    'EOR3_advsimd': '三路按位异或',
    'EXT_advsimd': '从两个向量中提取拼接向量',
    'F12CVTL_advsimd': '8位浮点转换为半精度（向量）',
    'FABD_advsimd': '浮点绝对差（向量）',
    'FABS_float': '浮点绝对值（标量）',
    'FABS_advsimd': '浮点绝对值（向量）',
    'FACGE_advsimd': '浮点绝对值比较大于等于（向量）',
    'FACGT_advsimd': '浮点绝对值比较大于（向量）',
    'FADD_float': '浮点加法（标量）',
    'FADD_advsimd': '浮点加法（向量）',
    'FADDP_advsimd_pair': '浮点成对元素相加（标量）',
    'FADDP_advsimd_vec': '浮点成对相加（向量）',
    'FAMAX_advsimd': '浮点绝对最大值',
    'FAMIN_advsimd': '浮点绝对最小值',
    'FCADD_advsimd_vec': '浮点复数加法',
    'FCCMP_float': '浮点条件静默比较（标量）',
    'FCCMPE_float': '浮点条件信号比较（标量）',
    'FCMEQ_advsimd_reg': '浮点比较相等（向量，寄存器）',
    'FCMEQ_advsimd_zero': '浮点比较等于零（向量）',
    'FCMGE_advsimd_reg': '浮点比较大于等于（向量，寄存器）',
    'FCMGE_advsimd_zero': '浮点比较大于等于零（向量）',
    'FCMGT_advsimd_reg': '浮点比较大于（向量，寄存器）',
    'FCMGT_advsimd_zero': '浮点比较大于零（向量）',
    'FCMLA_advsimd_vec': '浮点复数乘累加（向量）',
    'FCMLA_advsimd_elt': '浮点复数乘累加（按元素）',
    'FCMLE_advsimd': '浮点比较小于等于零（向量）',
    'FCMLT_advsimd': '浮点比较小于零（向量）',
    'FCMP_float': '浮点静默比较（标量）',
    'FCMPE_float': '浮点信号比较（标量）',
    'FCSEL_float': '浮点条件选择（标量）',
    'FCVT_float': '浮点精度转换（标量）',
    'FCVTAS_sisd': '浮点转有符号整数，向最近舍入（标量 SIMD&FP）',
    'FCVTAS_float': '浮点转有符号整数，向最近舍入（标量）',
    'FCVTAS_advsimd': '浮点转有符号整数，向最近舍入（向量）',
    'FCVTAU_sisd': '浮点转无符号整数，向最近舍入（标量 SIMD&FP）',
    'FCVTAU_float': '浮点转无符号整数，向最近舍入（标量）',
    'FCVTAU_advsimd': '浮点转无符号整数，向最近舍入（向量）',
    'FCVTL_advsimd': '浮点转高精度长格式（向量，FCVTL/FCVTL2）',
    'FCVTMS_sisd': '浮点转有符号整数，向负无穷舍入（标量 SIMD&FP）',
    'FCVTMS_float': '浮点转有符号整数，向负无穷舍入（标量）',
    'FCVTMS_advsimd': '浮点转有符号整数，向负无穷舍入（向量）',
    'FCVTMU_sisd': '浮点转无符号整数，向负无穷舍入（标量 SIMD&FP）',
    'FCVTMU_float': '浮点转无符号整数，向负无穷舍入（标量）',
    'FCVTMU_advsimd': '浮点转无符号整数，向负无穷舍入（向量）',
    'FCVTN_advsimd_168': '半精度转换为8位浮点（向量）',
    'FCVTN_advsimd': '浮点转低精度窄格式（向量，FCVTN/FCVTN2）',
    'FCVTN_advsimd_328': '单精度转换为8位浮点（向量，FCVTN/FCVTN2）',
    'FCVTNS_sisd': '浮点转有符号整数，就近舍入偶数（标量 SIMD&FP）',
    'FCVTNS_float': '浮点转有符号整数，就近舍入偶数（标量）',
    'FCVTNS_advsimd': '浮点转有符号整数，就近舍入偶数（向量）',
    'FCVTNU_sisd': '浮点转无符号整数，就近舍入偶数（标量 SIMD&FP）',
    'FCVTNU_float': '浮点转无符号整数，就近舍入（偶数优先）（标量）',
    'FCVTNU_advsimd': '浮点转无符号整数，就近舍入（偶数优先）（向量）',
    'FCVTPS_sisd': '浮点转有符号整数，向正无穷舍入（标量 SIMD&FP）',
    'FCVTPS_float': '浮点转有符号整数，向正无穷舍入（标量）',
    'FCVTPS_advsimd': '浮点转有符号整数，向正无穷舍入（向量）',
    'FCVTPU_sisd': '浮点转无符号整数，向正无穷舍入（标量 SIMD&FP）',
    'FCVTPU_float': '浮点转无符号整数，向正无穷舍入（标量）',
    'FCVTPU_advsimd': '浮点转无符号整数，向正无穷舍入（向量）',
    'FCVTXN_advsimd': '浮点降精度窄化转换，奇数舍入（向量）',
    'FCVTZS_sisd': '浮点转有符号整数，向零舍入（标量 SIMD&FP）',
    'FCVTZS_float_fix': '浮点转有符号定点数，向零舍入（标量）',
    'FCVTZS_float_int': '浮点转有符号整数，向零舍入（标量）',
    'FCVTZS_advsimd_fix': '浮点转有符号定点数，向零舍入（向量）',
    'FCVTZS_advsimd_int': '浮点转有符号整数，向零舍入（向量）',
    'FCVTZU_sisd': '浮点转无符号整数，向零舍入（标量 SIMD&FP）',
    'FCVTZU_float_fix': '浮点转无符号定点数，向零舍入（标量）',
    'FCVTZU_float_int': '浮点转无符号整数，向零舍入（标量）',
    'FCVTZU_advsimd_fix': '浮点转无符号定点数，向零舍入（向量）',
    'FCVTZU_advsimd_int': '浮点转无符号整数，向零舍入（向量）',
    'FDIV_float': '浮点除法（标量）',
    'FDIV_advsimd': '浮点除法（向量）',
    'FDOT_advsimd_2wayelem': '8 位浮点点积累加至半精度（向量，按元素）',
    'FDOT_advsimd_2wayvec': '8 位浮点点积累加至半精度（向量）',
    'FDOT_advsimd_4wayelem': '8 位浮点点积累加至单精度（向量，按元素）',
    'FDOT_advsimd_4wayvec': '8 位浮点点积累加至单精度（向量）',
    'FJCVTZS': '浮点 JavaScript 风格转有符号定点数，向零舍入',
    'FMADD_float': '浮点融合乘加（标量）',
    'FMAX_float': '浮点最大值（标量）',
    'FMAX_advsimd': '浮点最大值（向量）',
    'FMAXNM_float': '浮点数值最大值（标量）',
    'FMAXNM_advsimd': '浮点数值最大值（向量）',
    'FMAXNMP_advsimd_pair': '相邻元素对浮点数值最大值（标量）',
    'FMAXNMP_advsimd_vec': '浮点数值最大值逐对归约（向量）',
    'FMAXNMV_advsimd': '浮点数值最大值跨向量归约',
    'FMAXP_advsimd_pair': '相邻元素对浮点最大值（标量）',
    'FMAXP_advsimd_vec': '浮点最大值逐对归约（向量）',
    'FMAXV_advsimd': '浮点最大值跨向量归约',
    'FMIN_float': '浮点最小值（标量）',
    'FMIN_advsimd': '浮点最小值（向量）',
    'FMINNM_float': '浮点数值最小值（标量）',
    'FMINNM_advsimd': '浮点数值最小值（向量）',
    'FMINNMP_advsimd_pair': '相邻元素对浮点数值最小值（标量）',
    'FMINNMP_advsimd_vec': '浮点数值最小值逐对归约（向量）',
    'FMINNMV_advsimd': '浮点数值最小值跨向量归约',
    'FMINP_advsimd_pair': '相邻元素对浮点最小值（标量）',
    'FMINP_advsimd_vec': '浮点最小值逐对归约（向量）',
    'FMINV_advsimd': '浮点最小值跨向量归约',
    'FMLA_advsimd_elt': '浮点融合乘加至累加器（按元素）',
    'FMLA_advsimd_vec': '浮点融合乘加至累加器（向量）',
    'FMLAL_advsimd_elt': '浮点融合长乘加至累加器（按元素）',
    'FMLAL_advsimd_vec': '浮点融合长乘加至累加器（向量）',
    'FMLALB_advsimd_elem': '8 位浮点乘加至半精度（向量，按元素）',
    'FMLALB_advsimd_vec': '8 位浮点乘加至半精度（向量）',
    'FMLALLBB_advsimd_elem': '8 位浮点乘加至单精度（向量，按元素）',
    'FMLALLBB_advsimd_vec': '8 位浮点乘加至单精度（向量）',
    'FMLS_advsimd_elt': '浮点融合乘减至累加器（按元素）',
    'FMLS_advsimd_vec': '浮点融合乘减至累加器（向量）',
    'FMLSL_advsimd_elt': '浮点融合长乘减至累加器（按元素）',
    'FMLSL_advsimd_vec': '浮点融合长乘减至累加器（向量）',
    'FMMLA_FP8FP16': '8 位浮点矩阵乘累加至半精度',
    'FMMLA_FP8FP32': '8 位浮点矩阵乘累加至单精度',
    'FMOV_float_gen': '浮点与通用寄存器间无转换移动',
    'FMOV_float': '浮点寄存器间无转换移动',
    'FMOV_float_imm': '浮点立即数移动（标量）',
    'FMOV_advsimd': '浮点立即数移动（向量）',
    'FMSUB_float': '浮点融合乘减（标量）',
    'FMUL_advsimd_elt': '浮点乘法（按元素）',
    'FMUL_float': '浮点乘法（标量）',
    'FMUL_advsimd_vec': '浮点乘法（向量）',
    'FMULX_advsimd_vec': '浮点扩展乘法',
    'FMULX_advsimd_elt': '浮点扩展乘法（按元素）',
    'FNEG_float': '浮点取反（标量）',
    'FNEG_advsimd': '浮点取反（向量）',
    'FNMADD_float': '浮点否定融合乘加（标量）',
    'FNMSUB_float': '浮点否定融合乘减（标量）',
    'FNMUL_float': '浮点乘法取反（标量）',
    'FRECPE_advsimd': '浮点倒数估算',
    'FRECPS_advsimd': '浮点倒数迭代步进',
    'FRECPX_advsimd': '浮点倒数指数（标量）',
    'FRINT32X_float': '浮点舍入至 32 位整数，使用当前舍入模式（标量）',
    'FRINT32X_advsimd': '浮点舍入至 32 位整数，使用当前舍入模式（向量）',
    'FRINT32Z_float': '浮点舍入至 32 位整数，向零舍入（标量）',
    'FRINT32Z_advsimd': '浮点舍入至 32 位整数，向零舍入（向量）',
    'FRINT64X_float': '浮点舍入至 64 位整数，使用当前舍入模式（标量）',
    'FRINT64X_advsimd': '浮点舍入至 64 位整数，使用当前舍入模式（向量）',
    'FRINT64Z_float': '浮点舍入至 64 位整数，向零舍入（标量）',
    'FRINT64Z_advsimd': '浮点舍入至 64 位整数，向零舍入（向量）',
    'FRINTA_float': '浮点舍入至整数，就近远离零舍入（标量）',
    'FRINTA_advsimd': '浮点舍入至整数，就近远离零舍入（向量）',
    'FRINTI_float': '浮点舍入至整数，使用当前舍入模式（标量）',
    'FRINTI_advsimd': '浮点舍入至整数，使用当前舍入模式（向量）',
    'FRINTM_float': '浮点舍入至整数，向负无穷舍入（标量）',
    'FRINTM_advsimd': '浮点舍入至整数，向负无穷舍入（向量）',
    'FRINTN_float': '浮点舍入至整数，就近偶数舍入（标量）',
    'FRINTN_advsimd': '浮点舍入至整数，就近偶数舍入（向量）',
    'FRINTP_float': '浮点舍入至整数，向正无穷舍入（标量）',
    'FRINTP_advsimd': '浮点舍入至整数，向正无穷舍入（向量）',
    'FRINTX_float': '浮点精确舍入至整数，使用当前舍入模式（标量）',
    'FRINTX_advsimd': '浮点精确舍入至整数，使用当前舍入模式（向量）',
    'FRINTZ_float': '浮点舍入至整数，向零舍入（标量）',
    'FRINTZ_advsimd': '浮点舍入至整数，向零舍入（向量）',
    'FRSQRTE_advsimd': '浮点倒数平方根估算',
    'FRSQRTS_advsimd': '浮点倒数平方根迭代步进',
    'FSCALE_advsimd': '按向量调整浮点指数',
    'FSQRT_float': '浮点平方根（标量）',
    'FSQRT_advsimd': '浮点平方根（向量）',
    'FSUB_float': '浮点减法（标量）',
    'FSUB_advsimd': '浮点减法（向量）',
    'INS_advsimd_elt': '从另一向量元素插入向量元素',
    'INS_advsimd_gen': '从通用寄存器插入向量元素',
    'LD1_advsimd_mult': '加载多个单元素结构到一至四个寄存器',
    'LD1_advsimd_sngl': '加载一个单元素结构到寄存器指定通道',
    'LD1R_advsimd': '加载单元素结构并复制到寄存器所有通道',
    'LD2_advsimd_mult': '加载多个 2 元素结构到两个寄存器',
    'LD2_advsimd_sngl': '加载单个 2 元素结构到两寄存器指定通道',
    'LD2R_advsimd': '加载单个 2 元素结构并复制到两寄存器所有通道',
    'LD3_advsimd_mult': '加载多个 3 元素结构到三个寄存器',
    'LD3_advsimd_sngl': '加载单个 3 元素结构到三寄存器指定通道',
    'LD3R_advsimd': '加载单个 3 元素结构并复制到三寄存器所有通道',
    'LD4_advsimd_mult': '加载多个 4 元素结构到四个寄存器',
    'LD4_advsimd_sngl': '加载单个4元素结构体到四个寄存器的指定通道',
    'LD4R_advsimd': '加载单个4元素结构体并复制到四个寄存器的所有通道',
    'LDAP1_advsimd_sngl': 'Load-acquire RCpc 单元素结构体到一个SIMD&FP寄存器的指定通道',
    'LDAPUR_fpsimd': 'Load-acquire RCpc SIMD&FP寄存器（无缩放偏移）',
    'LDBFADD': '原子BFloat16加法',
    'LDBFMAX': '原子BFloat16最大值',
    'LDBFMAXNM': '原子BFloat16最大数值（number）',
    'LDBFMIN': '原子BFloat16最小值',
    'LDBFMINNM': '原子BFloat16最小数值（number）',
    'LDFADD': '原子浮点加法',
    'LDFMAX': '原子浮点最大值',
    'LDFMAXNM': '原子浮点最大数值（number）',
    'LDFMIN': '原子浮点最小值',
    'LDFMINNM': '原子浮点最小数值（number）',
    'LDNP_fpsimd': '加载一对SIMD&FP寄存器（非临时访问提示）',
    'LDP_fpsimd': '加载一对SIMD&FP寄存器',
    'LDR_imm_fpsimd': '加载SIMD&FP寄存器（立即数偏移）',
    'LDR_lit_fpsimd': '加载SIMD&FP寄存器（PC相对字面量）',
    'LDR_reg_fpsimd': '加载SIMD&FP寄存器（寄存器偏移）',
    'LDTNP_fpsimd': '非特权加载一对SIMD&FP寄存器（非临时访问提示）',
    'LDTP_fpsimd': '非特权加载一对SIMD&FP寄存器',
    'LDUR_fpsimd': '加载SIMD&FP寄存器（无缩放偏移）',
    'LUTI2_advsimd': '使用2位索引读查找表',
    'LUTI4_advsimd': '使用4位索引读查找表',
    'MLA_advsimd_elt': '乘加累积（向量，按元素）',
    'MLA_advsimd_vec': '乘加累积（向量）',
    'MLS_advsimd_elt': '乘减累积（向量，按元素）',
    'MLS_advsimd_vec': '乘减累积（向量）',
    'MOV_INS_advsimd_elt': '将向量元素移动到另一向量元素（INS element 的别名）',
    'MOV_INS_advsimd_gen': '将通用寄存器移动到向量元素（INS general 的别名）',
    'MOV_DUP_advsimd_elt': '将向量元素移动到标量（DUP element 的别名）',
    'MOV_UMOV_advsimd': '将向量元素移动到通用寄存器（UMOV 的别名）',
    'MOV_ORR_advsimd_reg': '移动向量（ORR vector register 的别名）',
    'MOVI_advsimd': '向量立即数传送',
    'MUL_advsimd_elt': '向量按元素乘法',
    'MUL_advsimd_vec': '向量乘法',
    'MVN_NOT_advsimd': '向量按位取反（NOT 的别名）',
    'MVNI_advsimd': '向量取反立即数传送',
    'NEG_advsimd': '向量取反',
    'NOT_advsimd': '向量按位取反',
    'ORN_advsimd': '向量按位OR NOT',
    'ORR_advsimd_imm': '向量按位OR（立即数）',
    'ORR_advsimd_reg': '向量按位OR（寄存器）',
    'PMUL_advsimd': '多项式乘法',
    'PMULL_advsimd': '多项式长乘法',
    'RADDHN_advsimd': '舍入加法取高位窄结果',
    'RAX1_advsimd': '循环移位并异或',
    'RBIT_advsimd': '向量按位反转',
    'REV16_advsimd': '向量内16位半字字节逆序',
    'REV32_advsimd': '向量内32位字字节逆序',
    'REV64_advsimd': '向量内64位双字字节逆序',
    'RSHRN_advsimd': '舍入右移窄化（立即数）',
    'RSUBHN_advsimd': '舍入减法取高位窄结果',
    'SABA_advsimd': '有符号绝对差并累加',
    'SABAL_advsimd': '有符号绝对差并累加长整型',
    'SABD_advsimd': '有符号绝对差',
    'SABDL_advsimd': '有符号绝对差长整型',
    'SADALP_advsimd': '有符号成对加法并累加长整型',
    'SADDL_advsimd': '有符号长整型加法（向量）',
    'SADDLP_advsimd': '有符号成对长整型加法',
    'SADDLV_advsimd': '有符号长整型跨向量加法',
    'SADDW_advsimd': '有符号宽加法',
    'SCVTF_sisd': '有符号整数转浮点（标量SIMD&FP）',
    'SCVTF_float_fix': '有符号定点数转浮点（标量）',
    'SCVTF_float_int': '有符号整数转浮点（标量）',
    'SCVTF_advsimd_fix': '有符号定点数转浮点（向量）',
    'SCVTF_advsimd_int': '有符号整数转浮点（向量）',
    'SDOT_advsimd_elt': '有符号点积运算（向量，按元素）',
    'SDOT_advsimd_vec': '有符号点积运算（向量）',
    'SHA1C_advsimd': 'SHA1哈希更新（choose）',
    'SHA1H_advsimd': 'SHA1固定旋转',
    'SHA1M_advsimd': 'SHA1哈希更新（majority）',
    'SHA1P_advsimd': 'SHA1哈希更新（parity）',
    'SHA1SU0_advsimd': 'SHA1调度更新0',
    'SHA1SU1_advsimd': 'SHA1调度更新1',
    'SHA256H_advsimd': 'SHA-256哈希更新第1部分',
    'SHA256H2_advsimd': 'SHA-256哈希更新第2部分',
    'SHA256SU0_advsimd': 'SHA-256调度更新0',
    'SHA256SU1_advsimd': 'SHA-256调度更新1',
    'SHA512H_advsimd': 'SHA-512哈希更新第1部分',
    'SHA512H2_advsimd': 'SHA-512哈希更新第2部分',
    'SHA512SU0_advsimd': 'SHA-512调度更新0',
    'SHA512SU1_advsimd': 'SHA-512调度更新1',
    'SHADD_advsimd': '有符号折半加法',
    'SHL_advsimd': '左移（立即数）',
    'SHLL_advsimd': '按元素大小左移长整型',
    'SHRN_advsimd': '右移窄化（立即数）',
    'SHSUB_advsimd': '有符号折半减法',
    'SLI_advsimd': '左移并插入（立即数）',
    'SM3PARTW1_advsimd': 'SM3消息扩展第一步',
    'SM3PARTW2_advsimd': 'SM3消息扩展第二步',
    'SM3SS1_advsimd': 'SM3压缩函数SS1计算',
    'SM3TT1A_advsimd': 'SM3压缩函数TT1A轮函数',
    'SM3TT1B_advsimd': 'SM3压缩函数TT1B轮函数',
    'SM3TT2A_advsimd': 'SM3压缩函数TT2A轮函数',
    'SM3TT2B_advsimd': 'SM3压缩函数TT2B轮函数',
    'SM4E_advsimd': 'SM4加密轮函数',
    'SM4EKEY_advsimd': 'SM4密钥扩展',
    'SMAX_advsimd': '有符号最大值（向量）',
    'SMAXP_advsimd': '有符号成对最大值',
    'SMAXV_advsimd': '有符号跨向量最大值',
    'SMIN_advsimd': '有符号最小值（向量）',
    'SMINP_advsimd': '有符号成对最小值',
    'SMINV_advsimd': '有符号跨向量最小值',
    'SMLAL_advsimd_elt': '有符号乘加长整型（向量，按元素）',
    'SMLAL_advsimd_vec': '有符号乘加长整型（向量）',
    'SMLSL_advsimd_elt': '有符号乘减长整型（向量，按元素）',
    'SMLSL_advsimd_vec': '有符号乘减长整型（向量）',
    'SMMLA_advsimd_vec': '有符号8位整数矩阵乘累加到32位整数（向量）',
    'SMOV_advsimd': '有符号向量元素移动到通用寄存器',
    'SMULL_advsimd_elt': '有符号长整型乘法（向量，按元素）',
    'SMULL_advsimd_vec': '有符号长整型乘法（向量）',
    'SQABS_advsimd': '有符号饱和绝对值',
    'SQADD_advsimd': '有符号饱和加法',
    'SQDMLAL_advsimd_elt': '有符号饱和倍精度乘加长整型（按元素）',
    'SQDMLAL_advsimd_vec': '有符号饱和倍精度乘加长整型',
    'SQDMLSL_advsimd_elt': '有符号饱和倍精度乘减长整型（按元素）',
    'SQDMLSL_advsimd_vec': '有符号饱和倍精度乘减长整型',
    'SQDMULH_advsimd_elt': '有符号饱和倍精度乘法取高半（按元素）',
    'SQDMULH_advsimd_vec': '有符号饱和倍精度乘法取高半',
    'SQDMULL_advsimd_elt': '有符号饱和倍增长乘法（按元素）',
    'SQDMULL_advsimd_vec': '有符号饱和倍增长乘法（向量）',
    'SQNEG_advsimd': '有符号饱和取反',
    'SQRDMLAH_advsimd_elt': '有符号饱和舍入倍增乘累加取高半部分（按元素）',
    'SQRDMLAH_advsimd_vec': '有符号饱和舍入倍增乘累加取高半部分（向量）',
    'SQRDMLSH_advsimd_elt': '有符号饱和舍入倍增乘减取高半部分（按元素）',
    'SQRDMLSH_advsimd_vec': '有符号饱和舍入倍增乘减取高半部分（向量）',
    'SQRDMULH_advsimd_elt': '有符号饱和舍入倍增乘法取高半部分（按元素）',
    'SQRDMULH_advsimd_vec': '有符号饱和舍入倍增乘法取高半部分（向量）',
    'SQRSHL_advsimd': '有符号饱和舍入左移（寄存器）',
    'SQRSHRN_advsimd': '有符号饱和舍入右移窄化（立即数）',
    'SQRSHRUN_advsimd': '有符号饱和舍入右移无符号窄化（立即数）',
    'SQSHL_advsimd_imm': '有符号饱和左移（立即数）',
    'SQSHL_advsimd_reg': '有符号饱和左移（寄存器）',
    'SQSHLU_advsimd': '有符号饱和左移转无符号（立即数）',
    'SQSHRN_advsimd': '有符号饱和右移窄化（立即数）',
    'SQSHRUN_advsimd': '有符号饱和右移无符号窄化（立即数）',
    'SQSUB_advsimd': '有符号饱和减法',
    'SQXTN_advsimd': '有符号饱和提取窄化',
    'SQXTUN_advsimd': '有符号饱和提取无符号窄化',
    'SRHADD_advsimd': '有符号舍入折半加法',
    'SRI_advsimd': '右移并插入（立即数）',
    'SRSHL_advsimd': '有符号舍入左移（寄存器）',
    'SRSHR_advsimd': '有符号舍入右移（立即数）',
    'SRSRA_advsimd': '有符号舍入右移并累加（立即数）',
    'SSHL_advsimd': '有符号左移（寄存器）',
    'SSHLL_advsimd': '有符号长左移（立即数）',
    'SSHR_advsimd': '有符号右移（立即数）',
    'SSRA_advsimd': '有符号右移并累加（立即数）',
    'SSUBL_advsimd': '有符号长减法',
    'SSUBW_advsimd': '有符号宽减法',
    'ST1_advsimd_mult': '将1/2/3/4个寄存器中的多个单元素结构存储到内存',
    'ST1_advsimd_sngl': '将单个寄存器某通道的单元素结构存储到内存',
    'ST2_advsimd_mult': '将两个寄存器中的多个2元素结构存储到内存',
    'ST2_advsimd_sngl': '将两个寄存器某通道的单个2元素结构存储到内存',
    'ST3_advsimd_mult': '将三个寄存器中的多个3元素结构存储到内存',
    'ST3_advsimd_sngl': '将三个寄存器某通道的单个3元素结构存储到内存',
    'ST4_advsimd_mult': '将四个寄存器中的多个4元素结构存储到内存',
    'ST4_advsimd_sngl': '将四个寄存器某通道的单个4元素结构存储到内存',
    'STBFADD': '原子 BFloat16 浮点加法（无返回）',
    'STBFMAX': '原子 BFloat16 浮点最大值（无返回）',
    'STBFMAXNM': '原子 BFloat16 浮点最大数（无返回）',
    'STBFMIN': '原子 BFloat16 浮点最小值（无返回）',
    'STBFMINNM': '原子 BFloat16 浮点最小数（无返回）',
    'STFADD': '原子浮点加法（无返回）',
    'STFMAX': '原子浮点最大值（无返回）',
    'STFMAXNM': '原子浮点最大数（无返回）',
    'STFMIN': '原子浮点最小值（无返回）',
    'STFMINNM': '原子浮点最小数（无返回）',
    'STL1_advsimd_sngl': '释放存储 SIMD&FP 寄存器某通道的单元素结构',
    'STLUR_fpsimd': '释放存储 SIMD&FP 寄存器（无缩放偏移）',
    'STNP_fpsimd': '存储一对 SIMD&FP 寄存器（非临时提示）',
    'STP_fpsimd': '存储一对 SIMD&FP 寄存器',
    'STR_imm_fpsimd': '存储 SIMD&FP 寄存器（立即数偏移）',
    'STR_reg_fpsimd': '存储 SIMD&FP 寄存器（寄存器偏移）',
    'STTNP_fpsimd': '非特权存储一对 SIMD&FP 寄存器（非临时提示）',
    'STTP_fpsimd': '非特权存储一对 SIMD&FP 寄存器',
    'STUR_fpsimd': '存储 SIMD&FP 寄存器（无缩放偏移）',
    'SUB_advsimd': '向量减法',
    'SUBHN_advsimd': '减法取高位窄化结果',
    'SUDOT_advsimd_elt': '有符号与无符号整数点积（向量，按元素）',
    'SUQADD_advsimd': '有符号饱和累加无符号值',
    'SXTL_SSHLL_advsimd': '有符号长扩展（SSHLL/SSHLL2 的别名）',
    'TBL_advsimd': '向量表查找',
    'TBX_advsimd': '向量表查找扩展',
    'TRN1_advsimd': '向量转置（主）',
    'TRN2_advsimd': '向量转置（次）',
    'UABA_advsimd': '无符号绝对差并累加',
    'UABAL_advsimd': '无符号绝对差并长累加',
    'UABD_advsimd': '无符号绝对差（向量）',
    'UABDL_advsimd': '无符号绝对差长结果',
    'UADALP_advsimd': '无符号成对加法并长累加',
    'UADDL_advsimd': '无符号长加法（向量）',
    'UADDLP_advsimd': '无符号成对长加法',
    'UADDLV_advsimd': '无符号跨向量长求和',
    'UADDW_advsimd': '无符号宽加法',
    'UCVTF_sisd': '无符号整数转浮点（标量 SIMD&FP）',
    'UCVTF_float_fix': '无符号定点数转浮点（标量）',
    'UCVTF_float_int': '无符号整数转浮点（标量）',
    'UCVTF_advsimd_fix': '无符号定点数转浮点（向量）',
    'UCVTF_advsimd_int': '无符号整数转浮点（向量）',
    'UDOT_advsimd_elt': '无符号整数点积（向量，按元素）',
    'UDOT_advsimd_vec': '无符号整数点积（向量）',
    'UHADD_advsimd': '无符号折半加法',
    'UHSUB_advsimd': '无符号折半减法',
    'UMAX_advsimd': '无符号最大值（向量）',
    'UMAXP_advsimd': '无符号成对最大值',
    'UMAXV_advsimd': '无符号跨向量最大值',
    'UMIN_advsimd': '无符号最小值（向量）',
    'UMINP_advsimd': '无符号成对最小值',
    'UMINV_advsimd': '无符号跨向量最小值',
    'UMLAL_advsimd_elt': '无符号长乘累加（向量，按元素）',
    'UMLAL_advsimd_vec': '无符号长乘累加（向量）',
    'UMLSL_advsimd_elt': '无符号长乘减（向量，按元素）',
    'UMLSL_advsimd_vec': '无符号长乘减（向量）',
    'UMMLA_advsimd_vec': '无符号8位整数矩阵乘累加至32位整数（向量）',
    'UMOV_advsimd': '将向量元素无符号移动到通用寄存器',
    'UMULL_advsimd_elt': '无符号长乘法（向量，按元素）',
    'UMULL_advsimd_vec': '无符号长乘法（向量）',
    'UQADD_advsimd': '无符号饱和加法',
    'UQRSHL_advsimd': '无符号饱和舍入左移（寄存器）',
    'UQRSHRN_advsimd': '无符号饱和舍入右移窄化（立即数）',
    'UQSHL_advsimd_imm': '无符号饱和左移（立即数）',
    'UQSHL_advsimd_reg': '无符号饱和左移（寄存器）',
    'UQSHRN_advsimd': '无符号饱和右移窄化（立即数）',
    'UQSUB_advsimd': '无符号饱和减法',
    'UQXTN_advsimd': '无符号饱和提取窄化',
    'URECPE_advsimd': '无符号倒数估算',
    'URHADD_advsimd': '无符号舍入折半加法',
    'URSHL_advsimd': '无符号舍入左移（寄存器）',
    'URSHR_advsimd': '无符号舍入右移（立即数）',
    'URSQRTE_advsimd': '无符号倒数平方根估算',
    'URSRA_advsimd': '无符号舍入右移并累加（立即数）',
    'USDOT_advsimd_elt': '无符号与有符号整数点积（向量，按元素）',
    'USDOT_advsimd_vec': '无符号与有符号整数点积（向量）',
    'USHL_advsimd': '无符号左移（寄存器）',
    'USHLL_advsimd': '无符号长左移（立即数）',
    'USHR_advsimd': '无符号右移（立即数）',
    'USMMLA_advsimd_vec': '无符号与有符号8位整数矩阵乘累加至32位整数（向量）',
    'USQADD_advsimd': '无符号饱和累加有符号值',
    'USRA_advsimd': '无符号右移并累加（立即数）',
    'USUBL_advsimd': '无符号长减法',
    'USUBW_advsimd': '无符号宽减法',
    'UXTL_USHLL_advsimd': '无符号长扩展（USHLL/USHLL2 的别名）',
    'UZP1_advsimd': '向量解交织（低半部分）',
    'UZP2_advsimd': '向量解交织（高半部分）',
    'XAR_advsimd': '异或并旋转',
    'XTN_advsimd': '窄化提取',
    'ZIP1_advsimd': '向量交织（低半部分）',
    'ZIP2_advsimd': '向量交织（高半部分）',
    'abs_z_p_z': '取绝对值（有谓词）',
    'adclb_z_zzz': '带进位长加法（低位）',
    'adclt_z_zzz': '带进位长加法（高位）',
    'add_z_zi': '加立即数（无谓词）',
    'add_z_p_zz': '向量加法（有谓词）',
    'add_z_zz': '向量加法（无谓词）',
    'addhnb_z_zz': '加法取高位窄化（低位）',
    'addhnt_z_zz': '加法取高位窄化（高位）',
    'addp_z_p_zz': '成对加法',
    'addpl_r_ri': '将谓词寄存器大小的倍数加到标量寄存器',
    'addpt_z_p_zz': '经检查指针向量加法（有谓词）',
    'addpt_z_zz': '经检查指针向量加法（无谓词）',
    'addqv_z_p_z': '四字向量段的加法归约',
    'addvl_r_ri': '将向量寄存器大小的倍数加到标量寄存器',
    'adr_z_az': '计算向量地址',
    'aesd_mz_zzi': '多向量 AES 单轮解密（索引）',
    'aesd_z_zz': 'AES 单轮解密',
    'aesdimc_mz_zzi': '多向量 AES 单轮解密并逆混列',
    'aese_mz_zzi': '多向量 AES 单轮加密（索引）',
    'aese_z_zz': 'AES 单轮加密',
    'aesemc_mz_zzi': '多向量 AES 单轮加密并混列',
    'aesimc_z_z': 'AES 逆混列',
    'aesmc_z_z': 'AES 混列',
    'and_z_zi': '按位与立即数（无谓词）',
    'and_p_p_pp': '谓词按位与',
    'and_z_p_zz': '向量按位与（有谓词）',
    'and_z_zz': '向量按位与（无谓词）',
    'andqv_z_p_z': '四字向量段按位与归约',
    'ands_p_p_pp': '谓词按位与并设置条件标志',
    'andv_r_p_z': '向量按位与归约到标量',
    'asr_z_p_zi': '算术右移立即数（有谓词）',
    'asr_z_zi': '算术右移立即数（无谓词）',
    'asr_z_p_zz': '按向量算术右移（有谓词）',
    'asr_z_p_zw': '按 64 位宽元素算术右移（有谓词）',
    'asr_z_zw': '按 64 位宽元素算术右移（无谓词）',
    'asrd_z_p_zi': '算术右移用于除以立即数（有谓词）',
    'asrr_z_p_zz': '反向按向量算术右移（有谓词）',
    'bcax_z_zzz': '按位清除并异或',
    'bdep_z_zz': '将低位按位掩码所选位置分散',
    'bext_z_zz': '从位掩码所选位置收集低位',
    'bf1cvt_z_z8': '8 位浮点转换为 BFloat16',
    'bf1cvtlt_z_z8': '8 位浮点转换为 BFloat16（高位）',
    'bfadd_z_p_zz': 'BFloat16 加法（有谓词）',
    'bfadd_z_zz': 'BFloat16 加法（无谓词）',
    'bfclamp_z_zz': 'BFloat16 钳位到最小/最大值',
    'bfcvt_z_p_z': '单精度转换为 BFloat16（有谓词）',
    'bfcvtn_z8_mz2': 'BFloat16 转换为交错 8 位浮点',
    'bfcvtnt_z_p_z': '单精度转换为 BFloat16（高位，有谓词）',
    'bfdot_z_zzzi': 'BFloat16 点积（索引元素）累加到单精度',
    'bfdot_z_zzz': 'BFloat16 点积累加到单精度',
    'bfmax_z_p_zz': 'BFloat16 最大值（有谓词）',
    'bfmaxnm_z_p_zz': 'BFloat16 数值最大值（有谓词）',
    'bfmin_z_p_zz': 'BFloat16 最小值（有谓词）',
    'bfminnm_z_p_zz': 'BFloat16 数值最小值（有谓词）',
    'bfmla_z_zzzi': 'BFloat16 融合乘加（索引元素）',
    'bfmla_z_p_zzz': 'BFloat16 融合乘加（向量）',
    'bfmlalb_z_zzzi': 'BFloat16 乘加到单精度（索引，低位）',
    'bfmlalb_z_zzz': 'BFloat16 乘加到单精度（低位）',
    'bfmlalt_z_zzzi': 'BFloat16 乘加到单精度（索引，高位）',
    'bfmlalt_z_zzz': 'BFloat16 乘加到单精度（高位）',
    'bfmls_z_zzzi': 'BFloat16 融合乘减（索引元素）',
    'bfmls_z_p_zzz': 'BFloat16 融合乘减（向量）',
    'bfmlslb_z_zzzi': 'BFloat16 乘减自单精度（索引，低位）',
    'bfmlslb_z_zzz': 'BFloat16 乘减自单精度（低位）',
    'bfmlslt_z_zzzi': 'BFloat16 乘减自单精度（索引，高位）',
    'bfmlslt_z_zzz': 'BFloat16 乘减自单精度（高位）',
    'bfmmla_z_zzz': 'BFloat16 矩阵乘累加到单精度',
    'bfmul_z_zzi': 'BFloat16 乘以索引元素',
    'bfmul_z_p_zz': 'BFloat16 乘法（有谓词）',
    'bfmul_z_zz': 'BFloat16 乘法（无谓词）',
    'bfscale_z_p_zz': 'BFloat16 调整指数（有谓词）',
    'bfsub_z_p_zz': 'BFloat16 减法（有谓词）',
    'bfsub_z_zz': 'BFloat16 减法（无谓词）',
    'bgrp_z_zz': '按位掩码将位分组到右侧或左侧',
    'bic_and_z_zi': '用立即数按位清除（无谓词，AND 立即数的别名）',
    'bic_p_p_pp': '谓词按位清除',
    'bic_z_p_zz': '向量按位清除（有谓词）',
    'bic_z_zz': '向量按位清除（无谓词）',
    'bics_p_p_pp': '谓词按位清除并设置条件标志',
    'brka_p_p_p': '在首个真条件后中断',
    'brkas_p_p_p': '在首个真条件后中断并设置条件标志',
    'brkb_p_p_p': '在首个真条件前中断',
    'brkbs_p_p_p': '在首个真条件前中断并设置条件标志',
    'brkn_p_p_pp': '将中断传播到下一分区',
    'brkns_p_p_pp': '将中断传播到下一分区并设置条件标志',
    'brkpa_p_p_pp': '从前一分区传播后在首个真条件后中断',
    'brkpas_p_p_pp': '从前一分区传播后在首个真条件后中断并设置条件标志',
    'brkpb_p_p_pp': '从前一分区传播后在首个真条件前中断',
    'brkpbs_p_p_pp': '从前一分区传播后在首个真条件前中断并设置条件标志',
    'bsl_z_zzz': '按位选择',
    'bsl1n_z_zzz': '按位选择（第一输入取反）',
    'bsl2n_z_zzz': '按位选择（第二输入取反）',
    'cadd_z_zz': '复数整数加法',
    'cdot_z_zzzi': '复数整数点积（索引元素）',
    'cdot_z_zzz': '复数整数点积',
    'clasta_r_p_z': '按条件提取末位后元素到通用寄存器',
    'clasta_v_p_z': '按条件提取末位后元素到 SIMD&FP 标量寄存器',
    'clasta_z_p_zz': '按条件提取末位后元素到向量寄存器',
    'clastb_r_p_z': '按条件提取最后元素到通用寄存器',
    'clastb_v_p_z': '按条件提取最后元素到 SIMD&FP 标量寄存器',
    'clastb_z_p_zz': '按条件提取最后元素到向量寄存器',
    'cls_z_p_z': '计算前导符号位数（有谓词）',
    'clz_z_p_z': '计算前导零位数（有谓词）',
    'cmla_z_zzzi': '复数整数乘加（索引元素）',
    'cmla_z_zzz': '复数整数乘加',
    'cmpeq_p_p_zi': '向量与立即数比较',
    'cmpeq_p_p_zz': '向量比较',
    'cmpeq_p_p_zw': '向量与 64 位宽元素比较',
    'cmple_cmpeq_p_p_zz': '有符号小于等于向量比较（CMP<cc> 向量的别名）',
    'cmplo_cmpeq_p_p_zz': '无符号低于向量比较（CMP<cc> 向量的别名）',
    'cmpls_cmpeq_p_p_zz': '比较向量（无符号小于等于），设置条件标志（CMP<cc>（向量）的别名）',
    'cmplt_cmpeq_p_p_zz': '比较向量（有符号小于），设置条件标志（CMP<cc>（向量）的别名）',
    'cnot_z_p_z': '逻辑取反布尔条件（有谓词）',
    'cnt_z_p_z': '统计非零位数（有谓词）',
    'cntb_r_s': '将标量设为谓词约束元素计数的倍数',
    'cntp_r_pn': '将标量设为谓词计数器中的计数',
    'cntp_r_p_p': '将标量设为谓词中真元素的数量',
    'compact_z_p_z': '将活跃向量元素复制到低编号元素位置',
    'cpy_z_p_i': '将有符号整数立即数复制到向量元素（合并）',
    'cpy_z_o_i': '将有符号整数立即数复制到向量元素（清零）',
    'cpy_z_p_r': '将通用寄存器复制到向量元素（有谓词）',
    'cpy_z_p_v': '将 SIMD&FP 标量寄存器复制到向量元素（有谓词）',
    'ctermeq_rr': '比较并终止循环',
    'decb_r_rs': '将标量减去谓词约束元素计数的倍数',
    'decd_z_zs': '将向量减去谓词约束元素计数的倍数',
    'decp_r_p_r': '将标量减去谓词中真元素的数量',
    'decp_z_p_z': '将向量减去谓词中真元素的数量',
    'dup_z_i': '将有符号立即数广播到向量所有元素（无谓词）',
    'dup_z_zi': '将索引元素广播到整个向量（无谓词）',
    'dup_z_r': '将通用寄存器广播到向量所有元素（无谓词）',
    'dupm_z_i': '将逻辑位掩码立即数广播到向量（无谓词）',
    'dupq_z_zi': '在每个四字向量段内广播索引元素（无谓词）',
    'eon_eor_z_zi': '与取反立即数按位异或（无谓词）（EOR（立即数）的别名）',
    'eor_z_zi': '与立即数按位异或（无谓词）',
    'eor_p_p_pp': '谓词按位异或',
    'eor_z_p_zz': '向量按位异或（有谓词）',
    'eor_z_zz': '向量按位异或（无谓词）',
    'eor3_z_zzz': '三个向量之间按位异或',
    'eorbt_z_zz': '交错按位异或（低半部分与高半部分）',
    'eorqv_z_p_z': '四字向量段的按位异或归约',
    'eors_p_p_pp': '谓词按位异或并设置条件标志',
    'eortb_z_zz': '交错按位异或（高半部分与低半部分）',
    'eorv_r_p_z': '向量按位异或归约到标量',
    'expand_z_p_z': '将低编号向量元素复制到活跃元素位置',
    'ext_z_zi': '从两个向量中提取向量片段',
    'extq_z_zi': '从每对四字向量段中提取向量段',
    'f1cvt_z_z8': '8位浮点数转换为半精度浮点数',
    'f1cvtlt_z_z8': '8位浮点数转换为半精度浮点数（高半部分）',
    'fabd_z_p_zz': '浮点绝对差（有谓词）',
    'fabs_z_p_z': '浮点绝对值（有谓词）',
    'facge_p_p_zz': '浮点绝对值比较',
    'facle_facge_p_p_zz': '浮点绝对值比较（小于等于）（FAC<cc> 的别名）',
    'faclt_facge_p_p_zz': '浮点绝对值比较（小于）（FAC<cc> 的别名）',
    'fadd_z_p_zs': '浮点加立即数（有谓词）',
    'fadd_z_p_zz': '浮点加法（有谓词）',
    'fadd_z_zz': '浮点加法（无谓词）',
    'fadda_v_p_z': '浮点严格顺序累加归约到标量',
    'faddp_z_p_zz': '浮点相邻元素加法',
    'faddqv_z_p_z': '四字向量段浮点加法递归归约',
    'faddv_v_p_z': '浮点加法递归归约到标量',
    'famax_z_p_zz': '浮点绝对值最大值（有谓词）',
    'famin_z_p_zz': '浮点绝对值最小值（有谓词）',
    'fcadd_z_p_zz': '浮点复数加法（有谓词）',
    'fclamp_z_zz': '浮点数钳制到最小/最大数',
    'fcmeq_p_p_zz': '浮点向量比较',
    'fcmeq_p_p_z0': '浮点与零比较',
    'fcmla_z_zzzi': '浮点复数乘加（按索引元素，有谓词）',
    'fcmla_z_p_zzz': '浮点复数乘加（有谓词）',
    'fcmle_fcmeq_p_p_zz': '浮点向量比较（小于等于）（FCM<cc>（向量）的别名）',
    'fcmlt_fcmeq_p_p_zz': '浮点向量比较（小于）（FCM<cc>（向量）的别名）',
    'fcpy_z_p_i': '将浮点立即数复制到向量元素（有谓词）',
    'fcvt_z_p_z': '浮点格式转换（有谓词）',
    'fcvtlt_z_p_z': '浮点扩展转换（高半部分，有谓词）',
    'fcvtn_z8_mz2': '半精度转换为交错8位浮点数',
    'fcvtnb_z8_mz2': '单精度转换为交错8位浮点数（低半部分）',
    'fcvtnt_z_p_z': '浮点窄化转换（高半部分，有谓词）',
    'fcvtnt_z8_mz2': '单精度转换为交错8位浮点数（高半部分）',
    'fcvtx_z_p_z': '双精度转换为单精度，取奇数舍入（有谓词）',
    'fcvtxnt_z_p_z': '双精度转换为单精度，取奇数舍入（高半部分，有谓词）',
    'fcvtzs_z_p_z': '浮点转换为有符号整数，向零舍入（有谓词）',
    'fcvtzu_z_p_z': '浮点转换为无符号整数，向零舍入（有谓词）',
    'fdiv_z_p_zz': '浮点除法（有谓词）',
    'fdivr_z_p_zz': '浮点反向除法（有谓词）',
    'fdot_z_zzzi': '半精度按索引元素点积到单精度（2路）',
    'fdot_z_zz8z8i': '8位浮点按索引元素点积到半精度（2路）',
    'fdot_z_zzz': '半精度点积到单精度（2路）',
    'fdot_z_zz8z8': '8位浮点点积到半精度（2路）',
    'fdot_z32_zz8z8i': '8位浮点按索引元素点积到单精度（4路）',
    'fdot_z32_zz8z8': '8位浮点点积到单精度（4路）',
    'fdup_z_i': '将浮点立即数广播到向量所有元素（无谓词）',
    'fexpa_z_z': '浮点指数加速器',
    'firstp_r_p_p': '获取第一个真谓词元素的标量索引（有谓词）',
    'flogb_z_p_z': '浮点以2为底的对数（整数结果）',
    'fmad_z_p_zzz': '浮点融合乘加到被乘数（有谓词）',
    'fmax_z_p_zs': '浮点与立即数取最大值（有谓词）',
    'fmax_z_p_zz': '浮点向量取最大值（有谓词）',
    'fmaxnm_z_p_zs': '浮点与立即数取最大数（有谓词）',
    'fmaxnm_z_p_zz': '浮点向量取最大数（有谓词）',
    'fmaxnmp_z_p_zz': '浮点相邻元素取最大数',
    'fmaxnmqv_z_p_z': '四字向量段浮点最大数递归归约',
    'fmaxnmv_v_p_z': '浮点最大数递归归约到标量',
    'fmaxp_z_p_zz': '浮点相邻元素取最大值',
    'fmaxqv_z_p_z': '四字向量段浮点最大值归约',
    'fmaxv_v_p_z': '浮点最大值递归归约到标量',
    'fmin_z_p_zs': '浮点与立即数取最小值（有谓词）',
    'fmin_z_p_zz': '浮点向量取最小值（有谓词）',
    'fminnm_z_p_zs': '浮点与立即数取最小数（有谓词）',
    'fminnm_z_p_zz': '浮点向量取最小数（有谓词）',
    'fminnmp_z_p_zz': '浮点相邻元素取最小数',
    'fminnmqv_z_p_z': '四字向量段浮点最小数递归归约',
    'fminnmv_v_p_z': '浮点最小数递归归约到标量',
    'fminp_z_p_zz': '浮点相邻元素取最小值',
    'fminqv_z_p_z': '四字向量段浮点最小值递归归约',
    'fminv_v_p_z': '浮点最小值递归归约到标量',
    'fmla_z_zzzi': '浮点融合乘加（按索引元素）',
    'fmla_z_p_zzz': '浮点融合乘加（有谓词）',
    'fmlalb_z_zzzi': '半精度按索引元素乘加到单精度（低半部分）',
    'fmlalb_z_z8z8z8i': '8位浮点按索引元素乘加到半精度（低半部分）',
    'fmlalb_z_zzz': '半精度乘加到单精度（低半部分）',
    'fmlalb_z_z8z8z8': '8位浮点乘加到半精度（低半部分）',
    'fmlallbb_z32_z8z8z8i': '8位浮点按索引元素乘加到单精度（底底）',
    'fmlallbb_z32_z8z8z8': '8位浮点乘加到单精度（底底）',
    'fmlallbt_z32_z8z8z8i': '8位浮点按索引元素乘加到单精度（底顶）',
    'fmlallbt_z32_z8z8z8': '8位浮点乘加到单精度（底顶）',
    'fmlalltb_z32_z8z8z8i': '8位浮点按索引元素乘加到单精度（顶底）',
    'fmlalltb_z32_z8z8z8': '8位浮点乘加到单精度（顶底）',
    'fmlalltt_z32_z8z8z8i': '8位浮点按索引元素乘加到单精度（顶顶）',
    'fmlalltt_z32_z8z8z8': '8位浮点乘加到单精度（顶顶）',
    'fmlalt_z_zzzi': '半精度按索引元素乘加到单精度（高半部分）',
    'fmlalt_z_z8z8z8i': '8位浮点按索引元素乘加到半精度（高半部分）',
    'fmlalt_z_zzz': '半精度乘加到单精度（高半部，FP16→FP32）',
    'fmlalt_z_z8z8z8': '8位浮点乘加到半精度（高半部，FP8→FP16）',
    'fmls_z_zzzi': '浮点融合乘减，乘以索引元素',
    'fmls_z_p_zzz': '浮点融合乘减（有谓词）',
    'fmlslb_z_zzzi': '半精度乘减单精度，乘以索引元素（低半部，FP16→FP32）',
    'fmlslb_z_zzz': '半精度乘减单精度（低半部，FP16→FP32）',
    'fmlslt_z_zzzi': '半精度乘减单精度，乘以索引元素（高半部，FP16→FP32）',
    'fmlslt_z_zzz': '半精度乘减单精度（高半部，FP16→FP32）',
    'fmmla_z_zzz': '浮点矩阵乘累加（非扩宽）',
    'fmmla_z32_zzz': '半精度矩阵乘累加到单精度（FP16→FP32）',
    'fmmla_z16_zz8z8': '8位浮点矩阵乘累加到半精度（FP8→FP16）',
    'fmmla_z32_zz8z8': '8位浮点矩阵乘累加到单精度（FP8→FP32）',
    'fmov_fcpy_z_p_i': '将浮点立即数移入向量各元素（有谓词，FCPY 的别名）',
    'fmov_fdup_z_i': '将浮点立即数移入向量各元素（无谓词，FDUP 的别名）',
    'fmov_cpy_z_p_i': '将浮点+0.0移入向量各元素（有谓词，CPY 立即数合并的别名）',
    'fmov_dup_z_i': '将浮点+0.0移入向量各元素（无谓词，DUP 立即数的别名）',
    'fmsb_z_p_zzz': '浮点融合乘减，结果写回被乘数（有谓词）',
    'fmul_z_p_zs': '浮点乘以立即数（有谓词）',
    'fmul_z_zzi': '浮点乘以索引元素',
    'fmul_z_p_zz': '浮点向量乘法（有谓词）',
    'fmul_z_zz': '浮点向量乘法（无谓词）',
    'fmulx_z_p_zz': '浮点扩展乘法（有谓词）',
    'fneg_z_p_z': '浮点取反（有谓词）',
    'fnmad_z_p_zzz': '浮点取负融合乘加，结果写回被乘数（有谓词）',
    'fnmla_z_p_zzz': '浮点取负融合乘加（有谓词）',
    'fnmls_z_p_zzz': '浮点取负融合乘减（有谓词）',
    'fnmsb_z_p_zzz': '浮点取负融合乘减，结果写回被乘数（有谓词）',
    'frecpe_z_z': '浮点倒数估算（无谓词）',
    'frecps_z_zz': '浮点倒数迭代步进（无谓词）',
    'frecpx_z_p_z': '浮点倒数指数（有谓词）',
    'frint32x_z_p_z': '浮点舍入为32位整数（有谓词）',
    'frint32z_z_p_z': '浮点向零舍入为32位整数（有谓词）',
    'frint64x_z_p_z': '浮点舍入为64位整数（有谓词）',
    'frint64z_z_p_z': '浮点向零舍入为64位整数（有谓词）',
    'frinta_z_p_z': '浮点舍入为整数值（有谓词）',
    'frsqrte_z_z': '浮点倒数平方根估算（无谓词）',
    'frsqrts_z_zz': '浮点倒数平方根迭代步进（无谓词）',
    'fscale_z_p_zz': '浮点调整指数（有谓词）',
    'fsqrt_z_p_z': '浮点平方根（有谓词）',
    'fsub_z_p_zs': '浮点减立即数（有谓词）',
    'fsub_z_p_zz': '浮点向量减法（有谓词）',
    'fsub_z_zz': '浮点向量减法（无谓词）',
    'fsubr_z_p_zs': '浮点反向减立即数（有谓词）',
    'fsubr_z_p_zz': '浮点反向减法（有谓词）',
    'ftmad_z_zzi': '浮点三角函数乘加系数',
    'ftsmul_z_zz': '浮点三角函数起始值计算',
    'ftssel_z_zz': '浮点三角函数系数选择',
    'histcnt_z_p_zz': '统计向量中匹配元素的个数',
    'histseg_z_zz': '统计向量分段中匹配元素的个数',
    'incb_r_rs': '按谓词约束元素计数的倍数递增标量寄存器',
    'incd_z_zs': '按谓词约束元素计数的倍数递增向量寄存器',
    'incp_r_p_r': '按谓词真元素个数递增标量寄存器',
    'incp_z_p_z': '按谓词真元素个数递增向量寄存器',
    'index_z_ir': '从立即数起始、以通用寄存器为步长创建索引向量',
    'index_z_ii': '从立即数起始、以立即数为步长创建索引向量',
    'index_z_ri': '从通用寄存器起始、以立即数为步长创建索引向量',
    'index_z_rr': '从通用寄存器起始、以寄存器为步长创建索引向量',
    'insr_z_r': '将通用寄存器值插入右移后的向量首位',
    'insr_z_v': '将SIMD&FP标量寄存器值插入右移后的向量首位',
    'lasta_r_p_z': '提取末个真谓词元素之后的元素到通用寄存器',
    'lasta_v_p_z': '提取末个真谓词元素之后的元素到SIMD&FP标量寄存器',
    'lastb_r_p_z': '提取最后一个真谓词元素到通用寄存器',
    'lastb_v_p_z': '提取最后一个真谓词元素到SIMD&FP标量寄存器',
    'lastp_r_p_p': '获取最后一个真谓词元素的标量索引（有谓词）',
    'ld1b_mz_p_bi': '连续加载字节到多个连续向量（立即数索引）',
    'ld1b_z_p_bi': '连续加载无符号字节到向量（立即数索引）',
    'ld1b_mz_p_br': '连续加载字节到多个连续向量（标量索引）',
    'ld1b_z_p_br': '连续加载无符号字节到向量（标量索引）',
    'ld1b_z_p_bz': '聚集加载无符号字节到向量（向量索引）',
    'ld1b_z_p_ai': '聚集加载无符号字节到向量（立即数索引）',
    'ld1d_mz_p_bi': '连续加载双字到多个连续向量（立即数索引）',
    'ld1d_z_p_bi': '连续加载无符号双字到向量（立即数索引）',
    'ld1d_mz_p_br': '连续加载双字到多个连续向量（标量索引）',
    'ld1d_z_p_br': '连续加载无符号双字到向量（标量索引）',
    'ld1d_z_p_bz': '聚集加载双字到向量（向量索引）',
    'ld1d_z_p_ai': '聚集加载双字到向量（立即数索引）',
    'ld1h_mz_p_bi': '连续加载半字到多个连续向量（立即数索引）',
    'ld1h_z_p_bi': '连续加载无符号半字到向量（立即数索引）',
    'ld1h_mz_p_br': '连续加载半字到多个连续向量（标量索引）',
    'ld1h_z_p_br': '连续加载无符号半字到向量（标量索引）',
    'ld1h_z_p_bz': '聚集加载无符号半字到向量（向量索引）',
    'ld1h_z_p_ai': '聚集加载无符号半字到向量（立即数索引）',
    'ld1q_z_p_ar': '聚集加载四字到向量',
    'ld1rb_z_p_bi': '加载并广播无符号字节到向量',
    'ld1rd_z_p_bi': '加载并广播双字到向量',
    'ld1rh_z_p_bi': '加载并广播无符号半字到向量',
    'ld1rob_z_p_bi': '连续加载并复制32字节到向量（立即数索引）',
    'ld1rob_z_p_br': '连续加载并复制32字节到向量（标量索引）',
    'ld1rod_z_p_bi': '连续加载并复制4个双字到向量（立即数索引）',
    'ld1rod_z_p_br': '连续加载并复制4个双字到向量（标量索引）',
    'ld1roh_z_p_bi': '连续加载并复制16个半字到向量（立即数索引）',
    'ld1roh_z_p_br': '连续加载并复制16个半字到向量（标量索引）',
    'ld1row_z_p_bi': '连续加载并复制8个字到向量（立即数索引）',
    'ld1row_z_p_br': '连续加载并复制8个字到向量（标量索引）',
    'ld1rqb_z_p_bi': '连续加载并复制16字节到向量（立即数索引）',
    'ld1rqb_z_p_br': '连续加载并复制16字节到向量（标量索引）',
    'ld1rqd_z_p_bi': '连续加载并复制2个双字到向量（立即数索引）',
    'ld1rqd_z_p_br': '连续加载并复制2个双字到向量（标量索引）',
    'ld1rqh_z_p_bi': '连续加载并复制8个半字到向量（立即数索引）',
    'ld1rqh_z_p_br': '连续加载并复制8个半字到向量（标量索引）',
    'ld1rqw_z_p_bi': '连续加载并复制4个字到向量（立即数索引）',
    'ld1rqw_z_p_br': '连续加载并复制4个字到向量（标量索引）',
    'ld1rsb_z_p_bi': '加载并广播有符号字节到向量',
    'ld1rsh_z_p_bi': '加载并广播有符号半字到向量',
    'ld1rsw_z_p_bi': '加载并广播有符号字到向量',
    'ld1rw_z_p_bi': '加载并广播无符号字到向量',
    'ld1sb_z_p_bi': '连续加载有符号字节到向量（立即数索引）',
    'ld1sb_z_p_br': '连续加载有符号字节到向量（标量索引）',
    'ld1sb_z_p_bz': '聚集加载有符号字节到向量（向量索引）',
    'ld1sb_z_p_ai': '聚集加载有符号字节到向量（立即数索引）',
    'ld1sh_z_p_bi': '连续加载有符号半字到向量（立即数索引）',
    'ld1sh_z_p_br': '连续加载有符号半字到向量（标量索引）',
    'ld1sh_z_p_bz': '聚集加载有符号半字到向量（向量索引）',
    'ld1sh_z_p_ai': '聚集加载有符号半字到向量（立即数索引）',
    'ld1sw_z_p_bi': '连续加载有符号字到向量（立即数索引）',
    'ld1sw_z_p_br': '连续加载有符号字到向量（标量索引）',
    'ld1sw_z_p_bz': '聚集加载有符号字到向量（向量索引）',
    'ld1sw_z_p_ai': '聚集加载有符号字到向量（立即数索引）',
    'ld1w_mz_p_bi': '连续加载字到多个连续向量（立即数索引）',
    'ld1w_z_p_bi': '连续加载无符号字到向量（立即数索引）',
    'ld1w_mz_p_br': '连续加载字到多个连续SVE向量寄存器（标量索引）',
    'ld1w_z_p_br': '连续加载无符号字到SVE向量寄存器（标量索引）',
    'ld1w_z_p_bz': '聚集加载无符号字到SVE向量寄存器（向量索引）',
    'ld1w_z_p_ai': '聚集加载无符号字到SVE向量寄存器（立即数索引）',
    'ld2b_z_p_bi': '连续加载双字节结构体到两个SVE向量寄存器（立即数索引）',
    'ld2b_z_p_br': '连续加载双字节结构体到两个SVE向量寄存器（标量索引）',
    'ld2d_z_p_bi': '连续加载双双字结构体到两个SVE向量寄存器（立即数索引）',
    'ld2d_z_p_br': '连续加载双双字结构体到两个SVE向量寄存器（标量索引）',
    'ld2h_z_p_bi': '连续加载双半字结构体到两个SVE向量寄存器（立即数索引）',
    'ld2h_z_p_br': '连续加载双半字结构体到两个SVE向量寄存器（标量索引）',
    'ld2q_z_p_bi': '连续加载双四字结构体到两个SVE向量寄存器（立即数索引）',
    'ld2q_z_p_br': '连续加载双四字结构体到两个SVE向量寄存器（标量索引）',
    'ld2w_z_p_bi': '连续加载双字结构体到两个SVE向量寄存器（立即数索引）',
    'ld2w_z_p_br': '连续加载双字结构体到两个SVE向量寄存器（标量索引）',
    'ld3b_z_p_bi': '连续加载三字节结构体到三个SVE向量寄存器（立即数索引）',
    'ld3b_z_p_br': '连续加载三字节结构体到三个SVE向量寄存器（标量索引）',
    'ld3d_z_p_bi': '连续加载三双字结构体到三个SVE向量寄存器（立即数索引）',
    'ld3d_z_p_br': '连续加载三双字结构体到三个SVE向量寄存器（标量索引）',
    'ld3h_z_p_bi': '连续加载三半字结构体到三个SVE向量寄存器（立即数索引）',
    'ld3h_z_p_br': '连续加载三半字结构体到三个SVE向量寄存器（标量索引）',
    'ld3q_z_p_bi': '连续加载三四字结构体到三个SVE向量寄存器（立即数索引）',
    'ld3q_z_p_br': '连续加载三四字结构体到三个SVE向量寄存器（标量索引）',
    'ld3w_z_p_bi': '连续加载三字结构体到三个SVE向量寄存器（立即数索引）',
    'ld3w_z_p_br': '连续加载三字结构体到三个SVE向量寄存器（标量索引）',
    'ld4b_z_p_bi': '连续加载四字节结构体到四个SVE向量寄存器（立即数索引）',
    'ld4b_z_p_br': '连续加载四字节结构体到四个SVE向量寄存器（标量索引）',
    'ld4d_z_p_bi': '连续加载四双字结构体到四个SVE向量寄存器（立即数索引）',
    'ld4d_z_p_br': '连续加载四双字结构体到四个SVE向量寄存器（标量索引）',
    'ld4h_z_p_bi': '连续加载四半字结构体到四个SVE向量寄存器（立即数索引）',
    'ld4h_z_p_br': '连续加载四半字结构体到四个SVE向量寄存器（标量索引）',
    'ld4q_z_p_bi': '连续加载四四字结构体到四个SVE向量寄存器（立即数索引）',
    'ld4q_z_p_br': '连续加载四四字结构体到四个SVE向量寄存器（标量索引）',
    'ld4w_z_p_bi': '连续加载四字结构体到四个SVE向量寄存器（立即数索引）',
    'ld4w_z_p_br': '连续加载四字结构体到四个SVE向量寄存器（标量索引）',
    'ldff1b_z_p_br': '连续首错误加载无符号字节到SVE向量寄存器（标量索引）',
    'ldff1b_z_p_bz': '聚集首错误加载无符号字节到SVE向量寄存器（向量索引）',
    'ldff1b_z_p_ai': '聚集首错误加载无符号字节到SVE向量寄存器（立即数索引）',
    'ldff1d_z_p_br': '连续首错误加载双字到SVE向量寄存器（标量索引）',
    'ldff1d_z_p_bz': '聚集首错误加载双字到SVE向量寄存器（向量索引）',
    'ldff1d_z_p_ai': '聚集首错误加载双字到SVE向量寄存器（立即数索引）',
    'ldff1h_z_p_br': '连续首错误加载无符号半字到SVE向量寄存器（标量索引）',
    'ldff1h_z_p_bz': '聚集首错误加载无符号半字到SVE向量寄存器（向量索引）',
    'ldff1h_z_p_ai': '聚集首错误加载无符号半字到SVE向量寄存器（立即数索引）',
    'ldff1sb_z_p_br': '连续首错误加载有符号字节到SVE向量寄存器（标量索引）',
    'ldff1sb_z_p_bz': '聚集首错误加载有符号字节到SVE向量寄存器（向量索引）',
    'ldff1sb_z_p_ai': '聚集首错误加载有符号字节到SVE向量寄存器（立即数索引）',
    'ldff1sh_z_p_br': '连续首错误加载有符号半字到SVE向量寄存器（标量索引）',
    'ldff1sh_z_p_bz': '聚集首错误加载有符号半字到SVE向量寄存器（向量索引）',
    'ldff1sh_z_p_ai': '聚集首错误加载有符号半字到SVE向量寄存器（立即数索引）',
    'ldff1sw_z_p_br': '连续首错误加载有符号字到SVE向量寄存器（标量索引）',
    'ldff1sw_z_p_bz': '聚集首错误加载有符号字到SVE向量寄存器（向量索引）',
    'ldff1sw_z_p_ai': '聚集首错误加载有符号字到SVE向量寄存器（立即数索引）',
    'ldff1w_z_p_br': '连续首错误加载无符号字到SVE向量寄存器（标量索引）',
    'ldff1w_z_p_bz': '聚集首错误加载无符号字到SVE向量寄存器（向量索引）',
    'ldff1w_z_p_ai': '聚集首错误加载无符号字到SVE向量寄存器（立即数索引）',
    'ldnf1b_z_p_bi': '连续非错误加载无符号字节到SVE向量寄存器（立即数索引）',
    'ldnf1d_z_p_bi': '连续非错误加载双字到SVE向量寄存器（立即数索引）',
    'ldnf1h_z_p_bi': '连续非错误加载无符号半字到SVE向量寄存器（立即数索引）',
    'ldnf1sb_z_p_bi': '连续非错误加载有符号字节到SVE向量寄存器（立即数索引）',
    'ldnf1sh_z_p_bi': '连续非错误加载有符号半字到SVE向量寄存器（立即数索引）',
    'ldnf1sw_z_p_bi': '连续非错误加载有符号字到SVE向量寄存器（立即数索引）',
    'ldnf1w_z_p_bi': '连续非错误加载无符号字到SVE向量寄存器（立即数索引）',
    'ldnt1b_mz_p_bi': '连续非临时加载字节到多个连续SVE向量寄存器（立即数索引）',
    'ldnt1b_z_p_bi': '连续非临时加载字节到SVE向量寄存器（立即数索引）',
    'ldnt1b_mz_p_br': '连续非临时加载字节到多个连续SVE向量寄存器（标量索引）',
    'ldnt1b_z_p_br': '连续非临时加载字节到SVE向量寄存器（标量索引）',
    'ldnt1b_z_p_ar': '聚集非临时加载无符号字节到SVE向量寄存器',
    'ldnt1d_mz_p_bi': '连续非临时加载双字到多个连续SVE向量寄存器（立即数索引）',
    'ldnt1d_z_p_bi': '连续非临时加载双字到SVE向量寄存器（立即数索引）',
    'ldnt1d_mz_p_br': '连续非临时加载双字到多个连续SVE向量寄存器（标量索引）',
    'ldnt1d_z_p_br': '连续非临时加载双字到SVE向量寄存器（标量索引）',
    'ldnt1d_z_p_ar': '聚集非临时加载无符号双字到SVE向量寄存器',
    'ldnt1h_mz_p_bi': '连续非临时加载半字到多个连续SVE向量寄存器（立即数索引）',
    'ldnt1h_z_p_bi': '连续非临时加载半字到SVE向量寄存器（立即数索引）',
    'ldnt1h_mz_p_br': '连续非临时加载半字到多个连续SVE向量寄存器（标量索引）',
    'ldnt1h_z_p_br': '连续非临时加载半字到SVE向量寄存器（标量索引）',
    'ldnt1h_z_p_ar': '聚集非临时加载无符号半字到SVE向量寄存器',
    'ldnt1sb_z_p_ar': '聚集非临时加载有符号字节到SVE向量寄存器',
    'ldnt1sh_z_p_ar': '聚集非临时加载有符号半字到SVE向量寄存器',
    'ldnt1sw_z_p_ar': '聚集非临时加载有符号字到SVE向量寄存器',
    'ldnt1w_mz_p_bi': '连续非临时加载字到多个连续SVE向量寄存器（立即数索引）',
    'ldnt1w_z_p_bi': '连续非临时加载字到SVE向量寄存器（立即数索引）',
    'ldnt1w_mz_p_br': '连续非临时加载字到多个连续SVE向量寄存器（标量索引）',
    'ldnt1w_z_p_br': '连续非临时加载字到SVE向量寄存器（标量索引）',
    'ldnt1w_z_p_ar': '聚集非临时加载无符号字到SVE向量寄存器',
    'ldr_p_bi': '加载SVE谓词寄存器',
    'ldr_z_bi': '加载SVE向量寄存器',
    'lsl_z_p_zi': 'SVE向量元素逻辑左移立即数（有谓词）',
    'lsl_z_zi': 'SVE向量元素逻辑左移立即数（无谓词）',
    'lsl_z_p_zz': 'SVE向量元素按向量逻辑左移（有谓词）',
    'lsl_z_p_zw': 'SVE向量元素按64位宽元素逻辑左移（有谓词）',
    'lsl_z_zw': 'SVE向量元素按64位宽元素逻辑左移（无谓词）',
    'lslr_z_p_zz': 'SVE向量元素反向逻辑左移（有谓词）',
    'lsr_z_p_zi': 'SVE向量元素逻辑右移立即数（有谓词）',
    'lsr_z_zi': 'SVE向量元素逻辑右移立即数（无谓词）',
    'lsr_z_p_zz': 'SVE向量元素按向量逻辑右移（有谓词）',
    'lsr_z_p_zw': 'SVE向量元素按64位宽元素逻辑右移（有谓词）',
    'lsr_z_zw': 'SVE向量元素按64位宽元素逻辑右移（无谓词）',
    'lsrr_z_p_zz': 'SVE向量元素反向逻辑右移（有谓词）',
    'luti2_z_zz': 'SVE查找表读取，使用2位索引（8位和16位元素）',
    'luti4_z_zz': 'SVE查找表读取，使用4位索引（8位和16位元素）',
    'mad_z_p_zzz': 'SVE向量乘加到被乘数（有谓词）',
    'madpt_z_zzz': 'SVE检查指针向量乘加到被乘数',
    'match_p_p_zz': 'SVE检测匹配元素并设置条件标志',
    'mla_z_zzzi': 'SVE向量元素乘加索引元素',
    'mla_z_p_zzz': 'SVE向量元素乘加（有谓词）',
    'mlapt_z_zzz': 'SVE检查指针向量乘加',
    'mls_z_zzzi': 'SVE向量元素乘减索引元素',
    'mls_z_p_zzz': 'SVE向量元素乘减（有谓词）',
    'mov_dupm_z_i': '将逻辑位掩码立即数移入SVE向量（无谓词，DUPM的别名）',
    'mov_orr_p_p_pp': '移动谓词（无谓词，ORR谓词版别名）',
    'mov_cpy_z_p_i': '将有符号整数立即数移入SVE向量元素（合并，CPY立即数合并版别名）',
    'mov_dup_z_i': '将有符号立即数移入SVE向量元素（无谓词，DUP立即数别名）',
    'mov_cpy_z_o_i': '将有符号整数立即数移入SVE向量元素（清零，CPY立即数清零版别名）',
    'mov_sel_p_p_pp': '移动谓词（合并，SEL谓词版别名）',
    'mov_and_p_p_pp': '移动谓词（清零，AND谓词版别名）',
    'mov_cpy_z_p_r': '将通用寄存器移入SVE向量元素（有谓词，CPY标量版别名）',
    'mov_dup_z_r': '将通用寄存器移入SVE向量元素（无谓词，DUP标量版别名）',
    'mov_cpy_z_p_v': '将SIMD&FP标量寄存器移入SVE向量元素（有谓词，CPY SIMD&FP版别名）',
    'mov_dup_z_zi': '将索引元素或SIMD&FP标量移入SVE向量（无谓词，DUP索引版别名）',
    'mov_sel_z_p_zz': '按谓词条件移动向量元素（SEL 向量的别名）',
    'mov_orr_z_zz': '无谓词移动向量寄存器（ORR 向量无谓词的别名）',
    'movprfx_z_p_z': '带谓词的移动前缀指令',
    'movprfx_z_z': '不带谓词的移动前缀指令',
    'movs_ands_p_p_pp': '归零移动谓词并设置条件标志（ANDS 的别名）',
    'movs_orrs_p_p_pp': '无谓词移动谓词并设置条件标志（ORRS 的别名）',
    'msb_z_p_zzz': '将乘积从被乘数中减去（带谓词乘减）',
    'mul_z_zi': '向量元素乘以立即数（无谓词）',
    'mul_z_zzi': '向量元素乘以索引元素',
    'mul_z_p_zz': '向量元素相乘（带谓词）',
    'mul_z_zz': '向量元素相乘（无谓词）',
    'nand_p_p_pp': '谓词按位与非（NAND）',
    'nands_p_p_pp': '谓词按位与非并设置条件标志',
    'nbsl_z_zzz': '按位反转选择（Bitwise inverted select）',
    'neg_z_p_z': '向量元素取反（带谓词）',
    'nmatch_p_p_zz': '检测无匹配元素并设置条件标志',
    'nor_p_p_pp': '谓词按位或非（NOR）',
    'nors_p_p_pp': '谓词按位或非并设置条件标志',
    'not_eor_p_p_pp': '按位取反谓词（EOR 谓词的别名）',
    'not_z_p_z': '向量元素按位取反（带谓词）',
    'nots_eors_p_p_pp': '按位取反谓词并设置条件标志（EORS 的别名）',
    'orn_orr_z_zi': '向量与立即数取反后按位或（ORR 立即数的别名）',
    'orn_p_p_pp': '谓词按位或取反（OR NOT）',
    'orns_p_p_pp': '谓词按位或取反并设置条件标志',
    'orqv_z_p_z': '按四字（128位）段对向量进行按位或归约',
    'orr_z_zi': '向量元素与立即数按位或（无谓词）',
    'orr_p_p_pp': '谓词按位或',
    'orr_z_p_zz': '向量元素按位或（带谓词）',
    'orr_z_zz': '向量元素按位或（无谓词）',
    'orrs_p_p_pp': '谓词按位或并设置条件标志',
    'orv_r_p_z': '向量元素按位或归约到标量',
    'pext_pp_rr': '从计数器形式谓词中提取谓词对',
    'pext_pn_rr': '从计数器形式谓词中提取单个谓词',
    'pfalse_p': '将谓词寄存器所有元素设为假',
    'pfirst_p_p_p': '将第一个活跃谓词元素置为真',
    'pmlal_mz_zzzw': '多向量多项式乘长并累加',
    'pmov_p_zi': '从向量中提取位并写入谓词寄存器',
    'pmov_z_pi': '将谓词寄存器位扩展写入向量',
    'pmul_z_zz': '向量元素多项式相乘（无谓词）',
    'pmull_mz_zzw': '多向量多项式乘长',
    'pmullb_z_zz': '多项式长乘（取低半部分元素）',
    'pmullt_z_zz': '多项式长乘（取高半部分元素）',
    'pnext_p_p_p': '查找下一个活跃谓词',
    'prfb_i_p_bi': '连续预取字节（立即数偏移）',
    'prfb_i_p_br': '连续预取字节（标量索引）',
    'prfb_i_p_bz': '聚集预取字节（标量加向量）',
    'prfb_i_p_ai': '聚集预取字节（向量加立即数）',
    'prfd_i_p_bi': '连续预取双字（立即数偏移）',
    'prfd_i_p_br': '连续预取双字（标量索引）',
    'prfd_i_p_bz': '聚集预取双字（标量加向量）',
    'prfd_i_p_ai': '聚集预取双字（向量加立即数）',
    'prfh_i_p_bi': '连续预取半字（立即数偏移）',
    'prfh_i_p_br': '连续预取半字（标量索引）',
    'prfh_i_p_bz': '聚集预取半字（标量加向量）',
    'prfh_i_p_ai': '聚集预取半字（向量加立即数）',
    'prfw_i_p_bi': '连续预取字（立即数偏移）',
    'prfw_i_p_br': '连续预取字（标量索引）',
    'prfw_i_p_bz': '聚集预取字（标量加向量）',
    'prfw_i_p_ai': '聚集预取字（向量加立即数）',
    'psel_p_ppi': '从谓词寄存器或全假值中按条件选择谓词',
    'ptest_p_p': '根据谓词设置条件标志',
    'ptrue_pn_i': '将计数器形式谓词初始化为全活跃',
    'ptrue_p_s': '按命名约束初始化谓词寄存器',
    'ptrues_p_s': '按命名约束初始化谓词并设置条件标志',
    'punpkhi_p_p': '将谓词高半部解包并宽展',
    'raddhnb_z_zz': '舍入加法取高位窄化（存低半元素）',
    'raddhnt_z_zz': '舍入加法取高位窄化（存高半元素）',
    'rax1_z_zz': '向左循环移位1位并与另一向量异或',
    'rbit_z_p_z': '按位反转各元素的位序（带谓词）',
    'rdffr_p_p_f': '返回成功加载元素的谓词（带谓词）',
    'rdffr_p_f': '读取首次错误寄存器（FFR）',
    'rdffrs_p_p_f': '返回成功加载元素的谓词并设置条件标志',
    'rdvl_r_i': '将向量寄存器长度的倍数读入标量寄存器',
    'rev_p_p': '反转谓词寄存器中所有元素的顺序',
    'rev_z_z': '反转向量中所有元素的顺序（无谓词）',
    'revb_z_z': '在元素内反转字节/半字/字的顺序（带谓词）',
    'revd_z_p_z': '在元素内反转64位双字顺序（带谓词）',
    'rshrnb_z_zi': '按立即数舍入右移并窄化（存低半元素）',
    'rshrnt_z_zi': '按立即数舍入右移并窄化（存高半元素）',
    'rsubhnb_z_zz': '舍入减法取高位窄化（存低半元素）',
    'rsubhnt_z_zz': '舍入减法取高位窄化（存高半元素）',
    'saba_z_zzz': '有符号绝对差并累加',
    'sabalb_z_zzz': '有符号绝对差长累加（取低半元素）',
    'sabalt_z_zzz': '有符号绝对差长累加（取高半元素）',
    'sabd_z_p_zz': '有符号绝对差（带谓词）',
    'sabdlb_z_zz': '有符号长绝对差（取低半元素）',
    'sabdlt_z_zz': '有符号长绝对差（取高半元素）',
    'sadalp_z_p_z': '有符号成对相加并长累加（带谓词）',
    'saddlb_z_zz': '有符号长加法（取低半元素）',
    'saddlbt_z_zz': '有符号长加法（低半加高半元素）',
    'saddlt_z_zz': '有符号长加法（取高半元素）',
    'saddv_r_p_z': '有符号向量元素归约求和到标量',
    'saddwb_z_zz': '有符号宽加法（取低半元素）',
    'saddwt_z_zz': '有符号宽加法（取高半元素）',
    'sbclb_z_zzz': '有符号带借位长减法（存低半元素）',
    'sbclt_z_zzz': '有符号带借位长减法（存高半元素）',
    'sclamp_z_zz': '有符号钳位到最小值/最大值范围',
    'scvtf_z_p_z': '有符号整数转浮点数（带谓词）',
    'sdiv_z_p_zz': '有符号整数除法（带谓词）',
    'sdivr_z_p_zz': '有符号整数反向除法（带谓词）',
    'sdot_z32_zzzi': '有符号整数点积（双路，索引元素）',
    'sdot_z32_zzz': '有符号整数点积（双路，向量）',
    'sdot_z_zzzi': '有符号整数点积（四路，索引元素）',
    'sdot_z_zzz': '有符号整数点积（四路，向量）',
    'sel_p_p_pp': '按条件从两个谓词中选取元素',
    'sel_z_p_zz': '按谓词从两个向量中条件选取元素',
    'setffr_f': '将首次错误寄存器（FFR）初始化为全真',
    'shadd_z_p_zz': '有符号折半加法（带谓词）',
    'shrnb_z_zi': '按立即数右移并窄化（存低半元素）',
    'shrnt_z_zi': '按立即数右移并窄化（存高半元素）',
    'shsub_z_p_zz': '有符号折半减法（带谓词）',
    'shsubr_z_p_zz': '有符号折半反向减法（带谓词）',
    'sli_z_zzi': '向量元素左移并插入（立即数位移）',
    'sm4e_z_zz': 'SM4 加密/解密轮操作',
    'sm4ekey_z_zz': 'SM4 密钥扩展轮操作',
    'smax_z_zi': '有符号最大值与立即数比较（无谓词）',
    'smax_z_p_zz': '有符号向量元素最大值（带谓词）',
    'smaxp_z_p_zz': '有符号成对最大值（带谓词）',
    'smaxqv_z_p_z': '按四字段对向量进行有符号最大归约',
    'smaxv_r_p_z': '有符号向量元素最大值归约到标量',
    'smin_z_zi': '有符号立即数最小值（无谓词）',
    'smin_z_p_zz': '有符号向量最小值（有谓词）',
    'sminp_z_p_zz': '有符号成对最小值',
    'sminqv_z_p_z': '有符号四字向量段最小值规约',
    'sminv_r_p_z': '有符号向量元素最小值规约到标量',
    'smlalb_z_zzzi': '有符号按索引元素乘加长（低半）',
    'smlalb_z_zzz': '有符号向量乘加长（低半）',
    'smlalt_z_zzzi': '有符号按索引元素乘加长（高半）',
    'smlalt_z_zzz': '有符号向量乘加长（高半）',
    'smlslb_z_zzzi': '有符号按索引元素乘减长（低半）',
    'smlslb_z_zzz': '有符号向量乘减长（低半）',
    'smlslt_z_zzzi': '有符号按索引元素乘减长（高半）',
    'smlslt_z_zzz': '有符号向量乘减长（高半）',
    'smmla_z_zzz': '有符号8位整数矩阵乘累加到32位整数',
    'smulh_z_p_zz': '有符号乘法取高半结果（有谓词）',
    'smulh_z_zz': '有符号乘法取高半结果（无谓词）',
    'smullb_z_zzi': '有符号按索引元素乘长（低半）',
    'smullb_z_zz': '有符号向量乘长（低半）',
    'smullt_z_zzi': '有符号按索引元素乘长（高半）',
    'smullt_z_zz': '有符号向量乘长（高半）',
    'splice_z_p_zz': '在谓词控制下拼接两个向量',
    'sqabs_z_p_z': '有符号饱和绝对值',
    'sqadd_z_zi': '有符号饱和加立即数（无谓词）',
    'sqadd_z_p_zz': '有符号饱和向量加法（有谓词）',
    'sqadd_z_zz': '有符号饱和向量加法（无谓词）',
    'sqcadd_z_zz': '饱和复数整数加法',
    'sqcvtn_z_mz2': '有符号32位整数饱和窄化提取为交错16位整数',
    'sqcvtun_z_mz2': '有符号32位整数饱和窄化提取为交错无符号16位整数',
    'sqdecb_r_rs': '有符号饱和标量减去8位谓词约束元素数倍数',
    'sqdecd_r_rs': '有符号饱和标量减去64位谓词约束元素数倍数',
    'sqdecd_z_zs': '有符号饱和向量减去64位谓词约束元素数倍数',
    'sqdech_r_rs': '有符号饱和标量减去16位谓词约束元素数倍数',
    'sqdech_z_zs': '有符号饱和向量减去16位谓词约束元素数倍数',
    'sqdecp_r_p_r': '有符号饱和标量减去真谓词元素数',
    'sqdecp_z_p_z': '有符号饱和向量减去真谓词元素数',
    'sqdecw_r_rs': '有符号饱和标量减去32位谓词约束元素数倍数',
    'sqdecw_z_zs': '有符号饱和向量减去32位谓词约束元素数倍数',
    'sqdmlalb_z_zzzi': '有符号饱和倍增乘加按索引元素（低半）',
    'sqdmlalb_z_zzz': '有符号饱和倍增乘加向量（低半）',
    'sqdmlalbt_z_zzz': '有符号饱和倍增乘加向量（低半×高半）',
    'sqdmlalt_z_zzzi': '有符号饱和倍增乘加按索引元素（高半）',
    'sqdmlalt_z_zzz': '有符号饱和倍增乘加向量（高半）',
    'sqdmlslb_z_zzzi': '有符号饱和倍增乘减按索引元素（低半）',
    'sqdmlslb_z_zzz': '有符号饱和倍增乘减向量（低半）',
    'sqdmlslbt_z_zzz': '有符号饱和倍增乘减向量（低半×高半）',
    'sqdmlslt_z_zzzi': '有符号饱和倍增乘减按索引元素（高半）',
    'sqdmlslt_z_zzz': '有符号饱和倍增乘减向量（高半）',
    'sqdmulh_z_zzi': '有符号饱和倍增乘高按索引元素',
    'sqdmulh_z_zz': '有符号饱和倍增乘高（无谓词）',
    'sqdmullb_z_zzi': '有符号饱和倍增乘长按索引元素（低半）',
    'sqdmullb_z_zz': '有符号饱和倍增乘长（低半）',
    'sqdmullt_z_zzi': '有符号饱和倍增乘长按索引元素（高半）',
    'sqdmullt_z_zz': '有符号饱和倍增乘长（高半）',
    'sqincb_r_rs': '有符号饱和标量加上8位谓词约束元素数倍数',
    'sqincd_r_rs': '有符号饱和标量加上64位谓词约束元素数倍数',
    'sqincd_z_zs': '有符号饱和向量加上64位谓词约束元素数倍数',
    'sqinch_r_rs': '有符号饱和标量加上16位谓词约束元素数倍数',
    'sqinch_z_zs': '有符号饱和向量加上16位谓词约束元素数倍数',
    'sqincp_r_p_r': '有符号饱和标量加上真谓词元素数',
    'sqincp_z_p_z': '有符号饱和向量加上真谓词元素数',
    'sqincw_r_rs': '有符号饱和标量加上32位谓词约束元素数倍数',
    'sqincw_z_zs': '有符号饱和向量加上32位谓词约束元素数倍数',
    'sqneg_z_p_z': '有符号饱和取反',
    'sqrdcmlah_z_zzzi': '饱和舍入倍增复数整数乘加高按索引元素',
    'sqrdcmlah_z_zzz': '饱和舍入倍增复数整数乘加高',
    'sqrdmlah_z_zzzi': '有符号饱和舍入倍增乘加高按索引元素',
    'sqrdmlah_z_zzz': '有符号饱和舍入倍增乘加高（无谓词）',
    'sqrdmlsh_z_zzzi': '有符号饱和舍入倍增乘减高按索引元素',
    'sqrdmlsh_z_zzz': '有符号饱和舍入倍增乘减高（无谓词）',
    'sqrdmulh_z_zzi': '有符号饱和舍入倍增乘高按索引元素',
    'sqrdmulh_z_zz': '有符号饱和舍入倍增乘高（无谓词）',
    'sqrshl_z_p_zz': '有符号饱和舍入左移（有谓词）',
    'sqrshlr_z_p_zz': '有符号饱和舍入左移（反转，有谓词）',
    'sqrshrn_z_mz2': '有符号饱和舍入右移窄化为交错整数（立即数）',
    'sqrshrnb_z_zi': '有符号饱和舍入右移窄化立即数（低半）',
    'sqrshrnt_z_zi': '有符号饱和舍入右移窄化立即数（高半）',
    'sqrshrun_z_mz2': '有符号饱和舍入右移无符号窄化并交错（立即数）',
    'sqrshrunb_z_zi': '有符号饱和舍入右移窄化为无符号整数（低半）',
    'sqrshrunt_z_zi': '有符号饱和舍入右移窄化为无符号整数（高半）',
    'sqshl_z_p_zi': '有符号饱和左移立即数',
    'sqshl_z_p_zz': '有符号饱和向量左移（有谓词）',
    'sqshlr_z_p_zz': '有符号饱和左移（反转，有谓词）',
    'sqshlu_z_p_zi': '有符号饱和左移为无符号（立即数）',
    'sqshrnb_z_zi': '有符号饱和右移窄化立即数（低半）',
    'sqshrnt_z_zi': '有符号饱和右移窄化立即数（高半）',
    'sqshrunb_z_zi': '有符号饱和右移窄化为无符号整数（低半）',
    'sqshrunt_z_zi': '有符号饱和右移窄化为无符号整数（高半）',
    'sqsub_z_zi': '有符号饱和减立即数（无谓词）',
    'sqsub_z_p_zz': '有符号饱和向量减法（有谓词）',
    'sqsub_z_zz': '有符号饱和向量减法（无谓词）',
    'sqsubr_z_p_zz': '有符号饱和减法（反转，有谓词）',
    'sqxtnb_z_zz': '有符号饱和窄化提取（低半）',
    'sqxtnt_z_zz': '有符号饱和窄化提取（高半）',
    'sqxtunb_z_zz': '有符号饱和窄化提取为无符号整数（低半）',
    'sqxtunt_z_zz': '有符号饱和窄化提取为无符号整数（高半）',
    'srhadd_z_p_zz': '有符号舍入折半加法',
    'sri_z_zzi': '右移并插入（立即数）',
    'srshl_z_p_zz': '有符号舍入左移（有谓词）',
    'srshlr_z_p_zz': '有符号舍入左移（反转，有谓词）',
    'srshr_z_p_zi': '有符号舍入右移立即数',
    'srsra_z_zi': '有符号舍入右移并累加（立即数）',
    'sshllb_z_zi': '有符号长左移立即数（低半）',
    'sshllt_z_zi': '有符号长左移立即数（高半）',
    'ssra_z_zi': '有符号右移并累加（立即数）',
    'ssublb_z_zz': '有符号长减法（低半）',
    'ssublbt_z_zz': '有符号长减法（低半减高半）',
    'ssublt_z_zz': '有符号长减法（高半）',
    'ssubltb_z_zz': '有符号长减法（高半减低半）',
    'ssubwb_z_zz': '有符号宽减法（低半）',
    'ssubwt_z_zz': '有符号宽减法（高半）',
    'st1b_mz_p_bi': '连续存储多寄存器字节到内存（立即数索引）',
    'st1b_z_p_bi': '连续存储向量字节到内存（立即数索引）',
    'st1b_mz_p_br': '连续存储多寄存器字节到内存（标量索引）',
    'st1b_z_p_br': '连续存储向量字节到内存（标量索引）',
    'st1b_z_p_bz': '散布存储向量字节到内存（向量索引）',
    'st1b_z_p_ai': '散布存储向量字节到内存（立即数索引）',
    'st1d_mz_p_bi': '连续存储多寄存器双字到内存（立即数索引）',
    'st1d_z_p_bi': '连续存储向量双字到内存（立即数索引）',
    'st1d_mz_p_br': '连续存储多寄存器双字到内存（标量索引）',
    'st1d_z_p_br': '连续存储向量双字到内存（标量索引）',
    'st1d_z_p_bz': 'SVE 向量散射存储双字（向量索引）',
    'st1d_z_p_ai': 'SVE 向量散射存储双字（立即数索引）',
    'st1h_mz_p_bi': 'SVE 多连续向量连续存储半字（立即数索引）',
    'st1h_z_p_bi': 'SVE 向量连续存储半字（立即数索引）',
    'st1h_mz_p_br': 'SVE 多连续向量连续存储半字（标量索引）',
    'st1h_z_p_br': 'SVE 向量连续存储半字（标量索引）',
    'st1h_z_p_bz': 'SVE 向量散射存储半字（向量索引）',
    'st1h_z_p_ai': 'SVE 向量散射存储半字（立即数索引）',
    'st1q_z_p_ar': 'SVE 向量散射存储四字',
    'st1w_mz_p_bi': 'SVE 多连续向量连续存储字（立即数索引）',
    'st1w_z_p_bi': 'SVE 向量连续存储字（立即数索引）',
    'st1w_mz_p_br': 'SVE 多连续向量连续存储字（标量索引）',
    'st1w_z_p_br': 'SVE 向量连续存储字（标量索引）',
    'st1w_z_p_bz': 'SVE 向量散射存储字（向量索引）',
    'st1w_z_p_ai': 'SVE 向量散射存储字（立即数索引）',
    'st2b_z_p_bi': 'SVE 两向量连续存储两字节结构（立即数索引）',
    'st2b_z_p_br': 'SVE 两向量连续存储两字节结构（标量索引）',
    'st2d_z_p_bi': 'SVE 两向量连续存储两双字结构（立即数索引）',
    'st2d_z_p_br': 'SVE 两向量连续存储两双字结构（标量索引）',
    'st2h_z_p_bi': 'SVE 两向量连续存储两半字结构（立即数索引）',
    'st2h_z_p_br': 'SVE 两向量连续存储两半字结构（标量索引）',
    'st2q_z_p_bi': 'SVE 两向量连续存储两四字结构（立即数索引）',
    'st2q_z_p_br': 'SVE 两向量连续存储两四字结构（标量索引）',
    'st2w_z_p_bi': 'SVE 两向量连续存储两字结构（立即数索引）',
    'st2w_z_p_br': 'SVE 两向量连续存储两字结构（标量索引）',
    'st3b_z_p_bi': 'SVE 三向量连续存储三字节结构（立即数索引）',
    'st3b_z_p_br': 'SVE 三向量连续存储三字节结构（标量索引）',
    'st3d_z_p_bi': 'SVE 三向量连续存储三双字结构（立即数索引）',
    'st3d_z_p_br': 'SVE 三向量连续存储三双字结构（标量索引）',
    'st3h_z_p_bi': 'SVE 三向量连续存储三半字结构（立即数索引）',
    'st3h_z_p_br': 'SVE 三向量连续存储三半字结构（标量索引）',
    'st3q_z_p_bi': 'SVE 三向量连续存储三四字结构（立即数索引）',
    'st3q_z_p_br': 'SVE 三向量连续存储三四字结构（标量索引）',
    'st3w_z_p_bi': 'SVE 三向量连续存储三字结构（立即数索引）',
    'st3w_z_p_br': 'SVE 三向量连续存储三字结构（标量索引）',
    'st4b_z_p_bi': 'SVE 四向量连续存储四字节结构（立即数索引）',
    'st4b_z_p_br': 'SVE 四向量连续存储四字节结构（标量索引）',
    'st4d_z_p_bi': 'SVE 四向量连续存储四双字结构（立即数索引）',
    'st4d_z_p_br': 'SVE 四向量连续存储四双字结构（标量索引）',
    'st4h_z_p_bi': 'SVE 四向量连续存储四半字结构（立即数索引）',
    'st4h_z_p_br': 'SVE 四向量连续存储四半字结构（标量索引）',
    'st4q_z_p_bi': 'SVE 四向量连续存储四四字结构（立即数索引）',
    'st4q_z_p_br': 'SVE 四向量连续存储四四字结构（标量索引）',
    'st4w_z_p_bi': 'SVE 四向量连续存储四字结构（立即数索引）',
    'st4w_z_p_br': 'SVE 四向量连续存储四字结构（标量索引）',
    'stnt1b_mz_p_bi': 'SVE 多连续向量连续非时态存储字节（立即数索引）',
    'stnt1b_z_p_bi': 'SVE 向量连续非时态存储字节（立即数索引）',
    'stnt1b_mz_p_br': 'SVE 多连续向量连续非时态存储字节（标量索引）',
    'stnt1b_z_p_br': 'SVE 向量连续非时态存储字节（标量索引）',
    'stnt1b_z_p_ar': 'SVE 向量散射非时态存储字节',
    'stnt1d_mz_p_bi': 'SVE 多连续向量连续非时态存储双字（立即数索引）',
    'stnt1d_z_p_bi': 'SVE 向量连续非时态存储双字（立即数索引）',
    'stnt1d_mz_p_br': 'SVE 多连续向量连续非时态存储双字（标量索引）',
    'stnt1d_z_p_br': 'SVE 向量连续非时态存储双字（标量索引）',
    'stnt1d_z_p_ar': 'SVE 向量散射非时态存储双字',
    'stnt1h_mz_p_bi': 'SVE 多连续向量连续非时态存储半字（立即数索引）',
    'stnt1h_z_p_bi': 'SVE 向量连续非时态存储半字（立即数索引）',
    'stnt1h_mz_p_br': 'SVE 多连续向量连续非时态存储半字（标量索引）',
    'stnt1h_z_p_br': 'SVE 向量连续非时态存储半字（标量索引）',
    'stnt1h_z_p_ar': 'SVE 向量散射非时态存储半字',
    'stnt1w_mz_p_bi': 'SVE 多连续向量连续非时态存储字（立即数索引）',
    'stnt1w_z_p_bi': 'SVE 向量连续非时态存储字（立即数索引）',
    'stnt1w_mz_p_br': 'SVE 多连续向量连续非时态存储字（标量索引）',
    'stnt1w_z_p_br': 'SVE 向量连续非时态存储字（标量索引）',
    'stnt1w_z_p_ar': 'SVE 向量散射非时态存储字',
    'str_p_bi': 'SVE 存储谓词寄存器',
    'str_z_bi': 'SVE 存储向量寄存器',
    'sub_z_zi': 'SVE 向量减立即数（无谓词）',
    'sub_z_p_zz': 'SVE 向量减法（有谓词）',
    'sub_z_zz': 'SVE 向量减法（无谓词）',
    'subhnb_z_zz': 'SVE 减法窄化取高位结果（写下半部分）',
    'subhnt_z_zz': 'SVE 减法窄化取高位结果（写上半部分）',
    'subpt_z_p_zz': 'SVE 校验指针向量相减（有谓词）',
    'subpt_z_zz': 'SVE 校验指针向量相减（无谓词）',
    'subr_z_zi': 'SVE 反向减立即数（无谓词）',
    'subr_z_p_zz': 'SVE 反向向量减法（有谓词）',
    'sudot_z_zzzi': 'SVE 有符号×无符号 8 位整数点积（索引元素）到 32 位整数',
    'sunpkhi_z_z': 'SVE 有符号解包并符号扩展向量高/低半部分',
    'suqadd_z_p_zz': 'SVE 有符号饱和加无符号整数',
    'sxtb_z_p_z': 'SVE 有符号字节/半字/字符号扩展（有谓词）',
    'tbl_z_zz': 'SVE 可编程表查找（一或两张向量表，补零）',
    'tblq_z_zz': 'SVE 每个四字段内可编程表查找（补零）',
    'tbx_z_zz': 'SVE 可编程表查找（单张向量表，保留原值）',
    'tbxq_z_zz': 'SVE 每个四字段内可编程表查找（保留原值）',
    'trn1_p_pp': 'SVE 交织两谓词的偶数或奇数元素',
    'trn1_z_zz': 'SVE 交织两向量的偶数或奇数元素',
    'uaba_z_zzz': 'SVE 无符号绝对差并累加',
    'uabalb_z_zzz': 'SVE 无符号绝对差并累加长（取下半元素）',
    'uabalt_z_zzz': 'SVE 无符号绝对差并累加长（取上半元素）',
    'uabd_z_p_zz': 'SVE 无符号绝对差（有谓词）',
    'uabdlb_z_zz': 'SVE 无符号绝对差长（取下半元素）',
    'uabdlt_z_zz': 'SVE 无符号绝对差长（取上半元素）',
    'uadalp_z_p_z': 'SVE 无符号相邻对加长并累加',
    'uaddlb_z_zz': 'SVE 无符号加长（取下半元素）',
    'uaddlt_z_zz': 'SVE 无符号加长（取上半元素）',
    'uaddv_r_p_z': 'SVE 无符号加法归约到标量',
    'uaddwb_z_zz': 'SVE 无符号宽加（取下半元素）',
    'uaddwt_z_zz': 'SVE 无符号宽加（取上半元素）',
    'uclamp_z_zz': 'SVE 无符号最小/最大值钳位',
    'ucvtf_z_p_z': 'SVE 无符号整数转浮点数（有谓词）',
    'udiv_z_p_zz': 'SVE 无符号除法（有谓词）',
    'udivr_z_p_zz': 'SVE 无符号反向除法（有谓词）',
    'udot_z32_zzzi': 'SVE 无符号整数点积（双路，索引元素）到 32 位',
    'udot_z32_zzz': 'SVE 无符号整数点积（双路，向量）',
    'udot_z_zzzi': 'SVE 无符号整数点积（四路，索引元素）',
    'udot_z_zzz': 'SVE 无符号整数点积（四路，向量）',
    'uhadd_z_p_zz': 'SVE 无符号折半加法',
    'uhsub_z_p_zz': 'SVE 无符号折半减法',
    'uhsubr_z_p_zz': 'SVE 无符号折半反向减法',
    'umax_z_zi': 'SVE 无符号与立即数取最大值（无谓词）',
    'umax_z_p_zz': 'SVE 无符号向量取最大值（有谓词）',
    'umaxp_z_p_zz': 'SVE 无符号相邻对取最大值',
    'umaxqv_z_p_z': 'SVE 无符号最大值归约（四字段）',
    'umaxv_r_p_z': 'SVE 无符号最大值归约到标量',
    'umin_z_zi': 'SVE 无符号与立即数取最小值（无谓词）',
    'umin_z_p_zz': 'SVE 无符号向量取最小值（有谓词）',
    'uminp_z_p_zz': 'SVE 无符号相邻对取最小值',
    'uminqv_z_p_z': 'SVE 无符号最小值归约（四字段）',
    'uminv_r_p_z': 'SVE 无符号最小值归约到标量',
    'umlalb_z_zzzi': 'SVE 无符号乘加长（索引元素，取下半元素）',
    'umlalb_z_zzz': '无符号长乘加（取低半部分元素）',
    'umlalt_z_zzzi': '无符号长乘加索引元素（取高半部分元素）',
    'umlalt_z_zzz': '无符号长乘加（取高半部分元素）',
    'umlslb_z_zzzi': '无符号长乘减索引元素（取低半部分元素）',
    'umlslb_z_zzz': '无符号长乘减（取低半部分元素）',
    'umlslt_z_zzzi': '无符号长乘减索引元素（取高半部分元素）',
    'umlslt_z_zzz': '无符号长乘减（取高半部分元素）',
    'ummla_z_zzz': '无符号8位整数矩阵乘累加至32位整数',
    'umulh_z_p_zz': '无符号乘法取高半结果（有谓词）',
    'umulh_z_zz': '无符号乘法取高半结果（无谓词）',
    'umullb_z_zzi': '无符号长乘索引元素（取低半部分元素）',
    'umullb_z_zz': '无符号长乘（取低半部分元素）',
    'umullt_z_zzi': '无符号长乘索引元素（取高半部分元素）',
    'umullt_z_zz': '无符号长乘（取高半部分元素）',
    'uqadd_z_zi': '无符号饱和加立即数（无谓词）',
    'uqadd_z_p_zz': '无符号饱和加法（有谓词）',
    'uqadd_z_zz': '无符号饱和加法（无谓词）',
    'uqcvtn_z_mz2': '无符号32位整数饱和窄化提取至交织16位整数',
    'uqdecb_r_rs': '标量无符号饱和递减，减量为8位谓词约束元素个数的倍数',
    'uqdecd_r_rs': '标量无符号饱和递减，减量为64位谓词约束元素个数的倍数',
    'uqdecd_z_zs': '向量无符号饱和递减，减量为64位谓词约束元素个数的倍数',
    'uqdech_r_rs': '标量无符号饱和递减，减量为16位谓词约束元素个数的倍数',
    'uqdech_z_zs': '向量无符号饱和递减，减量为16位谓词约束元素个数的倍数',
    'uqdecp_r_p_r': '标量无符号饱和递减，减量为谓词真元素个数',
    'uqdecp_z_p_z': '向量无符号饱和递减，减量为谓词真元素个数',
    'uqdecw_r_rs': '标量无符号饱和递减，减量为32位谓词约束元素个数的倍数',
    'uqdecw_z_zs': '向量无符号饱和递减，减量为32位谓词约束元素个数的倍数',
    'uqincb_r_rs': '标量无符号饱和递增，增量为8位谓词约束元素个数的倍数',
    'uqincd_r_rs': '标量无符号饱和递增，增量为64位谓词约束元素个数的倍数',
    'uqincd_z_zs': '向量无符号饱和递增，增量为64位谓词约束元素个数的倍数',
    'uqinch_r_rs': '标量无符号饱和递增，增量为16位谓词约束元素个数的倍数',
    'uqinch_z_zs': '向量无符号饱和递增，增量为16位谓词约束元素个数的倍数',
    'uqincp_r_p_r': '标量无符号饱和递增，增量为谓词真元素个数',
    'uqincp_z_p_z': '向量无符号饱和递增，增量为谓词真元素个数',
    'uqincw_r_rs': '标量无符号饱和递增，增量为32位谓词约束元素个数的倍数',
    'uqincw_z_zs': '向量无符号饱和递增，增量为32位谓词约束元素个数的倍数',
    'uqrshl_z_p_zz': '无符号饱和舍入左移（有谓词）',
    'uqrshlr_z_p_zz': '无符号饱和舍入左移（反向，有谓词）',
    'uqrshrn_z_mz2': '无符号饱和舍入右移窄化立即数至交织整数',
    'uqrshrnb_z_zi': '无符号饱和舍入右移窄化立即数（取低半部分）',
    'uqrshrnt_z_zi': '无符号饱和舍入右移窄化立即数（取高半部分）',
    'uqshl_z_p_zi': '无符号饱和左移立即数',
    'uqshl_z_p_zz': '无符号饱和左移（有谓词）',
    'uqshlr_z_p_zz': '无符号饱和左移（反向，有谓词）',
    'uqshrnb_z_zi': '无符号饱和右移窄化立即数（取低半部分）',
    'uqshrnt_z_zi': '无符号饱和右移窄化立即数（取高半部分）',
    'uqsub_z_zi': '无符号饱和减立即数（无谓词）',
    'uqsub_z_p_zz': '无符号饱和减法（有谓词）',
    'uqsub_z_zz': '无符号饱和减法（无谓词）',
    'uqsubr_z_p_zz': '无符号饱和减法（反向，有谓词）',
    'uqxtnb_z_zz': '无符号饱和提取窄化（取低半部分）',
    'uqxtnt_z_zz': '无符号饱和提取窄化（取高半部分）',
    'urecpe_z_p_z': '无符号倒数估算（有谓词）',
    'urhadd_z_p_zz': '无符号舍入折半加法',
    'urshl_z_p_zz': '无符号舍入左移（有谓词）',
    'urshlr_z_p_zz': '无符号舍入左移（反向，有谓词）',
    'urshr_z_p_zi': '无符号舍入右移立即数',
    'ursqrte_z_p_z': '无符号倒数平方根估算（有谓词）',
    'ursra_z_zi': '无符号舍入右移并累加立即数',
    'usdot_z_zzzi': '无符号×有符号8位整数点积索引元素至32位整数',
    'usdot_z_zzz': '无符号×有符号8位整数向量点积至32位整数',
    'ushllb_z_zi': '无符号长左移立即数（取低半部分元素）',
    'ushllt_z_zi': '无符号长左移立即数（取高半部分元素）',
    'usmmla_z_zzz': '无符号×有符号8位整数矩阵乘累加至32位整数',
    'usqadd_z_p_zz': '无符号饱和有符号加法',
    'usra_z_zi': '无符号右移并累加立即数',
    'usublb_z_zz': '无符号长减法（取低半部分元素）',
    'usublt_z_zz': '无符号长减法（取高半部分元素）',
    'usubwb_z_zz': '无符号宽减法（取低半部分元素）',
    'usubwt_z_zz': '无符号宽减法（取高半部分元素）',
    'uunpkhi_z_z': '无符号解包并扩展向量高半部分元素',
    'uxtb_z_p_z': '无符号字节/半字/字扩展（有谓词）',
    'uzp1_p_pp': '从两个谓词中拼接偶数或奇数位元素',
    'uzp1_z_zz': '从两个向量中拼接偶数或奇数位元素',
    'uzpq1_z_zz': '拼接每对128位向量段中的偶数元素',
    'uzpq2_z_zz': '拼接每对128位向量段中的奇数元素',
    'whilege_pn_rr': '递减有符号标量大于等于标量时循环（谓词计数器形式）',
    'whilege_pp_rr': '递减有符号标量大于等于标量时循环（谓词对形式）',
    'whilege_p_p_rr': '递减有符号标量大于等于标量时循环',
    'whilegt_pn_rr': '递减有符号标量大于标量时循环（谓词计数器形式）',
    'whilegt_pp_rr': '递减有符号标量大于标量时循环（谓词对形式）',
    'whilegt_p_p_rr': '递减有符号标量大于标量时循环',
    'whilehi_pn_rr': '递减无符号标量高于标量时循环（谓词计数器形式）',
    'whilehi_pp_rr': '递减无符号标量高于标量时循环（谓词对形式）',
    'whilehi_p_p_rr': '递减无符号标量高于标量时循环',
    'whilehs_pn_rr': '递减无符号标量高于或等于标量时循环（谓词计数器形式）',
    'whilehs_pp_rr': '递减无符号标量高于或等于标量时循环（谓词对形式）',
    'whilehs_p_p_rr': '递减无符号标量高于或等于标量时循环',
    'whilele_pn_rr': '递增有符号标量小于等于标量时循环（谓词计数器形式）',
    'whilele_pp_rr': '递增有符号标量小于等于标量时循环（谓词对形式）',
    'whilele_p_p_rr': '递增有符号标量小于等于标量时循环',
    'whilelo_pn_rr': '递增无符号标量低于标量时循环（谓词计数器形式）',
    'whilelo_pp_rr': '递增无符号标量低于标量时循环（谓词对形式）',
    'whilelo_p_p_rr': '递增无符号标量低于标量时循环',
    'whilels_pn_rr': '递增无符号标量低于或等于标量时循环（谓词计数器形式）',
    'whilels_pp_rr': '递增无符号标量低于或等于标量时循环（谓词对形式）',
    'whilels_p_p_rr': '递增无符号标量低于或等于标量时循环',
    'whilelt_pn_rr': '递增有符号标量小于标量时循环（谓词计数器形式）',
    'whilelt_pp_rr': '递增有符号标量小于标量时循环（谓词对形式）',
    'whilelt_p_p_rr': '递增有符号标量小于标量时循环',
    'whilerw_p_rr': '无读后写冲突时循环',
    'whilewr_p_rr': '无写后读/写冲突时循环',
    'wrffr_f_p': '写首错误寄存器（FFR）',
    'xar_z_zzi': '按立即数对向量执行异或并循环右移',
    'zip1_p_pp': '从两个半谓词交织合并元素',
    'zip1_z_zz': '从两个半向量交织合并元素',
    'zipq1_z_zz': '从每对128位向量段低半部分交织合并元素',
    'zipq2_z_zz': '从每对128位向量段高半部分交织合并元素',
    'add_za_zw': '多向量累加至ZA阵列向量',
    'add_za_zzv': '多向量加单向量并累加至ZA阵列向量',
    'add_za_zzw': '多向量相加并累加至ZA阵列向量',
    'add_mz_zzv': '多向量加单向量至多向量',
    'addha_za_pp_z': '将向量元素水平累加至ZA分块',
    'addspl_r_ri': '将流式SVE谓词寄存器大小的倍数加至标量寄存器',
    'addsvl_r_ri': '将流式SVE向量寄存器大小的倍数加至标量寄存器',
    'addva_za_pp_z': '将向量元素垂直累加至ZA分块',
    'bf1cvt_mz2_z8': '多向量8位浮点数转换为BFloat16',
    'bf1cvtl_mz2_z8': '多向量8位浮点数转换为去交织BFloat16',
    'bfadd_za_zw': '多向量BFloat16累加至ZA阵列向量',
    'bfclamp_mz_zz': '多向量BFloat16按最小/最大值截断',
    'bfcvt_z8_mz2': '多向量 BFloat16 转换为 8 位浮点数',
    'bfcvt_z_mz2': '多向量单精度转换为 BFloat16',
    'bfcvtn_z_mz2': '多向量单精度转换为交错 BFloat16',
    'bfdot_za_zzi': '多向量 BFloat16 按索引元素点积累加至单精度',
    'bfdot_za_zzv': '多向量 BFloat16 按向量点积累加至单精度',
    'bfdot_za_zzw': '多向量 BFloat16 点积累加至单精度',
    'bfmax_mz_zzv': '多向量 BFloat16 按向量取最大值',
    'bfmax_mz_zzw': '多向量 BFloat16 取最大值',
    'bfmaxnm_mz_zzv': '多向量 BFloat16 按向量取最大数值',
    'bfmaxnm_mz_zzw': '多向量 BFloat16 取最大数值',
    'bfmin_mz_zzv': '多向量 BFloat16 按向量取最小值',
    'bfmin_mz_zzw': '多向量 BFloat16 取最小值',
    'bfminnm_mz_zzv': '多向量 BFloat16 按向量取最小数值',
    'bfminnm_mz_zzw': '多向量 BFloat16 取最小数值',
    'bfmla_za_zzi': '多向量 BFloat16 按索引元素融合乘加',
    'bfmla_za_zzv': '多向量 BFloat16 按向量融合乘加',
    'bfmla_za_zzw': '多向量 BFloat16 融合乘加',
    'bfmlal_za_zzi': '多向量 BFloat16 按索引元素乘加至单精度',
    'bfmlal_za_zzv': '多向量 BFloat16 按向量乘加至单精度',
    'bfmlal_za_zzw': '多向量 BFloat16 乘加至单精度',
    'bfmls_za_zzi': '多向量 BFloat16 按索引元素融合乘减',
    'bfmls_za_zzv': '多向量 BFloat16 按向量融合乘减',
    'bfmls_za_zzw': '多向量 BFloat16 融合乘减',
    'bfmlsl_za_zzi': '多向量 BFloat16 按索引元素乘减自单精度',
    'bfmlsl_za_zzv': '多向量 BFloat16 按向量乘减自单精度',
    'bfmlsl_za_zzw': '多向量 BFloat16 乘减自单精度',
    'bfmop4a_za_zz': 'BFloat16 四分之一块外积，累加（非扩展精度）',
    'bfmop4a_za32_zz': 'BFloat16 四分之一块外积之和累加至单精度（扩展精度）',
    'bfmop4s_za_zz': 'BFloat16 四分之一块外积，减法（非扩展精度）',
    'bfmop4s_za32_zz': 'BFloat16 四分之一块外积之和减法至单精度（扩展精度）',
    'bfmopa_za_pp_zz': 'BFloat16 外积，累加（非扩展精度）',
    'bfmopa_za32_pp_zz': 'BFloat16 外积之和累加至单精度（扩展精度）',
    'bfmops_za_pp_zz': 'BFloat16 外积，减法（非扩展精度）',
    'bfmops_za32_pp_zz': 'BFloat16 外积之和减法至单精度（扩展精度）',
    'bfmul_mz_zzv': '多向量 BFloat16 按向量乘法',
    'bfmul_mz_zzw': '多向量 BFloat16 乘法',
    'bfscale_mz_zzv': '多向量 BFloat16 按向量调整指数',
    'bfscale_mz_zzw': '多向量 BFloat16 调整指数',
    'bfsub_za_zw': '多向量 BFloat16 从 ZA 数组向量中减法',
    'bftmopa_za_zzzi': 'BFloat16 稀疏外积，累加（非扩展精度）',
    'bftmopa_za32_zzzi': 'BFloat16 稀疏外积之和累加至单精度（扩展精度）',
    'bfvdot_za_zzi': '多向量 BFloat16 按索引元素垂直点积至单精度',
    'bmopa_za_pp_zz': '按位异或非统计外积，累加',
    'bmops_za_pp_zz': '按位异或非统计外积，减法',
    'f1cvt_mz2_z8': '多向量 8 位浮点数转换为半精度',
    'f1cvtl_mz2_z8': '多向量 8 位浮点数转换为去交错半精度',
    'fadd_za_zw': '多向量浮点数累加至 ZA 数组向量',
    'famax_mz_zzw': '多向量浮点数绝对值最大值',
    'famin_mz_zzw': '多向量浮点数绝对值最小值',
    'fclamp_mz_zz': '多向量浮点数限幅至最小值/最大值',
    'fcvt_z8_mz2': '多向量半精度转换为 8 位浮点数',
    'fcvt_z_mz2': '多向量单精度转换为半精度',
    'fcvt_z8_mz4': '多向量单精度转换为 8 位浮点数',
    'fcvt_mz2_z': '多向量半精度转换为单精度',
    'fcvtl_mz2_z': '多向量半精度转换为去交错单精度',
    'fcvtn_z_mz2': '多向量单精度转换为交错半精度',
    'fcvtn_z8_mz4': '多向量单精度转换为交错 8 位浮点数',
    'fcvtzs_mz_z': '多向量单精度转换为有符号 32 位整数，向零舍入',
    'fcvtzu_mz_z': '多向量单精度转换为无符号 32 位整数，向零舍入',
    'fdot_za_zzi': '多向量半精度按索引元素点积至单精度（2 路）',
    'fdot_za_z8z8i': '多向量 8 位浮点数按索引元素点积至半精度（2 路）',
    'fdot_za_zzv': '多向量半精度按向量点积至单精度（2 路）',
    'fdot_za_z8z8v': '多向量 8 位浮点数按向量点积至半精度（2 路）',
    'fdot_za_zzw': '多向量半精度点积至单精度（2 路）',
    'fdot_za_z8z8w': '多向量 8 位浮点数点积至半精度（2 路）',
    'fdot_za32_z8z8i': '多向量 8 位浮点数按索引元素点积至单精度（4 路）',
    'fdot_za32_z8z8v': '多向量 8 位浮点数按向量点积至单精度（4 路）',
    'fdot_za32_z8z8w': '多向量 8 位浮点数点积至单精度（4 路）',
    'fmax_mz_zzv': '多向量浮点数按向量取最大值',
    'fmax_mz_zzw': '多向量浮点数取最大值',
    'fmaxnm_mz_zzv': '多向量浮点数按向量取最大数值',
    'fmaxnm_mz_zzw': '多向量浮点数取最大数值',
    'fmin_mz_zzv': '多向量浮点数按向量取最小值',
    'fmin_mz_zzw': '多向量浮点数取最小值',
    'fminnm_mz_zzv': '多向量浮点数按向量取最小数值',
    'fminnm_mz_zzw': '多向量浮点数取最小数值',
    'fmla_za_zzi': '多向量浮点数按索引元素融合乘加',
    'fmla_za_zzv': '多向量浮点数按向量融合乘加',
    'fmla_za_zzw': '多向量浮点数融合乘加',
    'fmlal_za_zzi': '多向量半精度按索引元素乘加至单精度',
    'fmlal_za_z8z8i': '多向量 8 位浮点数按索引元素乘加至半精度',
    'fmlal_za_zzv': '多向量半精度按向量乘加至单精度',
    'fmlal_za_z8z8v': '多向量 8 位浮点数按向量乘加至半精度',
    'fmlal_za_zzw': '多向量半精度乘加至单精度',
    'fmlal_za_z8z8w': '多向量 8 位浮点数乘加至半精度',
    'fmlall_za32_z8z8i': '多向量 8 位浮点数按索引元素乘加至单精度（全扩展）',
    'fmlall_za32_z8z8v': '多向量 8 位浮点数按向量乘加至单精度（全扩展）',
    'fmlall_za32_z8z8w': '多向量 8 位浮点数乘加至单精度（全扩展）',
    'fmls_za_zzi': '多向量浮点数按索引元素融合乘减',
    'fmls_za_zzv': '多向量浮点数按向量融合乘减',
    'fmls_za_zzw': '多向量浮点数融合乘减',
    'fmlsl_za_zzi': '多向量半精度按索引元素乘减自单精度',
    'fmlsl_za_zzv': '多向量半精度按向量乘减自单精度',
    'fmlsl_za_zzw': '多向量半精度乘减自单精度',
    'fmop4a_za_zz': '浮点数四分之一块外积，累加（非扩展精度）',
    'fmop4a_za32_zz': '半精度四分之一块外积之和累加至单精度（2 路扩展）',
    'fmop4a_za16_z8z8': '8 位浮点数四分之一块外积之和累加至半精度（2 路扩展）',
    'fmop4a_za32_z8z8': '8 位浮点数四分之一块外积之和累加至单精度（4 路扩展）',
    'fmop4s_za_zz': '浮点数四分之一块外积，减法（非扩展精度）',
    'fmop4s_za32_zz': '半精度四分之一块外积之和减法至单精度（扩展精度）',
    'fmopa_za_pp_zz': '浮点数外积，累加（非扩展精度）',
    'fmopa_za32_pp_zz': '半精度外积之和累加至单精度（2 路扩展）',
    'fmopa_za16_pp_z8z8': '8 位浮点数外积之和累加至半精度（2 路扩展）',
    'fmopa_za32_pp_z8z8': '8 位浮点数外积之和累加至单精度（4 路扩展）',
    'fmops_za_pp_zz': '浮点数外积，减法（非扩展精度）',
    'fmops_za32_pp_zz': '半精度外积之和减法至单精度（扩展精度）',
    'fmul_mz_zzv': '多向量浮点数按向量乘法',
    'fmul_mz_zzw': '多向量浮点数乘法',
    'frinta_mz_z': '多向量单精度舍入为整数，四舍五入（远离零）',
    'frintm_mz_z': '多向量单精度舍入为整数，向负无穷方向',
    'frintn_mz_z': '多向量单精度舍入为整数，四舍五入（偶数优先）',
    'frintp_mz_z': '多向量单精度舍入为整数，向正无穷方向',
    'fscale_mz_zzv': '多向量浮点数按向量调整指数',
    'fscale_mz_zzw': '多向量浮点数调整指数',
    'fsub_za_zw': '多向量浮点数从 ZA 数组向量中减法',
    'ftmopa_za_zzzi': '浮点数稀疏外积，累加（非扩展精度）',
    'ftmopa_za32_zzzi': '半精度稀疏外积之和累加至单精度（2 路扩展）',
    'ftmopa_za16_z8z8zi': '8 位浮点数稀疏外积之和累加至半精度（2 路扩展）',
    'ftmopa_za32_z8z8zi': '8 位浮点数稀疏外积之和累加至单精度（4 路扩展）',
    'fvdot_za_zzi': '多向量半精度按索引元素垂直点积至单精度',
    'fvdot_za_z8z8i': '多向量 FP8 垂直点积（按索引元素）累加至半精度 ZA',
    'fvdotb_za32_z8z8i': '多向量 FP8 垂直点积（按索引元素）累加至单精度 ZA（低半）',
    'fvdott_za32_z8z8i': '多向量 FP8 垂直点积（按索引元素）累加至单精度 ZA（高半）',
    'ld1b_mzx_p_bi': '连续加载字节到多个步进向量（立即数索引）',
    'ld1b_mzx_p_br': '连续加载字节到多个步进向量（标量索引）',
    'ld1b_za_p_rrr': '连续加载字节到 ZA 8位元素 tile 切片',
    'ld1d_mzx_p_bi': '连续加载双字到多个步进向量（立即数索引）',
    'ld1d_mzx_p_br': '连续加载双字到多个步进向量（标量索引）',
    'ld1d_za_p_rrr': '连续加载双字到 ZA 64位元素 tile 切片',
    'ld1h_mzx_p_bi': '连续加载半字到多个步进向量（立即数索引）',
    'ld1h_mzx_p_br': '连续加载半字到多个步进向量（标量索引）',
    'ld1h_za_p_rrr': '连续加载半字到 ZA 16位元素 tile 切片',
    'ld1q_za_p_rrr': '连续加载四字到 ZA 128位元素 tile 切片',
    'ld1w_mzx_p_bi': '连续加载字到多个步进向量（立即数索引）',
    'ld1w_mzx_p_br': '连续加载字到多个步进向量（标量索引）',
    'ld1w_za_p_rrr': '连续加载字到 ZA 32位元素 tile 切片',
    'ldnt1b_mzx_p_bi': '连续非临时加载字节到多个步进向量（立即数索引）',
    'ldnt1b_mzx_p_br': '连续非临时加载字节到多个步进向量（标量索引）',
    'ldnt1d_mzx_p_bi': '连续非临时加载双字到多个步进向量（立即数索引）',
    'ldnt1d_mzx_p_br': '连续非临时加载双字到多个步进向量（标量索引）',
    'ldnt1h_mzx_p_bi': '连续非临时加载半字到多个步进向量（立即数索引）',
    'ldnt1h_mzx_p_br': '连续非临时加载半字到多个步进向量（标量索引）',
    'ldnt1w_mzx_p_bi': '连续非临时加载字到多个步进向量（立即数索引）',
    'ldnt1w_mzx_p_br': '连续非临时加载字到多个步进向量（标量索引）',
    'ldr_za_ri': '加载 ZA 阵列向量',
    'ldr_zt_br': '加载 ZT0 寄存器',
    'luti2_mz4_ztz': '使用 2 位索引读查找表（四寄存器）',
    'luti2_z_ztz': '使用 2 位索引读查找表（单寄存器）',
    'luti2_mz2_ztz': '使用 2 位索引读查找表（两寄存器）',
    'luti4_mz4_ztz': '使用 4 位索引读查找表（四寄存器，16/32位元素）',
    'luti4_mz4_ztmz2': '使用 4 位索引读查找表（四寄存器，8位元素）',
    'luti4_z_ztz': '使用 4 位索引读查找表（单寄存器）',
    'luti4_mz2_ztz': '使用 4 位索引读查找表（两寄存器）',
    'mov_mova_mz_za4': '将四个 ZA 单向量组移至 Z 四向量操作数（MOVA 的别名）',
    'mov_mova_mz_za2': '将两个 ZA 单向量组移至 Z 两向量操作数（MOVA 的别名）',
    'mov_mova_mz4_za': '将 ZA 四切片操作数移至 Z 四向量操作数（MOVA 的别名）',
    'mov_mova_z_p_rza': '将 ZA tile 切片移至 Z 向量（MOVA 的别名）',
    'mov_mova_mz2_za': '将 ZA 两切片操作数移至 Z 两向量操作数（MOVA 的别名）',
    'mov_mova_za_mz4': '将 Z 四向量操作数移至四个 ZA 单向量组（MOVA 的别名）',
    'mov_mova_za_mz2': '将 Z 两向量操作数移至两个 ZA 单向量组（MOVA 的别名）',
    'mov_mova_za4_z': '将 Z 四向量操作数移至 ZA 四切片操作数（MOVA 的别名）',
    'mov_mova_za_p_rz': '将 Z 向量移至 ZA tile 切片（MOVA 的别名）',
    'mov_mova_za2_z': '将 Z 两向量操作数移至 ZA 两切片操作数（MOVA 的别名）',
    'mova_mz_za4': '将四个 ZA 单向量组移至 Z 四向量操作数',
    'mova_mz_za2': '将两个 ZA 单向量组移至 Z 两向量操作数',
    'mova_mz4_za': '将 ZA 四切片操作数移至 Z 四向量操作数',
    'mova_z_p_rza': '将 ZA tile 切片移至 Z 向量',
    'mova_mz2_za': '将 ZA 两切片操作数移至 Z 两向量操作数',
    'mova_za_mz4': '将 Z 四向量操作数移至四个 ZA 单向量组',
    'mova_za_mz2': '将 Z 两向量操作数移至两个 ZA 单向量组',
    'mova_za4_z': '将 Z 四向量操作数移至 ZA 四切片操作数',
    'mova_za_p_rz': '将 Z 向量移至 ZA tile 切片',
    'mova_za2_z': '将 Z 两向量操作数移至 ZA 两切片操作数',
    'movaz_mz_za4': '移动并清零四个 ZA 单向量组至 Z 四向量操作数',
    'movaz_mz_za2': '移动并清零两个 ZA 单向量组至 Z 两向量操作数',
    'movaz_mz4_za': '移动并清零 ZA 四切片操作数至 Z 四向量操作数',
    'movaz_z_rza': '移动并清零 ZA tile 切片至 Z 向量',
    'movaz_mz2_za': '移动并清零 ZA 两切片操作数至 Z 两向量操作数',
    'movt_zt_r': '将通用寄存器的 8 字节移至 ZT0',
    'movt_r_zt': '将 ZT0 的 8 字节移至通用寄存器',
    'movt_zt_z': '将向量寄存器移至 ZT0',
    'rdsvl_r_i': '读取流式 SVE 向量寄存器大小的倍数到标量寄存器',
    'sclamp_mz_zz': '多向量有符号按最小/最大值钳位',
    'scvtf_mz_z': '多向量有符号 32 位整数转换为单精度浮点',
    'sdot_za32_zzi': '多向量有符号 16 位整数点积（按索引元素）累加至 32 位整数',
    'sdot_za32_zzv': '多向量有符号 16 位整数点积（按向量）累加至 32 位整数',
    'sdot_za32_zzw': '多向量有符号 16 位整数点积累加至 32 位整数',
    'sdot_za_zzi': '多向量有符号整数点积（按索引元素）',
    'sdot_za_zzv': '多向量有符号整数点积（按向量）',
    'sdot_za_zzw': '多向量有符号整数点积',
    'sel_mz_p_zz': '多向量条件选择',
    'smax_mz_zzv': '多向量有符号最大值（按向量）',
    'smax_mz_zzw': '多向量有符号最大值',
    'smin_mz_zzv': '多向量有符号最小值（按向量）',
    'smin_mz_zzw': '多向量有符号最小值',
    'smlal_za_zzi': '多向量有符号 16 位整数乘加（按索引元素）累加至 32 位整数',
    'smlal_za_zzv': '多向量有符号 16 位整数乘加（按向量）累加至 32 位整数',
    'smlal_za_zzw': '多向量有符号 16 位整数乘加累加至 32 位整数',
    'smlall_za_zzi': '多向量有符号整数长长乘加（按索引元素）',
    'smlall_za_zzv': '多向量有符号整数长长乘加（按向量）',
    'smlall_za_zzw': '多向量有符号整数长长乘加',
    'smlsl_za_zzi': '多向量有符号 16 位整数乘减（按索引元素）从 32 位整数中减',
    'smlsl_za_zzv': '多向量有符号 16 位整数乘减（按向量）从 32 位整数中减',
    'smlsl_za_zzw': '多向量有符号 16 位整数乘减从 32 位整数',
    'smlsll_za_zzi': '多向量有符号整数长长乘减（按索引元素）',
    'smlsll_za_zzv': '多向量有符号整数长长乘减（按向量）',
    'smlsll_za_zzw': '多向量有符号整数长长乘减',
    'smop4a_za32_zz': '有符号 16 位整数四分之一 tile 外积累加至 32 位整数',
    'smop4a_za_zz': '有符号整数四分之一 tile 外积累加',
    'smop4s_za32_zz': '有符号 16 位整数四分之一 tile 外积减至 32 位整数',
    'smop4s_za_zz': '有符号整数四分之一 tile 外积减法',
    'smopa_za32_pp_zz': '有符号 16 位整数外积累加至 32 位整数',
    'smopa_za_pp_zz': '有符号整数外积累加',
    'smops_za32_pp_zz': '有符号 16 位整数外积减至 32 位整数',
    'smops_za_pp_zz': '有符号整数外积减法',
    'sqcvt_z_mz4': '多向量有符号饱和提取窄化（四寄存器）',
    'sqcvt_z_mz2': '多向量有符号 32 位整数饱和提取窄化至 16 位整数（两寄存器）',
    'sqcvtn_z_mz4': '多向量有符号饱和提取窄化至交错整数',
    'sqcvtu_z_mz4': '多向量有符号饱和提取窄化至无符号整数（四寄存器）',
    'sqcvtu_z_mz2': '多向量有符号 32 位整数饱和提取窄化至无符号 16 位整数（两寄存器）',
    'sqcvtun_z_mz4': '多向量有符号饱和提取窄化至交错无符号整数',
    'sqdmulh_mz_zzv': '多向量有符号饱和倍增乘高（按向量）',
    'sqdmulh_mz_zzw': '多向量有符号饱和倍增乘高',
    'sqrshr_z_mz4': '多向量有符号饱和舍入右移窄化（立即数，四寄存器）',
    'sqrshr_z_mz2': '多向量有符号 32 位整数饱和舍入右移窄化至 16 位整数（两寄存器）',
    'sqrshrn_z_mz4': '多向量有符号饱和舍入右移窄化至交错整数',
    'sqrshru_z_mz4': '多向量有符号饱和舍入右移窄化至无符号整数（四寄存器）',
    'sqrshru_z_mz2': '多向量有符号 32 位整数饱和舍入右移窄化至无符号 16 位整数（两寄存器）',
    'sqrshrun_z_mz4': '多向量有符号饱和舍入右移窄化至交错无符号整数',
    'srshl_mz_zzv': '多向量有符号舍入左移（按向量）',
    'srshl_mz_zzw': '多向量有符号舍入左移',
    'st1b_mzx_p_bi': '连续存储字节从多个步进向量（立即数索引）',
    'st1b_mzx_p_br': '连续存储字节从多个步进向量（标量索引）',
    'st1b_za_p_rrr': '连续存储字节从 ZA 8位元素 tile 切片',
    'st1d_mzx_p_bi': '连续存储双字从多个步进向量（立即数索引）',
    'st1d_mzx_p_br': '连续存储双字从多个步进向量（标量索引）',
    'st1d_za_p_rrr': '连续存储双字从 ZA 64位元素 tile 切片',
    'st1h_mzx_p_bi': '连续存储半字从多个步进向量（立即数索引）',
    'st1h_mzx_p_br': '连续存储半字从多个步进向量（标量索引）',
    'st1h_za_p_rrr': '连续存储半字从 ZA 16位元素 tile 切片',
    'st1q_za_p_rrr': '从128位元素ZA tile切片连续存储四字',
    'st1w_mzx_p_bi': '从多个交错向量连续存储字（立即数索引）',
    'st1w_mzx_p_br': '从多个交错向量连续存储字（标量索引）',
    'st1w_za_p_rrr': '从32位元素ZA tile切片连续存储字',
    'stmopa_za32_zzzi': '有符号16位整数稀疏外积累加到32位整数（2路）',
    'stmopa_za_zzzi': '有符号8位整数稀疏外积累加到32位整数（4路）',
    'stnt1b_mzx_p_bi': '从多个交错向量非时序连续存储字节（立即数索引）',
    'stnt1b_mzx_p_br': '从多个交错向量非时序连续存储字节（标量索引）',
    'stnt1d_mzx_p_bi': '从多个交错向量非时序连续存储双字（立即数索引）',
    'stnt1d_mzx_p_br': '从多个交错向量非时序连续存储双字（标量索引）',
    'stnt1h_mzx_p_bi': '从多个交错向量非时序连续存储半字（立即数索引）',
    'stnt1h_mzx_p_br': '从多个交错向量非时序连续存储半字（标量索引）',
    'stnt1w_mzx_p_bi': '从多个交错向量非时序连续存储字（立即数索引）',
    'stnt1w_mzx_p_br': '从多个交错向量非时序连续存储字（标量索引）',
    'str_za_ri': '存储ZA数组向量',
    'str_zt_br': '存储ZT0寄存器',
    'sub_za_zw': '多向量减法写入ZA数组向量（数组与多向量）',
    'sub_za_zzv': '多向量按向量减法写入ZA数组向量',
    'sub_za_zzw': '多向量减法写入ZA数组向量',
    'sudot_za_zzi': '多向量有符号乘无符号8位整数点积（索引元素）累加到32位整数',
    'sudot_za_zzv': '多向量有符号乘无符号8位整数点积（单向量）累加到32位整数',
    'sumlall_za_zzi': '多向量有符号乘无符号8位整数乘加（索引元素）到32位整数',
    'sumlall_za_zzv': '多向量有符号乘无符号8位整数乘加（单向量）到32位整数',
    'sumop4a_za_zz': '有符号乘无符号整数四分之一tile外积累加',
    'sumop4s_za_zz': '有符号乘无符号整数四分之一tile外积累减',
    'sumopa_za_pp_zz': '有符号乘无符号整数外积累加（4路）',
    'sumops_za_pp_zz': '有符号乘无符号整数外积累减',
    'sunpk_mz_z': '解包并符号扩展多向量元素',
    'sutmopa_za_zzzi': '有符号乘无符号8位整数稀疏外积累加到32位整数',
    'suvdot_za_zzi': '多向量有符号乘无符号8位整数垂直点积（索引元素）到32位整数',
    'svdot_za32_zzi': '多向量有符号16位整数垂直点积（索引元素）到32位整数（2路）',
    'svdot_za_zzi': '多向量有符号整数垂直点积（索引元素）（4路）',
    'uclamp_mz_zz': '多向量无符号元素钳位到最小/最大值',
    'ucvtf_mz_z': '多向量无符号32位整数转换为单精度浮点',
    'udot_za32_zzi': '多向量无符号16位整数点积（索引元素）到32位整数（2路）',
    'udot_za32_zzv': '多向量无符号16位整数点积（单向量）到32位整数（2路）',
    'udot_za32_zzw': '多向量无符号16位整数点积到32位整数（2路）',
    'udot_za_zzi': '多向量无符号整数点积（索引元素）（4路）',
    'udot_za_zzv': '多向量无符号整数点积（单向量）（4路）',
    'udot_za_zzw': '多向量无符号整数点积（4路）',
    'umax_mz_zzv': '多向量按向量无符号最大值',
    'umax_mz_zzw': '多向量无符号最大值',
    'umin_mz_zzv': '多向量按向量无符号最小值',
    'umin_mz_zzw': '多向量无符号最小值',
    'umlal_za_zzi': '多向量无符号16位整数乘加（索引元素）到32位整数',
    'umlal_za_zzv': '多向量无符号16位整数乘加（单向量）到32位整数',
    'umlal_za_zzw': '多向量无符号16位整数乘加到32位整数',
    'umlall_za_zzi': '多向量无符号整数长长乘加（索引元素）',
    'umlall_za_zzv': '多向量无符号整数长长乘加（单向量）',
    'umlall_za_zzw': '多向量无符号整数长长乘加',
    'umlsl_za_zzi': '多向量无符号16位整数乘减（索引元素）从32位整数',
    'umlsl_za_zzv': '多向量无符号16位整数乘减（单向量）从32位整数',
    'umlsl_za_zzw': '多向量无符号16位整数乘减从32位整数',
    'umlsll_za_zzi': '多向量无符号整数长长乘减（索引元素）',
    'umlsll_za_zzv': '多向量无符号整数长长乘减（单向量）',
    'umlsll_za_zzw': '多向量无符号整数长长乘减',
    'umop4a_za32_zz': '无符号16位整数四分之一tile外积累加到32位整数（2路）',
    'umop4a_za_zz': '无符号整数四分之一tile外积累加（4路）',
    'umop4s_za32_zz': '无符号16位整数四分之一tile外积累减到32位整数（2路）',
    'umop4s_za_zz': '无符号整数四分之一tile外积累减（4路）',
    'umopa_za32_pp_zz': '无符号16位整数外积累加到32位整数（2路）',
    'umopa_za_pp_zz': '无符号整数外积累加（4路）',
    'umops_za32_pp_zz': '无符号16位整数外积累减到32位整数（2路）',
    'umops_za_pp_zz': '无符号整数外积累减（4路）',
    'uqcvt_z_mz4': '多向量无符号饱和窄化提取（四寄存器）',
    'uqcvt_z_mz2': '多向量无符号32位整数饱和窄化提取为16位整数（两寄存器）',
    'uqcvtn_z_mz4': '多向量无符号饱和窄化提取为交错整数',
    'uqrshr_z_mz4': '多向量无符号饱和舍入右移窄化（立即数，四寄存器）',
    'uqrshr_z_mz2': '多向量无符号32位整数饱和舍入右移窄化为16位整数（立即数，两寄存器）',
    'uqrshrn_z_mz4': '多向量无符号饱和舍入右移窄化为交错整数（立即数）',
    'urshl_mz_zzv': '多向量无符号舍入左移（按向量）',
    'urshl_mz_zzw': '多向量无符号舍入左移',
    'usdot_za_zzi': '多向量无符号乘有符号8位整数点积（索引元素）到32位整数（4路）',
    'usdot_za_zzv': '多向量无符号乘有符号8位整数点积（单向量）到32位整数（4路）',
    'usdot_za_zzw': '多向量无符号乘有符号8位整数点积到32位整数（4路）',
    'usmlall_za_zzi': '多向量无符号乘有符号8位整数乘加（索引元素）到32位整数',
    'usmlall_za_zzv': '多向量无符号乘有符号8位整数乘加（单向量）到32位整数',
    'usmlall_za_zzw': '多向量无符号乘有符号8位整数乘加到32位整数',
    'usmop4a_za_zz': '无符号乘有符号整数四分之一tile外积累加',
    'usmop4s_za_zz': '无符号乘有符号整数四分之一tile外积累减',
    'usmopa_za_pp_zz': '无符号乘有符号整数外积累加（4路）',
    'usmops_za_pp_zz': '无符号乘有符号整数外积累减',
    'ustmopa_za_zzzi': '无符号乘有符号8位整数稀疏外积累加到32位整数',
    'usvdot_za_zzi': '多向量无符号乘有符号8位整数垂直点积（索引元素）到32位整数',
    'utmopa_za32_zzzi': '无符号16位整数稀疏外积累加到32位整数（2路）',
    'utmopa_za_zzzi': '无符号8位整数稀疏外积累加到32位整数（4路）',
    'uunpk_mz_z': '解包并零扩展多向量元素',
    'uvdot_za32_zzi': '多向量无符号16位整数垂直点积（索引元素）到32位整数（2路）',
    'uvdot_za_zzi': '多向量无符号整数垂直点积（索引元素）（4路）',
    'uzp_mz_z': '从四个向量拼接元素',
    'uzp_mz_zz': '从两个向量拼接元素',
    'zero_za2_ri': '清零ZA双向量组',
    'zero_za4_ri': '清零ZA四向量组',
    'zero_za1_ri': '清零ZA单向量组',
    'zero_zt_i': '清零ZT0',
    'zero_za_i': '清零指定的64位元素ZA tile列表',
    'zip_mz_z': '从四个向量交错排列元素',
    'zip_mz_zz': '从两个向量交错排列元素',
}
